### ISSUE TITLE
Run bash with an initialization command

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#100]
Hi,
I was trying to run bash with an initialization command but I have failed.

I have tried this:
`busybox bash --init-file <(echo "alias another_ls=ls")`
and this:
`busybox bash -c "exec bash --init-file ^<(echo 'alias another_ls=ls')"`

What have I done wrong?

**Comment by rmyorston** [comment]
BusyBox bash is really just ash with a few bash-like features. It doesn't support ```--init-file``` or process substitution ```<(...)```.

**Comment by ale5000-git** [comment]
Is there an alternative way to execute a comands and remain inside ash without exit?

**Comment by rmyorston** [comment]
Hmm, I need more context on what you're trying to do.

A login shell (```sh -l```) will try to run /etc/profile or ```$HOME/.profile```.

Since ash is a POSIX shell it handles the ```ENV``` environment variable like this (even if it isn't a login shell):

> This variable, when and only when an interactive shell is invoked, shall be subjected to parameter expansion (see Parameter Expansion) by the shell and the resulting value shall be used as a pathname of a file containing shell commands to execute in the current environment. The file need not be executable. If the expanded value of ENV is not an absolute pathname, the results are unspecified.

So:

```
$ cat ~/startup
alias another_ls=ls
$ ENV=~/startup PS1='New sh: ' sh
New sh: another_ls startup
startup
New sh: exit
$ 
```

**Comment by ale5000-git** [comment]
I would like, from inside a Windows ".bat" file, to execute a ash shell and inside it execute `alias another_ls=ls` and then live it opened interactively.
I would like to execute the command without store it in a file.

To put it more simple I want to automate the operation of:
run `busybox ash` and `alias another_ls=ls` and wait user intervention.

**Comment by ale5000-git** [comment]
This will do the same thing that I want but it open the normal Windows command prompt:
`cmd.exe /k "DOSKEY another_ls=busybox ls"`
After this command if I type `another_ls` I get file listing.

I'm trying to do the same but with ash.

**Comment by rmyorston** [comment]
I think this does what you want:
```
busybox sh -s -c "alias another_ls=ls"
```
The ```-s``` flag seems to be an ash-ism. It isn't mentioned in POSIX and it doesn't work in bash. It does, however, work in BusyBox ash, dash and /bin/sh in FreeBSD, all of which are derived from ash.

**Comment by ale5000-git** [comment]
It is exactly what I need, thanks.
