### ISSUE TITLE
timeout should support standard exit codes

### ISSUE THREAD

**Issue by alejandro5042** [rmyorston/busybox-w32#105]
```
124 if command times out
125 if timeout itself fails
126 if command is found but cannot be invoked
127 if command cannot be found
137 if command is sent the KILL(9) signal (128+9)
the exit status of command otherwise
```

Source: https://www.gnu.org/software/coreutils/manual/coreutils.html#timeout-invocation

In my scripts, I need to know if the command completed successfully or timed out. Also, I need the exit code of the command I was running. Currently timeout only returns 0.

Also relevant:

> ‘--preserve-status’
> Return the exit status of the managed command on timeout, rather than a specific exit status indicating a timeout. This is useful if the managed command supports running for an indeterminate amount of time.

**Comment by rmyorston** [comment]
```timeout``` in busybox-w32 should now support exit status as specified by coreutils.

The implementation of ```timeout``` in upstream BusyBox is quite different and doesn't support coreutils exit status.

**Comment by alejandro5042** [comment]
Browsing the commit, it looks like what I want. Wow, thanks for the turnaround!

I consume this via [scoop](https://github.com/lukesampson/scoop/), which looks for an official release on your website. When is the next scheduled release? I'd love to use this :)

Note: It seems like there's one more instance of `EXIT_FAILURE` where it might need to be `125 if timeout itself fails`? Unsure, just bringing it up.

**Comment by alejandro5042** [comment]
> The implementation of timeout in upstream BusyBox is quite different and doesn't support coreutils exit status.

Should upstream BusyBox also support the--IMO--more complete behavior?

**Comment by rmyorston** [comment]
> When is the next scheduled release?

There isn't a schedule, I just make a release when it feels right to do so. We're not quite at that point yet:
- there have been two releases this month already and I try not to make them too frequent; 
- there are a couple of things I want to investigate further in ```timeout```.

> Note: It seems like there's one more instance of ```EXIT_FAILURE``` where it might need to be ```125 if timeout itself fails```? 

If you mean the explicit reference to ```EXIT_FAILURE``` that's still present, then no, that's not in the WIN32 part of the code. If you mean that ```getopt``` will return  ```EXIT_FAILURE``` if an invalid option is detected, then yes, that's now been fixed to return 125.

> Should upstream BusyBox also support the--IMHO--more complete behavior?

That's a matter for the upstream maintainer. If there's pressure for the change (and a patch implementing it) I'm sure they'd consider it. As always with BusyBox, though, there's a trade-off between features and size so the response might be "No".

I try to keep differences between busybox-w32 and upstream to a minimum. In this case, though, the code was already so different that implementing your request didn't increase the divergence. I'm not _too_ happy about the extra 80 bytes the feature costs but I can see its usefulness.

**Comment by rmyorston** [comment]
A new binary with these changes is now available on my website.

**Comment by alejandro5042** [comment]
I can confirm that exit code 124 (command timed out) work as expected. Thank you! This is a big improvement for the `timeout` command.

As far as the other features, I think I now understand the philosophy behind BusyBox and why it has a limited feature set. Makes sense.
