### ISSUE TITLE
Working directly not realiably detected when executing scripts

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#106]
If I do this it  doesn't work:
- double click on `my_test.bat`
- run `script.sh` (problem, it say `ash: script.sh: not found`)
- run `./script.sh` (it now display 1)

Instead if I do this instead it work directly:
- run `cmd.exe`
- cd to the script folder
- run `busybox ash`
- run `script.sh`
- it now display 1

Content of `my_test.bat`:
> busybox ash

Content of `script.sh`:
> #!/usr/bin/env ash
> 
> echo 1

**Comment by rmyorston** [comment]
I don't know why it's working in one case but not the other.

The fact that you have to run the script as ```./script.sh``` suggests that the directory containing the script isn't in ```PATH```. But then I wouldn't expect the second case to work either.

**Comment by ale5000-git** [comment]
The script is not in `PATH` but it is in the working directory, I expect that it always look here.

Am I wrong?

**Comment by rmyorston** [comment]
If the current directory isn't in ```PATH``` the shell won't look for executables there.
