### ISSUE TITLE
ash: cd: can't cd to ls: No such file or directory

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#109]
Using `cd \` probably cause strange behaviours.

I get this:
```
C:\Users\MyUser>busybox ash
~ $ cd \
> ls
ash: cd: can't cd to ls: No such file or directory
~ $
```

**Comment by rmyorston** [comment]
The backslash character has special meaning in the shell: that the following character _doesn't_ have any special meaning.

Putting a backslash before a newline tells the shell that the newline doesn't have it's normal meaning as an end of line marker. Notice how the prompt changed to ```>``` to show that the shell was expecting more text for the current command, not a new command.

This is commonly used in shell scripts to split long commands across lines:
```
git archive --format=tar --prefix=busybox-w32/ HEAD | \
        gzip -c >$FRIPWEB/busybox-w32-$DESC.tgz
```

You can prevent a backslash from having _it's_ special meaning by typing two backslashes together or by putting it in single quotes. On the whole, though, it's best not to use backslash as a file separator in the shell. As it says in README.md:

> Use forward slashes in paths: Windows doesn't mind and the shell will be happier.

**Comment by ale5000-git** [comment]
Ok, thanks.
