### ISSUE TITLE
Shell redirection

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#111]
Hi,
is there a way to do the same of this command with BusyBox?

`exec > >(tee "./debug.log") 2>&1`

**Comment by rmyorston** [comment]
That command will copy all output to the log file. If this is part of a script you might be able to wrap the whole thing in a subshell:
```
#!/bin/bash

#exec > >(tee "./debug.log") 2>&1
(
echo "hello stdout"
echo "hello stderr" >&2
) 2>&1 | tee "./debug.log"
```

**Comment by ale5000-git** [comment]
Thanks, but with this I cannot turn it on/off at runtime based on user input.

**Comment by rmyorston** [comment]
> Thanks, but with this I cannot turn it on/off at runtime based on user input.

That's called "moving the goalposts" ;-)

Can you wrap the stuff that needs to be logged into a function or a separate script?
```
#!/bin/bash

#exec > >(tee "./debug.log") 2>&1
everything() {
echo "hello stdout"
echo "hello stderr" >&2
}

echo -n "Redirect: "
read a

if [ "$a" = "y" ]
then
	everything 2>&1 | tee "./debug.log"
else
	everything
fi
```

**Comment by ale5000-git** [comment]
Sorry, I initially thought of not complicating too much the "help request" but actually I have 2 functions to enable/disable dynamically (event multiple times) the redirection that currently are disabling the output but I do want instead keep also the output.

```
enable_debug_log()
{
  if [ "$DEBUG_LOG_ENABLED" -eq 1 ]; then return; fi
  DEBUG_LOG_ENABLED=1
  exec 3>&1 4>&2  # Backup stdout and stderr
  exec 1>>"$ZIP_PATH/debug.log" 2>&1
}

disable_debug_log()
{
  if [ "$DEBUG_LOG_ENABLED" -eq 0 ]; then return; fi
  exec 1>&3 2>&4  # Restore stdout and stderr
  DEBUG_LOG_ENABLED=0
}
```

Today I have found the named pipe that may be helpful for my use case but I haven't tried it yet.

**Comment by ale5000-git** [comment]
@rmyorston: I can do waht I want but I miss mkfifo
Could you please enable it, it is inside upstream busybox?

**Comment by rmyorston** [comment]
Unfortunately ```mkfifo(1)``` uses the ```mkfifo(3)``` function, which isn't available in Microsoft Windows.

It's probably possible to implement ```mkfifo(3)``` but, as Deep Thought said, "I'll have to think about it".

**Comment by rmyorston** [comment]
It looks as though it won't be possible to implement ```mkfifo(3)``` for WIN32. Named pipes in Linux live in the filesystem, in Windows they don't.

**Comment by ale5000-git** [comment]
Isn't possible to do it with the [Windows API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365590(v=vs.85).aspx)?

**Comment by rmyorston** [comment]
Named pipes in Windows only exist for as long as the server that created them. On Linux named pipes exist in the filesystem so it's possible to:

- use ```mkfifo``` to create a special FIFO file
- start a process to write to the file
- start another process to read from the file

The two processes think they're just talking to a file.

On Windows you have to have a server process that creates the named pipe. It needs to know the special magic to do that. Then clients can connect to the server.

It's a different mode of operation.

**Comment by ale5000-git** [comment]
Can the base busybox shell process create the named pipe so that all sub-shells can use it?
If possible that I think that could be fine for basic uses, also explaining the difference in the --help.

**Comment by rmyorston** [comment]
> Can the base busybox shell process create the named pipe so that all sub-shells can use it?

No, the point of the FIFO is to allow unrelated processes to talk to one another. This would just allow process to talk to the base shell.

**Comment by sergeevabc** [comment]
Dear @rmyorston, could we have ```sponge``` in Busybox?
It would allow us to proceed as follows without extra files.

```
rem Removing duplicates
awk "!line[$0]++" hostnames.txt | sponge hostnames.txt
```
Alas, ```tee``` is not applicable here, because it would print a huge ```hostnames.txt``` to the screen as well.

**Comment by rmyorston** [comment]
>could we have sponge in Busybox?

Maybe. The upstream BusyBox maintainer is clearly aware of moreutils, as they added the ```ts``` utility from there. You'd need to persuade them that ```sponge``` is worthwhile.

**Comment by sergeevabc** [comment]
@rmyorston, I wrote a letter to Denys, who is mentioned as the maintainer at [busybox.net][1]’s footer.

[1]: https://busybox.net/

**Comment by rmyorston** [comment]
I kept this issue open as a reminder that process substitution wasn't implemented in BusyBox. It took a while, but now it is. The latest [prerelease binary](https://frippery.org/files/busybox/prerelease) has support for it.

Open a new issue for any problems.

**Comment by sergeevabc** [comment]
Err?

```console
$ busybox
BusyBox v1.34.0-PRE-4095-gabe872e2a (2021-06-07 12:00:34 BST)
$ busybox sponge
sponge: applet not found
```
