### ISSUE TITLE
Broken read -n1

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#112]
Hi,
I have tried in [Live BusyBox](https://busybox.net/live_bbox/live_bbox.html) and `read -n1` return after reading a single character without waiting the newline, instead on Windows it wait the newline.

Could it be fixed please?

**Comment by ale5000-git** [comment]
@rmyorston: I'm not sure if it is already fixed with the latest changes but using `read -s` doesn't hide the input and it is bad for asking passwords.

**Comment by rmyorston** [comment]
Yes, the latest fixes do make ```read -s``` work.

**Comment by ale5000-git** [comment]
Thanks.
