### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by j16180339887** [rmyorston/busybox-w32#114]
It would be nice to have a choco package of busybox.

Something like `choco install busybox` to install it.

Is this on the roadmap? thanks :)

**Comment by rmyorston** [comment]
This is a duplicate of issue #24.

The situation hasn't changed since then: this isn't something I'm planning to work on.

**Comment by j16180339887** [comment]
Thanks, I will try scoop instead of chocolatey.
