### ISSUE TITLE
Regression: 'sh -i' does not work if stdin is not a windows console.

### ISSUE THREAD

**Issue by Ronsor** [rmyorston/busybox-w32#115]
Reproducing:

1. Download the latest build
2. Open a MSYS shell
3. Run the 'busybox.exe' binary as 'busybox sh -i'
4. Observe that it exits immediately

Contrast this with running an older build such as this one: https://frippery.org/files/busybox/busybox-w32-FRP-403-ga89270b.exe

That one works fine.

**Comment by rmyorston** [comment]
Fixed in git. The last binary without this issue is busybox-w32-FRP-2001-gd9c5d3c61.exe.

I'm curious why you're using busybox-w32 with MSYS, though.

**Comment by Ronsor** [comment]
I'm not, but I was testing it with a SSH server I was writing, and found out that it had these issues with `-i`; then I tried in MSYS.
