### ISSUE TITLE
[suggestion] adding a Windows 10 compatible manifest

### ISSUE THREAD

**Issue by eladkarako** [rmyorston/busybox-w32#120]
adding an embedded manifest, 
will greatly assist all your Windows 10 users,

here is an example from git-for-windows
<sub>which also distributes a busybox for Windows btw. <br/>in their https://github.com/git-for-windows/git/releases/download/v2.18.0.windows.1/MinGit-2.18.0-busybox-32-bit.zip</sub>

https://github.com/git-for-windows/git/blob/master/git.rc
https://github.com/git-for-windows/git/blob/master/compat/win32/git.manifest

<hr/>
I've avoid recompiling by slightly modifying https://frippery.org/files/busybox/busybox.exe
with <a href="https://github.com/eladkarako/manifest/blob/master/generic.manifest">generic.manifest</a> using my <a href="https://github.com/eladkarako/manifest/">manifest tool</a>.

**Comment by rmyorston** [comment]
I've created a 'manifest' branch which has commit 2ed6dd86c. Does it look OK?

**Comment by eladkarako** [comment]
looks peachy 🍑︎ ,

..but
..you <strong>may</strong> skip the whole sed injecting-version part, <em>(although quite clever..)</em>.
identity-sections are useful for shared-library files (dll), less for exes,
(also- manifest-files needs Windows EOL and sed uses <code>\n</code>),

best to just include a static file, 
either with just the name and a 'foo' version: <a href="https://github.com/git-for-windows/git/blob/master/compat/win32/git.manifest">#1</a>, 
or skipping this part all together: <a href="https://github.com/eladkarako/manifest/blob/master/generic.manifest">#2</a>.

**Comment by eladkarako** [comment]
looks peachy 🍑︎ ,

..but
..you <strong>may</strong> skip the whole sed injecting-version part, <em>(although quite clever..)</em>.
identity-sections are useful for shared-library files (dll), less for exes,
<sub>(also- manifest-files needs Windows EOL and that sed+STDOUT <code>&gt;</code> will uses <code>\n</code>),</sub>

best to just include a static file, 
either with just the name and a 'foo' version: <a href="https://github.com/git-for-windows/git/blob/master/compat/win32/git.manifest">#1</a>, 
or skipping this part all together: <a href="https://github.com/eladkarako/manifest/blob/master/generic.manifest">#2</a>.

**Comment by rmyorston** [comment]
If I'm going to include a version number I'd prefer to have the _correct_ version number, even if nobody uses it.

Fixing the line endings should be simple enough: use CRLF in the source file and change the command to ```sed -b```, which is supported in GNU sed and various Windows versions of sed so it should  be cross-platform(-ish).

**Comment by rmyorston** [comment]
The manifest has been updated as suggested above and is included in the latest binary release.
