### ISSUE TITLE
Recursive wildcard

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#122]
It seems that recursive wildcard isn't supported.

Example:
`touch **`

Is there a way to enable it?

**Comment by rmyorston** [comment]
The use of ```**``` as a recursive wildcard seems to be a bashism.  It isn't supported in BusyBox ash.

**Comment by ale5000-git** [comment]
Is there an alternative standard way for recursive wildcard?

**Comment by rmyorston** [comment]
Not that I'm aware of.

There's always ```find```, of course.

**Comment by ale5000-git** [comment]
Ok, thanks :)
