### ISSUE TITLE
Prepackaged exe & Install Script

### ISSUE THREAD

**Issue by limeb** [rmyorston/busybox-w32#124]
Could we maybe show a prepackaged exe or alternatively give a script(powershell or cmd.exe) that installs everything needed to get the install working?

Alternatively is there a package manager for Windows that is up to date?

**Comment by rmyorston** [comment]
What would an installer or script do? I just dump the binary somewhere and make a shortcut on the desktop manually.

It's possible to install busybox-w32 using [Scoop](https://scoop.sh/). They seem to pick up new binaries within moments of release.

**Comment by limeb** [comment]
installed with scoop thank you.
