### ISSUE TITLE
Configure extension auto-complete at runtime

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#126]
Hi,
is it possible to configure it at runtime?

For example, if I run from ash shell `./my_script` I would like that it execute the file `my_script.sh` if the file without extension doesn't exist (and also com, exe, bat, cmd not exist).

**Comment by rmyorston** [comment]
You mean by having the shell respect the ```PATHEXT``` environment variable? Then you could add ```.sh``` as a supported extension.

It's possible, though it would need a bit of work. Hardcoding ```.sh``` would be easier. Though if I did that all the Perl programmers would then want ```.pl``` added too.

**Comment by rmyorston** [comment]
Commit 6c3fd20e6 adds hardcoded special treatment for files with the ```.sh``` extension.

I looked at implementing a more generic solution but the cost was too great. This commit adds 52 bytes while a partial solution using ```PATHEXT``` required 288 bytes. The environment variable has to be parsed to ensure it doesn't contain garbage and, as mentioned above, the shell has to update the suffixes when they change. It's a lot more code.

A full generic solution would probably need to use a different environment variable.  On my systems ```PATHEXT``` includes extensions like ```.JS``` and ```.WSH``` which can't be handled by ```spawnve()```. Supporting these is probably out of scope for busybox-w32.

**Comment by ale5000-git** [comment]
Maybe busybox could import PATHEXT (with the unsupported extensions stripped) when busybox is importing environment variable from Windows and save as PATHEXT_BB inside busybox.

By the way, I'm already satisfied with the current solution.

**Comment by rmyorston** [comment]
Yes, ```#!/usr/bin/env executable_name``` works as expected.
