### ISSUE TITLE
How to grep UTF-16LE file?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#129]
Hi,
I'm trying this:
`busybox grep -Eq 'A\x00' abc.txt && echo 'OK' || echo 'NO'`

But it doesn't seems to work.

Is there any alternative?

**Comment by ale5000-git** [comment]
After various attempts I have come up with this function:
```
search_ansi_string_in_utf16_file()
{
  local SEARCH_STRING=$(echo -n "$1" | od -A n -t x1 | cut -c 2- | head -c -1 | tr '\n', ' ' | sed 's/ /00/g')
  od -A n -t x1 "$2" | tr -d ' \n' | grep -qF "$SEARCH_STRING" && return 0  # Found
  return 1  # NOT found
}
```

It works but it is a bit ugly.

**Comment by rmyorston** [comment]
I don't have a better alternative but this does make me think that perhaps BusyBox ought to have an implementation of ```iconv(1)```. I'll look into it.

**Comment by rmyorston** [comment]
I've imported a WIN32 implementation of iconv from [win-iconv](https://github.com/win-iconv/win-iconv) into busybox-w32.

**Comment by ale5000-git** [comment]
Thanks.
