### ISSUE TITLE
file order when creating a zip (printing the file list give the same problems)

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#132]
I'm not sure if the problem is here but i'm not able to list files in the same order (to create a zip) on Linux (standard bash shell) vs Windows (busybox).

Attempts:
- `ls -1 --color=never | sort -f | zip -r9X "myzip.zip" -@` => different on Windows vs Linux since ls list only the main folder and the zip take the content of subfolder but with its own ordering different on Windows vs Linux
- `find . | sort -f | zip -9X "myzip.zip" -@` => they get a [strange order](https://travis-ci.com/a5k-testing/unzip-test/builds/96716549) (not correct)

---------------------------------------------------------------

The last attempt is the most similar:
```
list_files()  # $1 => Folder to scan
{
  test -d "$1" || return
  for entry in "$1"/*; do
    if test -d "${entry}"; then
      list_files "${entry}"
    else
      printf '%s\n' "${entry}"
    fi
  done
}
list_files . | sort -f | zip -9X "myzip.zip" -@
```
But it is still different.

Order on Linux:
```
./files/app/DejaVuBackend.apk
./files/app/IchnaeaNlpBackend.apk
./files/app-legacy/LegacyNetworkLocation.apk
./files/app/NewPipe.apk
./files/app/NominatimGeocoderBackend.apk
```

Order on Windows:
```
./files/app-legacy/LegacyNetworkLocation.apk
./files/app/DejaVuBackend.apk
./files/app/IchnaeaNlpBackend.apk
./files/app/NewPipe.apk
./files/app/NominatimGeocoderBackend.apk
```

Am I missing something?

**Comment by rmyorston** [comment]
When I put your filenames in a file and sort it using ```sort -f files.txt``` I get the same order on Windows and Linux (the one you get for Windows).

Are you quoting the output of ```sort -f``` or the order of the files in the zip?

**Comment by ale5000-git** [comment]
Is there a simple way to quote the output of sort -f?

In every case also simply using [find . | sort -f](https://github.com/a5k-testing/unzip-test/blob/test-find/build.sh#L184) give the wrong result: https://travis-ci.com/a5k-testing/unzip-test/builds/96716549#L1000

**Comment by rmyorston** [comment]
I can get your weird sort order on Fedora Linux using ```sort -df```, that is, a case-insensitive sort in dictionary order, considering only blanks and alphanumerics, thus ignoring slashes and dashes.

On Ubuntu I get your weird order, so it looks as though they default to dictionary order.  If I use ```LANG=c sort -f``` on Ubuntu I get the sensible order.

**Comment by ale5000-git** [comment]
Thanks, you rock :)

On Travis CI it insist on using the dictionary order but thanks to your comment I have found that `LC_ALL=C sort -f` fixed it.
