### ISSUE TITLE
How detect attrib failure?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#133]
This display 0:
```
busybox ash
attrib -a unexistent_file
echo $?
```

Is there a way to detect when attrib fail?

**Comment by rmyorston** [comment]
If it doesn't return a useful exit code I guess not. I suppose you could check the file yourself:
```test -f filename && attrib -a filename```.

**Comment by ale5000-git** [comment]
Well, I gues it is a limitation of attrib itself, thanks.
