### ISSUE TITLE
Accessing different drive letters

### ISSUE THREAD

**Issue by rawganet** [rmyorston/busybox-w32#134]
I noticed that it always put the main Windows `C:` drive on `/`, making other drives unacessible. 

Is there any way to access these additional drives? If not, is it feasible to implement it?

Thanks you very much! This project has been very useful.

**Comment by rmyorston** [comment]
On UNIX-like systems each process has a current directory; DOS-like systems (such as Microsoft Windows) maintain a separate record of the current drive and current directory. If a file path is given without a drive prefix the current drive is assumed.

If the current drive is C: any of the commands ```ls c:/```, ```ls c:``` or ```ls /``` will list the contents of the root of the C: drive.  To see what's in the D: drive use ```ls d:/``` or ```ls d:```.

To switch to a directory on the D: drive use ```cd d:/``` in the busybox-w32 shell. This makes D: the current drive, so now references to file paths without a drive prefix will use D:.

(To change the current drive from the Windows command prompt enter ```d:```, the ```cd``` command only changes the directory.)

**Comment by ale5000-git** [comment]
On Windows command prompt you can also use cd /d d:/patch to change both

**Comment by rawganet** [comment]
Awesome, thanks @rmyorston and @ale5000-git for the help.
