### ISSUE TITLE
Wget digest authentication and proxy

### ISSUE THREAD

**Issue by deajan** [rmyorston/busybox-w32#137]
Hello,

I am currently designing a "rescue" bash script that needs to download & upload some data to a https server.
My problem is that I need to rely solely on busybox executable, without any external curl, in order for my rescue to be as portable as it can.

I've found standard wget supports digest via:
```
wget --digest --http-user=admin --http-password=aaa --post-data=$mydataz https://someurl
```

So far, reading wget.c suggests that busybox wget implementation does not support digest, am I right ?
Any chances this may happen ?

I'm currently using busybox wget with basic auth like
```
wget http://user:pass@someurl --post-data="$(cat mydatafile)" -O - > /dev/null 2>&1
```

Also, I don't understand the ```--proxy on``` option, does it use system settings ? Couldn't find any --proxy=url paramter

Best regards.

**Comment by rmyorston** [comment]
I'm by no means an expert on wget, but it seems that the BusyBox implementation doesn't support digest authentication. Since this isn't a Windows-specific issue I'd prefer that it be fixed upstream.

It looks as though the proxy settings need to be placed in the environment variables ```ftp_proxy``` and ```http_proxy```.

**Comment by ale5000-git** [comment]
@deajan
You should open a ticket [here](https://bugs.busybox.net/).

Once it is added to the upstream BusyBox it will likely be ported in all other versions.

**Comment by deajan** [comment]
Thanks for your answers, posted the feature request.
@rmyorston Thanks for the environment variables hints.

**Comment by deajan** [comment]
Just to be sure if this needs to be posted here or upstream:
Setting http_proxy as environment variable will force proxy usage regardless of missing --proxy on parameter:

```
export http_proxy=127.0.0.1:3128
wget google.fr --proxy on
Connecting to 127.0.0.1:3128 (127.0.0.1:3128)
wget google.fr
Connecting to 127.0.0.1:3128 (127.0.0.1:3128)
wget google.fr --proxy off
Connection to (googleIP)
```

**Comment by rmyorston** [comment]
That is the documented behaviour. From the man page for wget 1.8.1:
```
   -Y on/off
  --proxy=on/off
     Turn proxy support on or off. The proxy is on by default if
     the appropriate environment variable is defined.
```
Actually, wget 1.8.1 dates from 2002 when this feature was implemented in BusyBox. (I checked the man page in a Red Hat Linux 7.3 virtual machine of that vintage.)

In more modern versions of wget those options have been replaced by --no-proxy, though BusyBox hasn't kept pace.

**Comment by deajan** [comment]
Thanks, and sorry for the noise.
