### ISSUE TITLE
shell: DOS-style linefeeds not handled sensibly

### ISSUE THREAD

**Issue by Xjs** [rmyorston/busybox-w32#138]
I tried to use busybox-w32 as a lightweight variant of giving [Bazel](https://bazel.build) a shell.

(NB: Bazel currently depends on a Posix shell, and I currently use mingw-bash on Windows, but we would like to replace it with something lighter as long as Bazel's shell dependency hasn't been ruled out yet.)

However, when running bazel with busybox-w32, I noticed that due to how commands are executed from Starlark files, it can happen that Bazel tries to execute `sh -c <command string that can contain \r\n>`. The busybox shell will (correctly) separate commands by \n, but will be confused by the \r-s and attempt to parse them as part of the command. This leads to e. g. `set` complaining about an unknown parameter `-\r` because the first line of some command is `set -ex\r\n` (linefeed characters typed out for clarity). 

`\r\n`-style linebreaks are very common in the Windows world, so it seems sensible that busybox-w32 should handle them gracefully. However, I understand that there are several leverage points to improve this, each one of which could subtly introduce unwanted or unexpected behaviour if not handled carefully. (I, personally, would probably say the shell should just ignore \r characters altogether, this will probably break the least behaviour. Another option would be to preprocess the minusc command-line argument not to contain \r, this has less impact but is a stronger specialisation and won't fix other cases where \r characters might break the shell's behaviour.)

As for me, in light of this issue I will probably search for another alternative for our use with Bazel. Still, I wanted to raise awareness for the general issue and am open for discussion. :) I don't know how well the other busybox tools handle \r\n linefeeds, maybe there are more things to be learned.

**Comment by ale5000-git** [comment]
This is probably the problem already fixed [here](https://github.com/rmyorston/busybox-w32/commit/8e55f1eabc0632d6060caf1c0bf9325ac1cc19c2) but it isn't yet included in the precompiled executable.

**Comment by rmyorston** [comment]
The issue of line endings is a known problem.

busybox-w32 defaults to opening files and pipes in binary mode and deals with \r in text as required. The main exception is ```vi```, which always uses text mode to read and write files.

The shell ignores \r when running scripts from files. I'll have a look at what's going on with the ```-c``` string.

**Comment by rmyorston** [comment]
Here's how I reproduced the issue:
```
awk 'BEGIN {
	"set -ex\r\npwd\r\n" | getline
}' </dev/null
```
The pipe in ```awk``` is implemented by calling ```popen(3)``` which passes the string verbatim to ```sh -c```. As noted above the ```set``` built-in attempts to treat the carriage return as an option. This fails on Unix and in busybox-w32 ash.

Commit 0aad680 removes carriage returns from the string before evaluation.

**Comment by Xjs** [comment]
Wow. I didn't expect this to be fixed this quickly. Thanks very much! :)

I'll give the fixed version a try right away.
