### ISSUE TITLE
Wget -qO- is not really quiet

### ISSUE THREAD

**Issue by Klexer** [rmyorston/busybox-w32#139]
Whenever I enter wget -qO- then I get the following message:

~ $ wget -qO- frippery.org/files/busybox | grep -v ""
writing to stdout
written to stdout

That did not exist in the past releases.

**Comment by rmyorston** [comment]
The noise was introduced in the upstream commit [wget: notify on download begin and end](https://git.busybox.net/busybox/commit/?id=46fc3290c20a0468c02bd771a8c548c0e1b23e47). They later realised the problem and fixed it with commit [wget: don't notify on download begin and end if quiet](https://git.busybox.net/busybox/commit/?id=94e748d0276a089ca9093767d15b5d050e0218b1).

I synced busybox-w32 with upstream between those two commits so we currently suffer from the noise. It'll go away the next time I synchronise.

**Comment by rmyorston** [comment]
busybox-w32 has been synced with upstream. ```wget``` in the latest binary respects the ```-q``` option.
