### ISSUE TITLE
Inconsistences in cd

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#144]
When you are on C:/ you get (commands do nothing but doesn't display errors):
```
C:/ $ cd /
C:/ $ cd ..
```

Instead on a network folder (they error out):
```
//ca/LANTEST $ cd /
ash: cd: can't cd to /: Invalid argument
//ca/LANTEST $ cd ..
ash: cd: can't cd to ..: No such file or directory
```

**Comment by ale5000-git** [comment]
For this I sugges to patch just `cd`:
- if the current directory start with `//` then give a special handling to `/`
- if the current directory start with `//` and it is the main folder (example: //computer_name/folder_name) then alter `..` to point to `.`

**Comment by rmyorston** [comment]
I've tweaked the Windows-specific code in the shell so it knows that root of a UNC path is ```//host/share```. Try [busybox_unc.exe](https://frippery.org/files/busybox/busybox_unc.exe).

**Comment by ale5000-git** [comment]
Unfortunately something go wrong:
```
C:\Users\DELL\Downloads>busybox_unc.exe ash
~/Downloads $ cd //nas326/pc
//nas326/pc $ cd /
ash: cd: can't cd to /: Bad file descriptor
//nas326/pc $ cd ..
ash: cd: can't cd to ..: No such file or directory
//nas326/pc $
```

**Comment by ale5000-git** [comment]
Also `cd letter:` without slash behave inconsistently:
```
C:/ $ cd z:
//NAS326/area-tecnica $ cd c:
C:/ $ cd z:/recycle
//NAS326/area-tecnica/recycle $ cd c:
ash: cd: can't cd to c:: No such file or directory
//NAS326/area-tecnica/recycle $

```

**Comment by rmyorston** [comment]
I'm unable to reproduce the UNC issues you report here or in #145.

The behaviour of ```cd c:``` is a different issue.

**Comment by ale5000-git** [comment]
Is it possible to have a debug version that show the content of all variabled inside "cd" execution phase?

**Comment by rmyorston** [comment]
Debug version: [busybox_unc2.exe](https://frippery.org/files/busybox/busybox_unc2.exe)

Diff: [busybox_unc2.diff](https://frippery.org/files/busybox/busybox_unc2.diff)

**Comment by ale5000-git** [comment]
I'm not sure why but busybox_unc2.exe works fine while busybox_unc.exe don't work.

Is it possible that there was an error in the compilation of busybox_unc.exe?

**Comment by rmyorston** [comment]
Yes, it looks as though busybox_unc.exe doesn't have the changes it was supposed to.

My bad. Sorry.

**Comment by ale5000-git** [comment]
Luckily it was only a missing change otherwise I wouldn't have know what to do.

**Comment by ale5000-git** [comment]
It now works correctly how you can see in #145, so all UNC issues should be fixed now.
