### ISSUE TITLE
`cd letter:` without slash behaves inconsistently

### ISSUE THREAD

**Issue by rmyorston** [rmyorston/busybox-w32#147]
Also `cd letter:` without slash behave inconsistently:
```
C:/ $ cd z:
//NAS326/area-tecnica $ cd c:
C:/ $ cd z:/recycle
//NAS326/area-tecnica/recycle $ cd c:
ash: cd: can't cd to c:: No such file or directory
//NAS326/area-tecnica/recycle $

```

_Originally posted by @ale5000-git in https://github.com/rmyorston/busybox-w32/issues/144#issuecomment-471626003_

**Comment by rmyorston** [comment]
Actually the behaviour isn't inconsistent; it's just not very intuitive or useful.

The Windows Command Prompt (and DOS before it) has features to support disk drives and directories that are rather different from *nix:

- It maintains a 'current directory' for *each* drive.
- The ```cd``` command can be used in different ways (all examples assume the current drive is ```c:```):
  - With a relative path to move within the current drive: ```cd Downloads```
  - With an absolute path to move within the current drive: ```cd \Users```
  - With a drive and absolute path to change the current directory of a different drive *without* switching to it: ```cd d:\sources```
  - With a drive alone to switch to the current directory of that drive: ```cd d:```.
  - If there isn't a path separator between the drive and the path, the path is interpreted relative to the current directory of the drive. Thus:
    - If the current directory of ```c:``` is ```\Users```, ```cd c:rmy``` moves you to ```c:\Users\rmy```.
    - If the current directory of ```d:``` is ```\sources```, ```cd d:vista``` changes the current directory of drive ```d:``` to ```d:\sources\vista``` but leaves you in the same directory as before.

Apologies if I got any of that wrong or omitted any important details.

Now, the original developer of busybox-w32 didn't want to maintain a record of the current directory of every drive. So instead of interpreting paths of the form ```d:path``` as relative to the current directory of *that* drive they used the current directory of the *current* drive.

It's easy to see that in most cases this is a useless thing to do. Almost every time it will result in the error ```ash: cd: can't cd to c:: No such file or directory```.

What to do about it? A number of options suggest themselves:
- Do nothing. Leave the current behaviour as it is.
- Track the current directory of each drive and implement the same behaviour as Command Prompt.
- Always treat a path of the form ```c:path``` as malformed and issue an error.
- Always treat a path of the form ```c:path``` as equivalent to ```c:/path```.

Any other ideas? Preferences?

**Comment by ale5000-git** [comment]
On cmd:
cd c: => Show current directory under c
cd /d c: => do nothing

In my opinion since this is totally different from *unix that has a different method of doing this and to avoid ambiguity I think it is better to treat as malformed and issue an error.

**Comment by rmyorston** [comment]
On further investigation I find:
- The special treatment of ```c:path``` isn't just a feature of the Command Prompt as I suggested above: it's baked into the API. Any call that can take a pathname supports it. This makes it much more difficult for busybox-w32 to impose its own interpretation of ```c:path```: there are too many affected API calls for it to be practicable to intercept them all. This seems to rule out options 3 and 4.
- The comment in ```updatepwd()``` said that tracking the current directory of all drives would be 'painful'. In fact, no special effort is needed. A call of the form ```GetFullPathName("z:", ...)``` returns the current directory of the ```z:``` drive. This makes option 2 seem less painful, though it would still take some work to provide full support for ```c:path```.

**Comment by ale5000-git** [comment]
@rmyorston: If you do it just make sure that Windows don't leave an open handle otherwise all "current directory" on all drives wouldn't be able to be deleted.

**Comment by rmyorston** [comment]
Support for ```c:path``` has been improved:

- ```cd``` treats such paths as relative to the current directory of the specified drive, not the current drive.
- ```pwd -a``` lists the current directory of all drives.
- Tab-completion works properly for ```c:path```.

There's a new prerelease binary: [busybox_pre.exe](https://frippery.org/files/busybox/prerelease/busybox_pre.exe).

**Comment by ale5000-git** [comment]
It is an improvement but it seems it doesn't work properly yet.

See:
```
~/Downloads $ cd z:
//cA/LaNtEsT $ pwd -a
C:/Users/Ale/Downloads
Z:/
//cA/LaNtEsT $ cd c:
~/Downloads $ cd z:/sss
//cA/LaNtEsT/sss $ pwd -a
C:/Users/Ale/Downloads
Z:/
//cA/LaNtEsT/sss $ pwd
z:/sss
//cA/LaNtEsT/sss $
```

1) It doesn't resolve symlinks even if it is already resolved in the current folder displayed
2) `pwd -a` folder doesn't match `pwd` folder for drive z
2) `pwd -a` case doesn't match `pwd` case

**Comment by rmyorston** [comment]
The first two items are a result of commit 585d17d26 which was intended to fix the handling of symbolic links in ```chdir(2)```. However, it used ```realpath(3)``` rather than ```readlink(2)``` so mapped drives were also affected. This is fixed in the current prerelease.

The third item is more complicated. There are three ways current directories can be displayed:
- The shell maintains its own record of the current directory. This is based on what the user types at the command line and so it can include path components which don't match the case stored on disk. This is what's displayed by ```pwd```.
- The line editing code, which displays the prompt, uses ```getcwd(3)```.
- ```pwd -a``` uses the WIN32 API call ```GetFullPathName("C:", ...)```.

As an additional complication, there's the case where ```cd``` is used to change to a directory which is the target of a symbolic link. The symbolic link retains the case of the target that was specified when it was created. This may not match how the name of the target is stored on disk.

Getting each of these different mechanisms to display path components with the 'correct' case is difficult. Canonicalising using ```realpath(3)``` works for physical drives but is unreliable for mapped drives. I think the only reliable approach is the one used in tab-completion where names are read from the directory.

On the whole, I don't think it's worth the effort.

**Comment by ale5000-git** [comment]
The latest fixes resolve all problems but since the "root path" of unc path (/pc_name/folder/) and local path (c:/) are always case insensitive (and uppercase for the most part, since windows, in many versions, also display pc names over the lan in uppercase form irrespective of the specificed case) what about always uppercase root pathes?

**Comment by rmyorston** [comment]
The latest prerelease has a 'best efforts' attempt to make path names consistent.
- Drive names and host names are made uppercase
- Paths are canonicalised using ```realpath(3)```

The latter seems to work for physical drives; it only partially works for mapped drives or symlinks.

**Comment by ale5000-git** [comment]
Sorry for the delay, I think that now it works perfectly.
Thanks.

**Comment by rmyorston** [comment]
Maybe not perfect, but it's certainly much better than it was.
