### ISSUE TITLE
Mapped lan drives issue

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#148]
A mapped lan drive it is like a symlink to a network folder, using `cd` it is resolved to the real path but it isn't resolved when ash is initialized.

Examples:
```
Z:\>busybox_unc2.exe ash
Z:/ $ cd z:/
docd called with z:/
updatepwd returns z:/
realpath 1 z:/
realpath 2 z:\
realpath 3 //cA/LaNtEsT
mingw_chdir called with z:/
calling chdir with //cA/LaNtEsT
//cA/LaNtEsT $
```

```
Z:\>busybox_unc2.exe su

realpath 1 C:\WINDOWS\system32
realpath 2 C:\WINDOWS\system32
realpath 3 C:/Windows/system32
realpath 1 Z:/
realpath 2 Z:\
mingw_chdir called with Z:/
C:/WINDOWS/system32 #
```

**Comment by rmyorston** [comment]
I added some more debug. ```resolve_symlinks()``` fails to open ```Z:\```. It seems that when running with elevated privileges the mapped drive isn't available.

I get a similar result if I run Command Prompt as Administrator:
```
C:\Windows\System32>z:
The system cannot find the drive specified.
```

**Comment by rmyorston** [comment]
As a solution to this particular issue, canonicalise the directory path in ```su``` *before* we change privileges.

New binary: [busybox_su8.exe](https://frippery.org/files/busybox/busybox_su8.exe)
Diff from current master: [busybox_su8.diff](https://frippery.org/files/busybox/busybox_su8.diff)

**Comment by ale5000-git** [comment]
Now it works correctly in su, but it would be nice to do it also in ash initialization to have:
```
Z:\>busybox ash
//cA/LaNtEsT $
```

instead of:
```
Z:\>busybox ash
Z:/ $
```

**Comment by rmyorston** [comment]
It isn't *necessary* to resolve the mapped drive. However, if the current directory is a symlink it should be resolved when the shell is started. Otherwise ```ls -l``` doesn't work properly, which was the reason for resolving symlinks in ```cd```.

New binary: [busybox_su9.exe](https://frippery.org/files/busybox/busybox_su9.exe)
Diff from current master: [busybox_su9.diff](https://frippery.org/files/busybox/busybox_su9.diff)

This has fixes for:
- running ```busybox su``` from Command Prompt when current directory is a mapped drive;
- running ```busybox sh``` from Command Prompt when current directory is a symlink;
- strip trailing space from path in ```realpath(3)```, an unrelated problem.

**Comment by ale5000-git** [comment]
Work perfectly now.

**Comment by rmyorston** [comment]
I've only committed the first and third fixes. I'm still thinking about ```cd``` and ```chdir(2)```.

Reopening until this is fully resolved.

**Comment by ale5000-git** [comment]
I don't care if symlink are resolved directly or not in general but currently they are resolved on `cd` but not on `ash` init so it is a bit inconsistent.

**Comment by rmyorston** [comment]
From the config file:
```
#
# Shells
#
CONFIG_SH_IS_ASH=y
# CONFIG_SH_IS_HUSH is not set
# CONFIG_SH_IS_NONE is not set
CONFIG_BASH_IS_ASH=y
# CONFIG_BASH_IS_HUSH is not set
# CONFIG_BASH_IS_NONE is not set
CONFIG_ASH=y
```
sh, ash and bash are all the same thing.

**Comment by rmyorston** [comment]
A somewhat better version of the second fix has been committed so this issue can be closed.
