### ISSUE TITLE
Drag and drop folders

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#149]
I type `cd ` , drag and drop a folder from explorer and press enter, it works correctly in cmd.exe but not in busybox since backslashes have a different meaning.

I think busybox should replace backslash with slash when drag and dropping a path (file or folder, local or network).

**Comment by rmyorston** [comment]
How would busybox-w32 know that the path has been dropped into it? It only sees key events. I think the drop is being handled by the console host.

Other things I found out:
- dropping from Explorer into a console with elevated privileges doesn't work;
- if the path name contains spaces it's automatically given quotes.

**Comment by ale5000-git** [comment]
Look at these:
http://www.cplusplus.com/forum/beginner/71994/
https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-dragqueryfilea

You can replace backslash with slash or escape backslashes.

PS: For console with elevated privileges not working it is a known limitation (same for cmd.exe).

**Comment by ale5000-git** [comment]
Regarding the elevated prompt, you can drag and drop only from elevated apps.

If you open notepad as admin (not using busybox), inside notepad select File => Open... and then drag a file from the open dialog to busybox ash elevated prompt it works correctly.
**Instead** if you open notepad using `busybox su -c "notepad &"` then it doesn't work, I'm not sure why.

**Comment by rmyorston** [comment]
> if you open notepad using busybox su -c "notepad &" then it doesn't work

Works for me. I'm not sure why.

busybox-w32 is a Console application, not a Windows application. It runs inside a Console Host, ```conhost.exe```, which is a Windows application. The Console Host handles drag and drop operations by sending key events to the Console application (which may be ```busybox.exe``` or ```cmd.exe``` or whatever). I don't know how the Console application can distinguish between key events arriving due to the user typing on the keyboard or the Console Host inserting then because of a drop operation.

As an alternative I've added a feature to the line editor so that that typing Ctrl-\ on the shell command line changes all backslashes to slashes.

Test binary: [busybox_slash.exe](https://frippery.org/files/busybox/busybox_slash.exe)
Diff from current git master: [busybox_slash.diff](https://frippery.org/files/busybox/busybox_slash.diff)

**Comment by ale5000-git** [comment]
This is a very usefull feature but if possible it would be nice to have both.

1) For drag and drop on console apps see [here](https://stackoverflow.com/a/21345390/490687).
> To use drag&drop on the console window itself, try using GetConsoleWindow() to get the console HWND, then ...

2) Ctrl-\ works on an English keyboard, on others it just use the key in the same place on the keyboard regardless of its meaning.

**Comment by rmyorston** [comment]
1. The key word there is 'try'. Reading the following comments it seems that even the person who made the suggestion was unable to get it to work. I don't plan on trying.
2. That's annoying! Crtl-\ is by far the best key combination to use: it has clear mnemonic value in this case and, in the *nix world, it sends SIGQUIT so people tend not to use it as an editing command.

Most of the other control characters already have defined meanings and many of them are used in the BusyBox line editing code. The next best option is probably Ctrl-Z. I know this has special meaning in the DOS world but that shouldn't be a problem here.

While looking into control characters I noticed some apparently unnecessary code in the busybox-w32 implementation of ``read_key()```. I've removed it, which wins back most of the bloat introduced by the new line editing feature.

New binary with these changes: [busybox_slash2.exe](https://frippery.org/files/busybox/busybox_slash2.exe)
Diff from current git master: [busybox_slash2.diff](https://frippery.org/files/busybox/busybox_slash2.diff)

**Comment by ale5000-git** [comment]
Italian keyboard = work
English keyboard = work
French keyboard => **break**

This make me think that all keyboard shortcuts are broken, it is just the some key letters match different keyboard so it goes mostly unnoticed but the base code need to be fixed.

Crtl-\ would be the best when the base code is fixed.

**Comment by ale5000-git** [comment]
@rmyorston: It works now but with the removed are you sure that Crtl-\ do not work?

**Comment by rmyorston** [comment]
The removed code was never being called when a control character was entered. The first thing I tried when I found it was to add handling of Ctrl-\, since I could see that it only worked for A-Z. But it made no difference.

**Comment by ale5000-git** [comment]
@rmyorston: The removed code is the one that caused the Euro issue.

- Set `chcp 1253`
- Paste Euro => now it works while previously it wasn't working.

But now you have to disable the hack to make it work again in chcp 858:
```
			if (buf[i] == 0x20ac) {
				d[i] = 0xd5;
			}
```

**Comment by rmyorston** [comment]
*Mea culpa.* The last binary had euro support disabled as an experiment.  Here's one with it enabled again (same diff as slash2): [busybox_slash3.exe](https://frippery.org/files/busybox/busybox_slash3.exe).

After putting up the wrong binary before I was especially careful with slash2 and checked that the md5sum of the one I'd tested matched that of the one I uploaded. Clearly that was insufficient. Sorry.

**Comment by ale5000-git** [comment]
In busybox_slash2.exe Euro WORKS on chcp 1253 but do NOT works on chcp 858
In busybox_slash3.exe Euro do NOT works on chcp 1253 but WORKS on chcp 858

Why?

**Comment by rmyorston** [comment]
>In busybox_slash2.exe Euro WORKS on chcp 1253 but do NOT works on chcp 858

- slash2 has euro support disabled so input characters are single-byte.
- Codepage 1253 includes the euro so it can be entered. Even Microsoft can't screw up the conversion from an OEM codepage with the euro at 0x80 to an ANSI codepage with the euro at the same place, so it works.
- Codepage 858 also includes the euro so the character is entered correctly but when it comes to be output it's corrupted by the buggy Microsoft conversion routines.

>In busybox_slash3.exe Euro do NOT works on chcp 1253 but WORKS on chcp 858
- slash3 has euro support enabled so input is read as wide characters. In both cases the euro is correctly read and converted to the correct OEM character.
- The code doesn't have a fix for the buggy Microsoft conversion routines for codepage 1253 so the euro is corrupted on output.
- It does have a fix for codepage 858 so it works.

The euro support feature in busybox-w32 only works when the Windows language setting is Western Europe. That's the one where people are most likely to need euro support. It could be extended to handle other settings if required.

>getc() => Oem to Wide => Wide to Ansi

On input there's only ever one conversion: Wide to Ansi when euro support is enabled and Oem to Ansi when it isn't.
