### ISSUE TITLE
Find the absolute path

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#154]
How can I find the absolute path of the shell script (from inside the shell script) in all conditions?
(possibly in a way that works also under Linux)

Examples:
```
C:/ $ folder/script.sh
$0 = folder/script.sh pwd = C:/
```

```
C:/ $ cd folder
C:/folder $ ./script.sh
$0 = ./script.sh pwd = C:/folder
```

```
C:/ $ cd folder
C:/folder $ ash ./script.sh
$0 = ./script.sh pwd = C:/folder
```

```
C:/ $ cd folder
C:/folder $ . ./script.sh
$0 = ash pwd = C:/folder
```

```
C:/ $ C:/folder/script.sh
$0 = C:/folder/script.sh pwd = C:/
```

```
C:/ $ ash C:/folder/script.sh
$0 = C:/folder/script.sh pwd = C:/
```

```
C:/ $ . C:/folder/script.sh
$0 = ash pwd = C:/
```

**Comment by rmyorston** [comment]
A web search for 'shell script absolute path' turns up many hits. Some of the solutions are bash-specific and won't work with BusyBox ash but there should be something that'll do what you want.

If there isn't *and it's a specific problem with busybox-w32 ash* I'll take a look.

**Comment by ale5000-git** [comment]
I have come up with this:
```
#!/usr/bin/env bash
LAST_COMMAND="$_"  # IMPORTANT: This must be the first line in the script after the shebang otherwise it will not work

temp="$(ps -o pid,comm | grep -Fw $$)"; for word in $temp; do CURRENT_SHELL=$word; done; unset temp; unset word
if test -n "$BASH_SOURCE"; then SCRIPT="${BASH_SOURCE[0]}"; elif test "$0" != "$CURRENT_SHELL"; then SCRIPT="$0"; elif test -n "$LAST_COMMAND"; then SCRIPT="$LAST_COMMAND"; else echo "Error"; fi
SCRIPT=$(realpath "$SCRIPT") || echo "Error"
SCRIPT_DIR=$(dirname "$SCRIPT")

echo "$CURRENT_SHELL"
echo "$SCRIPT"
echo "$SCRIPT_DIR"
```

It achieve a good compatibility but it is abit annoying to have to use ps and grep to find shell name.
Is there a "shortcut" in busybox to find shell name?

**Comment by rmyorston** [comment]
```ps``` is able to get the command name because every busybox-w32 process stores it internally and ```ps``` accesses the remote process's memory. Unfortunately there's no shortcut to allow the shell to access it's own record of the command name. Such information *could* be made available to the shell but there isn't a standard way to do this so it would have to be something non-portable.

How about using ```ps -o pid,args``` instead? For a shell script that gives both the shell and the script. In busybox-w32 the ```args``` string is limited to a maximum of 128 characters, though.

**Comment by ale5000-git** [comment]
I said it badly, I meant to ask if there was something like "ps -p $$ -o comm".

**Comment by rmyorston** [comment]
It's the kind of thing you might expect ```pgrep``` to do, but it can't match on process id.

```ps``` on my Linux system allows you to do:
```
ps --no-headers -o pid,comm $$
```
but ```ps``` in BusyBox doesn't support that. It looks like you're stuck with using ```grep```.

**Comment by ale5000-git** [comment]
Ok, thanks
