### ISSUE TITLE
Redirection bug

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#156]
Content of broken.sh:
`SCRIPT=$(realpath -broken) 2>&- || echo "Error"`

Now call it:
`busybox ash ./broken.sh`
you get:
`Error`

Instead inside Ubuntu (I'm using the one inside Windows):
`bash ./broken.sh`
you get:
```
realpath: invalid option -- 'b'
Try 'realpath --help' for more information.
Error
```

The redirection outside the $() doesn't take effect in Ubuntu (while inside it works perfectly) unlike in BusyBox.

**Comment by rmyorston** [comment]
busybox-w32 ```ash```, upstream BusyBox ```ash```,  ```dash```, ```zsh``` and ```ksh``` don't show the error from ```realpath```.

```bash``` and ```ksh``` show the error from ```realpath```.

Which is buggy and which correct? I don't know.

**Comment by ale5000-git** [comment]
Well, so this is one of the ambiguities in POSIX.
