### ISSUE TITLE
/var folder remapping

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#158]
Currently dpkg use `/var/lib/dpkg/` but `/var` point to whatever disk is selected (not always `C:/` and including lan folders).

I think it would be better to remap the `/var` folder globally to `${ALLUSERSPROFILE}` so it will become `C:/ProgramData/lib/dpkg/` that make more sense.

**Comment by rmyorston** [comment]
What do you mean by 'remapping'?

**Comment by ale5000-git** [comment]
A sort of global 'live' text replace like the \r removal but only for path.

**Comment by rmyorston** [comment]
I don't think 'live' replacement of the text ```/var/lib``` can be made to work. There are just too many places it would need to be done. And probably just as many where it *shouldn't* be done.

Modifying ```dpkg``` is probably the better option.

Of course there's also the problem of where to install files from .deb packages. They'll want to go to paths starting with '/'.

**Comment by ale5000-git** [comment]
Maybe `/localappdata/` and `/commonappdata/` can be set as reserved folder names and they can be used as virtual symlinks (by hacking the readlink code) to `${LOCALAPPDATA}` and `${ALLUSERSPROFILE}`.
So for user packages I suggest `/localappdata/deb/` and global packages `/commonappdata/deb/`

**Comment by rmyorston** [comment]
There are actually relatively few places where absolute paths are used in busybox-w32:
- ```ash``` uses ```/etc/profile```;
- ```rpm``` and ```dpkg``` install files to ```/``` (and ```dpkg``` has its data store in ```/var/lib```);
- ```man``` looks for config files in ```/etc``` and man pages in ```/usr/man```.

Rather than do anything more complicated I've arranged for these paths to be treated as being on ```%SYSTEMDRIVE%``` in Windows.

There's a prerelease binary including this feature: [busybox_pre.exe](https://frippery.org/files/busybox/prerelease/busybox_pre.exe)

**Comment by ale5000-git** [comment]
It is a nice way to fix it but for the dpkg case I still think it would be better $ALLUSERSPROFILE, it can be found by calling SHGetFolderPathA with csidl parameter as CSIDL_COMMON_APPDATA

For a Windows user, find a folder called "var" in C:\ isn't a good thing, tipically nothing (programs related) should be here.
It may look like a virus for a user not knowning its meaning.

**Comment by rmyorston** [comment]
I prefer the current arrangement, even for ```dpkg```.

- There are many references to ```/var``` in ```dpkg```, changing them all is quite intrusive.
- The sort of people who are likely to experiment with ```dpkg``` probably won't be too concerned.

**Comment by ale5000-git** [comment]
I plan to make some of my apps compatible with dpkg when I get some free time and after that the userbase will increase, but in effect the option to change the default dir for dpkg should be raised upstream.
