### ISSUE TITLE
Open a separate windows

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#159]
Using `start busybox ash` from a `.bat` file I can open a separate and async window retaining the same privilege level but it doesn't work inside `busybox ash`.

Is it possible to add an applet that do a similar thing?
Or is there already something that have a similar functionality?

**Comment by rmyorston** [comment]
Since ```start``` seems to be built into ```cmd.exe``` it's possible to run it from ```ash``` with:
```
cmd /c start busybox sh
```
Alternatively it would be simple to modify ```su``` to work without elevating privilege. The only thing would be deciding how to tell it to do that: there isn't a standard argument for that case. The closest would be ```su $USER``` but that's ugly.

**Comment by ale5000-git** [comment]
@rmyorston: With "retaining the same privilege level" I mean that running from limited prompt create a limited windows instead running from elevated prompt create an elevated window also "start" make available the environment variables in the new window.

Environment variables that are set inside busybox doesn't appear with `cmd /c start busybox sh`.

**Comment by rmyorston** [comment]
> Environment variables that are set inside busybox doesn't appear with cmd /c start busybox sh.

Works for me, both for global variables and local ones:
```
~ $ export VAR1=1
~ $ VAR2=2 cmd /c start busybox sh
```
In the new window both ```VAR1``` and ```VAR2``` are available. It also works when run from a shell with elevated privileges: the shell in the new window has elevated privileges and the environment variables are present.

I also made a modified ```su``` which (optionally) allows starting a new window without elevating privileges (so a normal user remains a normal user and a user with elevated privileges retains elevated privileges). Again, environment variables are copied across to the new shell.  (Recall that they aren't when ```su``` is used to elevate privileges. Must be a security thing.)

> it would also be nice to be able to use su to open shell as different user

Unfortunately ```ShellExecuteEx()``` doesn't provide a way to do that.

**Comment by ale5000-git** [comment]
According to [this article](https://textslashplain.com/2015/07/30/stupid-useful-windows-shell-tricks/) there ia an additional verb to do it.

**Comment by ale5000-git** [comment]
**PS:** `su $USER` seems to be the most correct by reading the su man page, but to be correct it should also degrade privileges when runnig it from an elevated prompt.

**Comment by ale5000-git** [comment]
Using `$COMSPEC /C start busybox sh` will result in: 
![start](https://user-images.githubusercontent.com/15793015/54739996-4c713a80-4bba-11e9-80b4-953bfa0bf385.png)

There are both slash and backslash.

**Comment by rmyorston** [comment]
I can't get RunAsUser to work. ```ShellExecuteEx()``` clearly recognises it because if I use some random string instead it complains. The internet says it may be necessary to have the Secondary Logon service running but enabling that didn't help. If some additional magic is required I haven't been able to find it.

The article you mention says:
>So, you’d expect that ShellExecute would’ve been updated to offer some sort of RunUnelevated verb that enabled an elevated application to run a target application without elevation. Sadly, it doesn’t; the Windows team considered this a really hard problem (the corner cases are ugly) so they punted on solving it.

Downgrading privileges doesn't seem to be an option.

If it isn't possible to extend ```su``` in a way that's somewhat consistent with how it behaves on *nix I'd rather leave it as it is. Using ```cmd /c start busybox sh``` meets your original requirement.
> There are both slash and backslash.

```cmd``` is using ```PATH``` from the shell, which has forward slashes, and is appending the backslash and command name to form a path to the binary. I don't think it's worth trying to fix this.

**Comment by ale5000-git** [comment]
I'm not sure but maybe it need ShellExecute instead of ShellExecuteEx.

RunAsUser is cited here: https://devblogs.microsoft.com/scripting/use-powershell-to-work-with-windows-explorer/
