### ISSUE TITLE
MSVC++ Runtime Error with bb and openssl

### ISSUE THREAD

**Issue by QueuingKoala** [rmyorston/busybox-w32#16]
I have encountered a rather strange issue with a busybox-w32 running on Windows XP when attempting to run the openssl.exe program from the installer provided on their binary distribution page here: https://www.openssl.org/related/binaries.html .

This issue is not present on my busybox-w32 build repeating the same steps on my Vista box: only XP. I have built busybox-w32 from git commit 3fd3465 in a fairly simple setup, and am happy to paste my .config if it will help (for reference, the current rmyorston-supplied binaries from http://intgat.tigress.co.uk/rmy/busybox/index.html break in the same way.) My compile environment is mingw on an Ubuntu-server 13.04 64-bit using i686-w64-mingw32-gcc as my compiler. Since it's not listed, I have no clue how the upstream binaries are built; both exhibit the same symptoms.

Note that I can run openssl.exe from a cmd.exe prompt fine, as it does from Cygwin's bash shell. Under Windows XP specifically, busybox-w32 appears to work fine except when I call that same openssl.exe from the above installation. For reference, an openssl executable from the OpenVPN installer (build using the mingw cross-compiler instead of MSVC++) works fine when called from busybox-w32.

When reproducing the issue, the following error is shown in a graphical message box:
Microsoft Visual C++ Runtime Library
Runtime Error!
Program: D:\Apps\OpenSSL-Win32\bin\openssl.exe
R6034
An application has made an attempt to load the C runtime library incorrectly. Please contact the application's support team for more information.

While the MSVC++RT error message is apparently coming from openssl, there has to be something busybox is doing to cause it since this application works fine everywhere else I can think to run it from, including a variety of cygwin shells.

Reproduction steps:

1. Need to be using Windows XP.
2. Build busybox
3. Install the "OpenSSL Lite" (I'm using 1.0.1e, latest version)
4. OpenSSL Lite will require the Visual C++ 2008 Redistributable linked from their page if not already present.
5. Open a Windows command prompt & start bb: busybox.exe sh
6. Call the openssl program: D:/InstallPath/OpenSSL-Win32/bin/openssl.exe version

The expected result is of course the version from openssl, not the MSVC++ runtime error.

Let me know if any further info is useful for debugging.

**Comment by rmyorston** [comment]
This issue may be related to the problem in issue #39, where forward slashes in environment variables caused a native Windows application to fail to run.

**Comment by rmyorston** [comment]
The shell in busybox-w32 now supports the -X option (which must be the first).  This prevents backslashes from being converted to slashes in the environment, which should fix this issue.
