### ISSUE TITLE
ts applet

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#160]
Please enable `ts` at the next sync with upstream.

**Comment by rmyorston** [comment]
It isn't necessary to raise an issue for this: I check new applets from upstream as a matter of course.

**Comment by ale5000-git** [comment]
Thanks.

**Comment by rmyorston** [comment]
I wanted to pull in some other stuff from upstream so the prerelease binary now includes ```ts```.

**Comment by ale5000-git** [comment]
Thanks.
