### ISSUE TITLE
erase scrollback escape sequence is not working properly

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#161]
`clear` should behave like: `echo -e "\33[3J\33[H\33[2J"` ([erase scrollback] [reset cursor position] [erase screen])

Now [reset cursor position] and [erase screen] seems to be working properly but [erase scrollback] is totally ignored.

**Comment by rmyorston** [comment]
The [man page](http://man7.org/linux/man-pages/man1/CLEAR.1.html) for ```clear``` goes into great detail about the history of erasing the scrollback buffer.

A lot of that history happened after ```clear``` was implemented in BusyBox, so upstream still uses ```\033[H\033[J```. I see no particular reason to change that.

**Comment by ale5000-git** [comment]
Apart from clear thing, it would be nice to have the escape sequence working.

**Comment by rmyorston** [comment]
There's an internal function, ```reset_screen()``` which essentially implements the erase scrollback feature. It wasn't hooked up to an escape sequence as it was more efficient to call it directly when required. It has now been exposed as part of the functionality of the ```reset``` applet which is a more thorough version of ```clear```.

I've also implemented the ```\033[?1049h``` and ```\033[?1049l``` escape sequences to switch between the normal and alternate screen buffers. These are used by ```vi``` and ```less``` to restore the original contents of the screen on exit.

There's a prerelease binary with these new features.

**Comment by ale5000-git** [comment]
`reset` works perfectly thanks.

**Comment by Peter0x44** [comment]
Honestly, I find it kind of obnoxious that it differs from coreutils and every other implementation. My hack to work around this is:
`alias clear="cmd /c cls"`

**Comment by Peter0x44** [comment]
Or I guess, probably better to use the `reset` mentioned here...
`alias clear="reset"`

edit: nvm this doesn't work

**Comment by rmyorston** [comment]
The `reset` applet hasn't kept pace with Microsoft's changes to their Terminal and Console programs.

Please try the latest prerelease binaries, available in the [usual place](https://frippery.org/files/busybox/prerelease) (PRE-6079 or later).
