### ISSUE TITLE
Virtual tmpfs

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#165]
If possible it would be nice to have a virtual ramdrive, something like `/tmp` mounted to `tmpfs`, all files copied or created into to it should be only in RAM and lost when one exit from busybox.

I need it since I would like to simulate on a PC an Ota zip installation (that is usualy done inside an Android recovery using busybox for Android) and I make a large use of /tmp.

**Comment by rmyorston** [comment]
I think this is well beyond the scope of busybox-w32.

Something like the [ImDisk Virtual Disk Driver](http://www.ltr-data.se/opencode.html/) or an equivalent would probably be a better option.

**Comment by ale5000-git** [comment]
What I need is a portable version (so no install) that doesn't require admin rights (so no drives) but is is probably too complex to include it in busybox.
Thanks however.
