### ISSUE TITLE
Define _FILE_OFFSET_BITS 64 for 32-bit builds to avoid ''Value too large for defined data type''

### ISSUE THREAD

**Issue by ilg-ul** [rmyorston/busybox-w32#167]
I encountered a problem while building on an old 32-bit machine, the `script/basic/fixdep` and `script/basic/split-include` were not functional, they failed with ''Value too large for defined data type''.

It seems to be a known problem:

https://stackoverflow.com/questions/13893580/calling-stat-from-sys-stat-h-faills-with-value-too-large-for-defined-data-typ/13893581

Actually it affects not only `stat()`, but other system functions too, like `mmap()`.

As suggested there, I patched the `fixdep.c` and `split-include .c` files to add `#define _FILE_OFFSET_BITS 64` before the first `#include`.

This fixed my builds, but perhaps you can find a proper solution for this problem.

**Comment by rmyorston** [comment]
I'm unable to reproduce this on a 32-bit CentOS 6 system.

What platform and compiler are you using?

**Comment by ilg-ul** [comment]
hmm... exactly a 32-bit CentOS 6 system... with the very old gcc that comes with the system.

I first get errors during `make mingw32_defconfig`, which compiles the two utilities, but the build continues.

later, during `make` I get new errors and the build fails.

**Comment by rmyorston** [comment]
Could you put some debug in ```fixdep.c``` and ```split-include.c``` to find out why they're failing?

**Comment by ilg-ul** [comment]
I did, in `fixdep.c` the first `mmap()` returns -1; in `split-include.c` the first `stat()` returns -1 and 'Value too large for defined data type'.

My CentOS is actually a Docker image, running on macOS.

**Comment by rmyorston** [comment]
My CentOS is a virtual machine.

The first call to ```stat()``` in ```split-include.c``` is for the file ```include/autoconf.h``` which is 187,029 bytes in my build. That is certainly not too large.

What does the command ```stat include/autoconf.h``` do on your system? I get:
```
$ stat include/autoconf.h 
  File: `include/autoconf.h'
  Size: 187029    	Blocks: 368        IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 149211      Links: 1
Access: (0664/-rw-rw-r--)  Uid: (  500/     rmy)   Gid: (  500/     rmy)
Access: 2019-04-07 19:56:48.749999981 +0100
Modify: 2019-04-07 19:56:27.410999983 +0100
Change: 2019-04-07 19:56:27.410999983 +0100
```

**Comment by ilg-ul** [comment]
probably when a 32-bit docker container runs inside a 64-bit virtual machine things are a bit different and the `_FILE_OFFSET_BITS=64` definition is the cure.

**Comment by ilg-ul** [comment]
could you check what happens if you add `-D_FILE_OFFSET_BITS=64` to the build when running on your CentOS 32-bit machine?

if it does not hurt, and fixes cases like when running a 32-bit container inside a 64-bit vm, you have a better solution than my patch which adds the #define inside the files, before the first #include.

**Comment by rmyorston** [comment]
Adding ```-D_FILE_OFFSET_BITS=64``` to the host build flags works on my 32-bit CentOS. (Note that the default busybox-w32 configuration has ``CONFIG_LFS=y``` so the target build already has support for large files.)

Setting the host build flags can be done with an environment variable:
```
export HOST_EXTRACFLAGS="-D_FILE_OFFSET_BITS=64"
```
Does that work for you in your CentOS container?

**Comment by ilg-ul** [comment]
Yes, this finally worked but I noticed that the `script/basic` tools are built twice, the first time correctly, with the definition added, when I run `make mingw32_defconfig`, and the second time incorrectly, without the definition, when I run `make`:

```
Running BusyBox configure...
make -f scripts/Makefile.build obj=scripts/basic
  gcc -Wp,-MD,scripts/basic/.fixdep.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer   -D_FILE_OFFSET_BITS=64    -o scripts/basic/fixdep scripts/basic/fixdep.c  
  gcc -Wp,-MD,scripts/basic/.split-include.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer   -D_FILE_OFFSET_BITS=64    -o scripts/basic/split-include scripts/basic/split-include.c  
  gcc -Wp,-MD,scripts/basic/.docproc.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer   -D_FILE_OFFSET_BITS=64    -o scripts/basic/docproc scripts/basic/docproc.c  
/Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1/scripts/gen_build_files.sh /Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1 /Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1
  GEN     include/applets.h
  GEN     include/usage.h
  GEN     mailutils/Kbuild
  GEN     mailutils/Config.in
...

Running BusyBox make...
rm -f .kernelrelease
echo 1.31.0.git > .kernelrelease
/Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1/scripts/gen_build_files.sh /Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1 /Host/Users/ilg/Work/build-tools-2.12/win32-x32/build/busybox-w32-65ae5b24cc08f898e81b36421b616fc7fc25d2b1
make -f scripts/Makefile.build obj=scripts/basic
  gcc -Wp,-MD,scripts/basic/.fixdep.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer       -o scripts/basic/fixdep scripts/basic/fixdep.c  
fixdep: mmap: Cannot allocate memory
  gcc -Wp,-MD,scripts/basic/.split-include.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer       -o scripts/basic/split-include scripts/basic/split-include.c  
  gcc -Wp,-MD,scripts/basic/.docproc.d  -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer       -o scripts/basic/docproc scripts/basic/docproc.c  
fixdep: mmap: Cannot allocate memory
fixdep: mmap: Cannot allocate memory
  scripts/basic/split-include include/autoconf.h include/config
scripts/basic/split-include: include/autoconf.h: Value too large for defined data type
make: *** [Makefile:861: include/config/MARKER] Error 1
ilg-mbp:~ ilg$ 
```

For various reasons, in my build scripts the two make commands run in different subshells, and the export added to the first make does not reach the second one.

Adding it explicitly for the second make fixed the problem. Since I noticed that the second make builds some more host tools, I think it is safer to have the definition there too. 

So, from my point of view, this issue can be closed.

It would be helpful to add a paragraph to the documentation, explaining this solution, and possibly enumerating the other environment variables relevant for the build.

Thank you,

Liviu

**Comment by rmyorston** [comment]
OK, I'm pleased you have a solution.

Currently the build process is only mentioned briefly in the README.md. Ideally there should probably be a separate page on my website to cover it in more detail. Until then at least this issue might help someone.

**Comment by ilg-ul** [comment]
For completeness, the binaries built from your sources are available from

https://github.com/gnu-mcu-eclipse/windows-build-tools/releases
