### ISSUE TITLE
Script performance profiling

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#168]
Hi,
if possible it would be nice to have [this change](https://github.com/git-for-windows/busybox-w32/commit/09ddaba5df1ee947ed6be28fc23b6ed685b90516) to detect bottlenecks in scripts.

**Comment by rmyorston** [comment]
There are problems with the proposed change:
- it's non-standard;
- it only affects the prompt;
- it's WIN32-specific.

Instead I suggest implementing the ```EPOCHSECONDS``` and ```EPOCHREALTIME``` environment variables that were recently added to bash. A patch for this has been accepted by upstream BusyBox.

Try the latest [prerelease](https://frippery.org/files/busybox/prerelease/busybox_pre.exe).

**Comment by ale5000-git** [comment]
Thanks, this is nice but I'm not able to replicate the behaviour of \P.

I have tried:
```
PROMPT_COMMAND='LASTEPOCHSECONDS="$EPOCHSECONDS"'
PS1='$(expr $EPOCHSECONDS - $LASTEPOCHSECONDS) \$'
```

But PROMPT_COMMAND do not work on busybox and inside PS1 variable cannot be set (because they are in a subshell).

**Comment by ale5000-git** [comment]
**PS:** I'm not sure if it is intended but this `PS1='$(expr $EPOCHSECONDS - $LASTEPOCHSECONDS) \$ `eval(LASTEPOCHSECONDS="$EPOCHSECONDS")`'` cause the termination of the shell.

**Comment by rmyorston** [comment]
>inside PS1 the variables cannot be set

Something like this might do what you want:
```
PS1='$((delta=EPOCHSECONDS-${last:-0},last=$EPOCHSECONDS,delta)) \$ '
```
It uses arithmetic expansion and avoids creating subshells and new processes. The expression uses the comma operator to perform three subexpressions:
- the first calculates the elapsed time and assigns it to a variable. ```${last:-0}``` ensures that ```last``` has a value on the first call;
- the second updates the value of ```last```;
- the third outputs the elapsed time.

It might be better just to record the absolute time values and calculate the differences in a separate process later.

>I'm not sure if it is intended

Certainly not intended. Both upstream BusyBox and dash have trouble handling invalid code in ```PS1```.  I'm looking into it.

**Comment by rmyorston** [comment]
Fixes for issues with ```PS1``` have been applied upstream. Try the current prerelease.

**Comment by ale5000-git** [comment]
Sorry to be late.
It works perfectly now, thanks.
