### ISSUE TITLE
Inconsistent sh startup hidden option?

### ISSUE THREAD

**Issue by d-faure** [rmyorston/busybox-w32#171]
Cf. https://github.com/rmyorston/busybox-w32/blob/01950ee1937fdb5172673afad5b65bdb48fe89de/shell/ash.c#L15124-L15161

If the -d hidden option is very convenient to setup the initial running directory before execution of some shell script, I would find nice to have it taken in account while running login shell, enabling coherent portable environment setups, such as:
```
.../some_dir/
     +- busybox.exe
     +- /etc/profile
     +- /home/...
```
ie. looking relatively to itself for initialization scripts instead of being bound to the root of the system drive.

**Comment by rmyorston** [comment]
I'm not clear what you're asking for here.  Do you want the scripts to be relative to the location of the executable or the initial directory?

**Comment by d-faure** [comment]
You're right, this wasn't clear enough. I'd simply would like that, when both the ```-d <dir>``` and the ```-l``` options are used on the command line, that the startup script location (ie. ```/etc/profile```) is relative to the specified directory (resulting to ```<dir>/etc/profile```), and, if this directory specification itself is relative (not starting with a drive letter and/or a root directory), it would be interpreted relatively to the executable location.

running:
```.../somedir/busybox.exe sh -d root -l```
would make the shell look for:
```.../somedir/root/etc/profile```
startup script

**Comment by rmyorston** [comment]
The ```-d``` option is non-standard and undocumented. It was added to resolve problems with the ```su``` applet and I'd rather people didn't rely on it:  no other Bourne-style shell supports it.

I'm unwilling to add more features that require the presence of ```-d```.

**Comment by d-faure** [comment]
For the record, I could manage to get the expected "portable" installation using the following command line:
```"...\somedir\busybox.exe" -d ".../somedir/root" -s -i -c ". etc/profile"```
and the following `etc/profile` content:
```
# -*- /etc/profile --- mode: shell-script -*-
#
export BB_ROOT="$PWD"
[ -f "$BB_ROOT/home/.profile" ] && . "$BB_ROOT/home/.profile"
[ -z "$ENV" ] && export ENV="$BB_ROOT/etc/ashrc" && . "$ENV"
```
