### ISSUE TITLE
Command-line switch to enable wildcards?

### ISSUE THREAD

**Issue by lunakid** [rmyorston/busybox-w32#172]
Would it be possible to turn on Windows-facing (non-sh) globbing via a command-line switch? It (perhaps a `--disable-globbing` flag *only in the globbing-enabled* version) would be so much better than having two flavors of the executable around.

(Or is it too late then, altering the processing of the cmdline by a cmdline option?)

For some rationale (if needed):

A use case here (presumably not a rarity, just one example from this whole class of simple on-the-fly command invocations from Windows) was replacing old CMD commands in `$(COPY)`, `$(DEL)`, `$(MKDIR)`, `$(RMDIR)` etc. macros in a makefile.

Most could be done by the simple `CHORE = busybox command switches` prefix scheme (then used like `$(CHORE) $(FS_OBJ)` transparently the same way as without Busybox), but not those requiring wildcards in `FS_OBJ` (e.g. for cleaning, archiving, deployment, etc.). 

The lack of globbing at the front end implied an `sh` wrapping, and that, in turn, combined with the required quoting of args like `busybox sh -c "cp $(LIB_HEADERS) $(RELEASEDIR_INCLUDE)" forced unwelcome changes in the makefile (incl. some hardcoding for the time being).

I may be doing things suboptimally, but regardless, the option of switching globbing on/off on the `busybox` command line may still be valid.

Thanks! _(I love your busybox version, BTW.)_

----
_Related: the old #9 about wildcards in non-shell mode, and the less relevant #35 (globbing in "which?" shell mode)._

**Comment by lunakid** [comment]
OK, sorry, I think I get it now: globbing is done clib itself, so the globbing and non-globbing version of those (which, BTW?) calls can't live together in the same .exe. Is that correct?

**Comment by rmyorston** [comment]
Yes, it would be nice to avoid the need for different executables.  However, globbing happens before ```main()``` is called so it can't be affected by a command-line switch that's interpreted by ```main()```.

The setting is controlled by a global variable: ```_CRT_glob``` in the case of MinGW and ```_dowildcard``` in MinGW-w64.

**Comment by ale5000-git** [comment]
@rmyorston: I think it is possible to completely ignore the parsed command line, get the [raw command line](https://stackoverflow.com/questions/14150374/how-to-get-the-raw-command-line-arguments) and then parse it manually in your code (maybe by creating an helper function to do it).

PS: you could also reuse [CommandLineToArgvW](https://github.com/wine-mirror/wine/blob/6d801377055911d914226a3c6af8d8637a63fa13/dlls/shell32/shell32_main.c) form Wine.
