### ISSUE TITLE
no proper serializing between find and exec results.

### ISSUE THREAD

**Issue by hussamT** [rmyorston/busybox-w32#173]
I am seeing a lot of this:
find . -type d -name ".vs" -exec rm -rfv "{}" \;
removed './cpp/QtConsoleApplication/.vs/QtConsoleApplication/v15/.suo'
removed directory: './cpp/QtConsoleApplication/.vs/QtConsoleApplication/v15'
removed directory: './cpp/QtConsoleApplication/.vs/QtConsoleApplication'
removed directory: './cpp/QtConsoleApplication/.vs'
find: ./cpp/QtConsoleApplication/.vs: No such file or directory
removed './csharp/Proj1/.vs/Proj1/v15/.suo'
removed './csharp/Proj1/.vs/Proj1/v15/Server/sqlite3/db.lock'
removed './csharp/Proj1/.vs/Proj1/v15/Server/sqlite3/storage.ide'
removed './csharp/Proj1/.vs/Proj1/v15/Server/sqlite3/storage.ide-shm'
removed './csharp/Proj1/.vs/Proj1/v15/Server/sqlite3/storage.ide-wal'
removed directory: './csharp/Proj1/.vs/Proj1/v15/Server/sqlite3'
removed directory: './csharp/Proj1/.vs/Proj1/v15/Server'
removed directory: './csharp/Proj1/.vs/Proj1/v15'
removed directory: './csharp/Proj1/.vs/Proj1'
removed directory: './csharp/Proj1/.vs'
find: ./csharp/Proj1/.vs: No such file or directory

**Comment by rmyorston** [comment]
Both upstream BusyBox and GNU ```find``` exhibit the same behaviour.

Using ```-exec ... +``` rather than ```-exec ... ;``` avoids the warning and is probably more efficient.

**Comment by hussamT** [comment]
Thank you very much.
I was used to ...; from a decade and a half of using ArchLinux.

**Comment by hussamT** [comment]
Can you please tell me though what the difference is though for my reference?

**Comment by rmyorston** [comment]
```-exec ... ;``` executes a separate command for each matching file. When the file is a directory ```find``` performs a check that it exists after the actions have been executed, which is where the warning comes from.

```-exec ... +``` builds a command line by appending each matching file to the command provided and executes it when ```find``` has finished its search.

**Comment by hussamT** [comment]
Thank you very much.
