### ISSUE TITLE
ADD #177: Color not reset after command ls

### ISSUE THREAD

**Issue by Klexer** [rmyorston/busybox-w32#178]
Unfortunately there is a new bug now: The color is not reset after the command **`ls`**. The dircolor of the last file type of **`ls`** remains as standard color at the end.

_Originally posted by @Klexer in https://github.com/rmyorston/busybox-w32/issues/177#issuecomment-571316249_

**Comment by rmyorston** [comment]
Should be fixed now. There's a new prerelease binary in [the usual place](https://frippery.org/files/busybox/prerelease).

**Comment by Klexer** [comment]
Thanks.
