### ISSUE TITLE
busybox show error "applet not found" when i call it by a relative path

### ISSUE THREAD

**Issue by ejzhang** [rmyorston/busybox-w32#180]
It's ok by a absolute path.
![busybox](https://user-images.githubusercontent.com/452491/76930347-3c9d4b00-6921-11ea-9660-f2c593cdc7df.png)

**Comment by rmyorston** [comment]
Indeed, the handling of paths to executables, like 'c:busybox', was incorrect. It also affected the shell. Fixed in git.

There's a new pre-release binary in [the usual place](https://frippery.org/files/busybox/prerelease).

**Comment by ejzhang** [comment]
thanks for your job!
