### ISSUE TITLE
Windows dd with seek option cannot generate sparse file

### ISSUE THREAD

**Issue by HuangShumin** [rmyorston/busybox-w32#181]
This behavior is different from Linux dd.
For example,
dd if=/dev/urandom of=sparse.file bs=1 count=1 seek=10240

du -k sparse.file

Linux shows 4K
Windows shows 1028K

**Comment by rmyorston** [comment]
There are actually two issues here:

1. On Linux the use of seek to create a hole in a file will automatically result in a sparse file (if the filesystem supports it). On Windows the file has to be marked as being sparse and the hole has to be created specially, just seeking is not enough.

2. The implementation of ```stat(2)``` for busybox-w32 approximates the size in blocks from the reported file size. This is incorrect for sparse files.

I think I have solutions to both of these. Watch this space...

**Comment by rmyorston** [comment]
The latest pre-release binary [on my website](https://frippery.org/files/busybox/prerelease) should fix this. When ```dd``` is run with the ```seek=N``` option it creates a sparse file (on filesystems that support it). Also, any utilities that use ```stat(2)``` to report file sizes in blocks now report the correct size for sparse files.

With these changes:

```
~ $ dd if=/dev/urandom of=sparse.file bs=1k count=1 seek=2048
1+0 records in
1+0 records out
~ $ ls -ls sparse.file
    64 -rw-rw-r--    1 rmy      rmy        2098176 Mar 24 16:51 sparse.file
~ $ dd if=/dev/urandom of=sparse.file bs=1k count=0 seek=2048
0+0 records in
0+0 records out
~ $ ls -ls sparse.file
     0 -rw-rw-r--    1 rmy      rmy        2097152 Mar 24 16:51 sparse.file
~ $ fsutil sparse queryflag sparse.file
This file is set as sparse
~ $
```

**Comment by HuangShumin** [comment]
Much appreciated for your work!

This issue is perfectly solved in short time frame, and it can be closed.
