### ISSUE TITLE
Consider if miscutils/time.c could be enabled by default?

### ISSUE THREAD

**Issue by HuangShumin** [rmyorston/busybox-w32#182]
time ultility is useful to evaluate command efficiency of different implementation.

**Comment by rmyorston** [comment]
I've ported ```time``` to WIN32. Only elapsed, user and system times are supported, not the other statistics reported by GNU ```time```.

There's a new pre-release binary with ```time``` enabled.

**Comment by HuangShumin** [comment]
Good works!

**Comment by HuangShumin** [comment]
I've tested this time ultility, it works without issue found. I will close this request issue now.
