### ISSUE TITLE
Is it possible to port inotifyd in windows?

### ISSUE THREAD

**Issue by fitu996** [rmyorston/busybox-w32#184]
It is a very useful tool when creating scripts that watch file changes and do something.

In Linux it will use inotify which not present on windows. A similar API in windows is [this](https://docs.microsoft.com/en-us/windows/win32/fileio/obtaining-directory-change-notifications?redirectedfrom=MSDN). So I wonder if it can be ported to busybox-w32.

**Comment by rmyorston** [comment]
I've implemented ```inotifyd``` in busybox-w2.  There are limitations:

- It's only possible to watch directories, not individual files.
- The notification doesn't distinguish between different changes to file state.  All changes other than creation, deletion and renaming are reported as 'c'.  It might be possible to fix this by setting up a separate watch for each type of change but that seems like a lot of work for little gain.
- I note that if I use ```rm -rf``` to delete the directory being watched only one file deletion is reported, even if there are lots of files in the directory.

There's a new pre-release binary with ```inotifyd``` enabled [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by fitu996** [comment]
Thank you for your work. I think these limitations are acceptable if pointed out as known issues. Is there any plan that makes stable release?

**Comment by rmyorston** [comment]
There was a new release just a week ago. I prefer to have a few weeks between releases.

**Comment by fitu996** [comment]
Do you have any plan fixing the issue mentioned in the second post? If not, I will close this issue after the next release.

**Comment by rmyorston** [comment]
I think the current implementation is a reasonable compromise between functionality and complexity. If anyone has any strong feelings about the need for particular features or suggestions for improvements I'd be happy to consider them. Otherwise I'm satisfied with the current version.

**Comment by rmyorston** [comment]
The new binary release (FRP-3466-g53c09d0e1) has ```inotifyd```.
