### ISSUE TITLE
Side effect of sparse file support in dd

### ISSUE THREAD

**Issue by yindian** [rmyorston/busybox-w32#186]
Commit e6680912a for #181 adds support for sparse file creation using dd seek=N. However, in cases where dd seek=N is used to modify an existing file, the data before the seek position are zeroed in seek_sparse(). That differs with the behavior under Linux, and breaks some scripts I am using.

When used without conv=notrunc, dd seek=N calls ftruncate() before seek_sparse(), where _chsize() is invoked as defined in ftruncate.c in mingw-w64. According to MSDN and CRT source, _chsize() would extend the file using lseek & write, or shrink it using SetEndOfFile. Therefore in the former case, non-sparse file with expected size seems to have already been created before calling seek_sparse(), which is not nice as possible slow writing & large disk usage might still happen during the operation.

IMHO it would be more feasible to rewrite ftruncate() to set sparse and zero data on extending, and for the conv=notrunc case, perform similar operations to extend the file, without shrinking.

**Comment by rmyorston** [comment]
I'd prefer not to touch ```ftruncate()```. It's used elsewhere in BusyBox in places where the need for sparse files is less important than in ```dd```.

Instead I've rewritten the function that creates the sparse region and moved it to before the call to ```ftruncate()```. This should fix the issue with ```conv=notrunc``` and also ensures that the file is created sparse.

If anyone would like to try this there's a new pre-release binary [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by yindian** [comment]
I have tested the new binary and confirmed that the issue has been fixed. The code change also looks good. Thanks for your support!
