### ISSUE TITLE
Enable regular expressions in vi?

### ISSUE THREAD

**Issue by kkwoo** [rmyorston/busybox-w32#188]
Hi Ron,

Thanks for compiling busybox to w32 and w64. They've been very good to me. I searched through the issues and failed to find if anyone asked to enable regular expressions in vi. Are you open to the suggestion of enabling regular expressions in the busybox w32 and w64 vi?

Regards,

Kevin

**Comment by HuangShumin** [comment]
try CONFIG_FEATURE_VI_REGEX_SEARCH=y

**Comment by rmyorston** [comment]
Sure, I've added the setting to the default configuration.

There's a new pre-release binary (32-bit only) [on my website](https://frippery.org/files/busybox/prerelease). I have a vague plan to make a new release in the next week or so.

**Comment by kkwoo** [comment]
Hi Ron,

    Thank you for the super-fast response! The pre-release binary works great. Looking forward to the next release whenever it comes.

Regards,

Kevin

**Comment by kkwoo** [comment]
Hi HuangShumin,

I saw the CONFIG_FEATURE_VI_REGEX_SEARCH as well. I work and personal circumstances make self-compilation unfeasible. Thanks for your help!

Regards,

Kevin

**Comment by kkwoo** [comment]
Hi Ron,

    I'll check back every fortnight and close this issue once the release has come. I'll continue using the pre-release for now. Thanks again for your help!

Regards,

Kevin

**Comment by rmyorston** [comment]
I've made a new binary release (FRP-3466-g53c09d0e1) which includes this enhancement.

**Comment by kkwoo** [comment]
Hi Ron,

Thanks very much for the new release, I appreciate it very much. I will close this issue now.

Regards,

Kevin
