### ISSUE TITLE
echo is colored, but not printf

### ISSUE THREAD

**Issue by ko1nksm** [rmyorston/busybox-w32#189]
`printf` is not colord.

```sh
$ printf '\033[31m%s\033[0m\n' abc
[31mabc[0m
```

but `echo` is colord.

```sh
$ echo $(printf '\033[31m%s\033[0m\n' abc)
abc # red
```

Is this a limitation?

**Comment by rmyorston** [comment]
It's a known problem.  ```printf``` outputs characters from the format string one at a time, but the code in busybox-w32 to process escape sequences needs to see the whole sequence at once.

It's reasonable to expect that escape sequences should work in ```printf```.  I'll see what I can do.

**Comment by rmyorston** [comment]
OK, this isn't a full solution but ```printf``` now outputs escape sequences in a way that busybox-w32 understands in two cases:

- literal text in the format string
- string arguments printed with the ```%b``` format specifier

These now work:
```sh
$ printf '\033[31m%s\033[0m\n' hello
hello # red
```

```sh
$ RED='\033[31m'
$ RESET='\033[0m'
$ printf '%b%s%b\n' "$RED" hello "$RESET"
hello # red
```

A pre-release binary with this change (```busybox_pre.exe```) is available [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by ko1nksm** [comment]
Thanks for quick fix! It looks good to me.

I think this is a case that hasn't been solved yet.

```sh
printf '\033'; printf '[31m%s\033[m\n' abc
```

However, This fix solve most use cases. I appreciate it!

**Comment by rmyorston** [comment]
Sorry, the commit has nothing to do with this issue.
