### ISSUE TITLE
`type` and `command -v` are inconsistent with `which` regarding trailing slash in `$PATH`

### ISSUE THREAD

**Issue by imgx64** [rmyorston/busybox-w32#191]
If a path in `$PATH` ends with a slash, `which` correctly prints executables' paths with only a single slash. However, `type` and `command -v` print double slashes.

To reproduce:
```
> busybox sh
~ $ echo "$PATH" | tr ';' $'\n' | grep 'PowerShell'
C:/WINDOWS/System32/WindowsPowerShell/v1.0/
~ $ which powershell
C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe
~ $ type powershell
powershell is C:/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe
~ $ command -v powershell
C:/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe
```

Version information:
```
~ $ busybox | head -n 2
BusyBox v1.32.0-FRP-3466-g53c09d0e1 (2020-05-30 07:56:19 BST) multi-call binary
(mingw64-gcc 9.2.1-1.fc31; mingw64-crt 6.0.0-2.fc31)
```

<sub>P.S. Funnily enough, Ubuntu WSL has the opposite problem. `type` and `command -v` behave correctly while `which` prints double slashes.</sub>

**Comment by rmyorston** [comment]
Upstream BusyBox ```ash``` and ```dash``` exhibit the same behaviour.  ```bash``` and Korn shell ignore one trailing slash but let any more through.  I've implemented the latter, plus a couple of other minor things.

A pre-release binary with this change (```busybox_pre.exe```) is available [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by ale5000-git** [comment]
Strange behaviour:
```
~ $ cd //C04/lantest
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd /
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd //
ash: cd: can't cd to //: Invalid argument
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd ///
//C04/lantest $ pwd
/
//C04/lantest $
```
