### ISSUE TITLE
busybox-w32 has an imperfect understanding of UNC paths

### ISSUE THREAD

**Issue by rmyorston** [rmyorston/busybox-w32#192]
Strange behaviour:
```
~ $ cd //C04/lantest
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd /
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd //
ash: cd: can't cd to //: Invalid argument
//C04/lantest $ pwd
//C04/lantest
//C04/lantest $ cd ///
//C04/lantest $ pwd
/
//C04/lantest $
```

The / may be ok on Linux but not on Windows.

_Originally posted by @ale5000-git in https://github.com/rmyorston/busybox-w32/issues/191#issuecomment-651266422_

**Comment by ale5000-git** [comment]
UNC paths should be mostly ok since `cd /` work perfectly but `cd ///` is probably replaced to `/` in a different part of code not tracked by your changes.

**Comment by rmyorston** [comment]
I've substantially rewritten how paths are handled by ```cd``` in ```ash```.

```cd ///``` and ```cd /xyz``` when the current directory is on a UNC path work better now.

A pre-release binary with this change (```busybox_pre.exe```) is available [on my website](https://frippery.org/files/busybox/prerelease).
