### ISSUE TITLE
Build install by default

### ISSUE THREAD

**Issue by longnguyen2004** [rmyorston/busybox-w32#194]
The `install` command just copies files and sets their permissions, There are some build scripts that use it, so I'd like to see it built by default

**Comment by rmyorston** [comment]
Done. The latest pre-release binary [on my website](https://frippery.org/files/busybox/prerelease) has this change.

Attempting to set file ownership or permissions may not work as on *NIX.

**Comment by longnguyen2004** [comment]
That's fine, I just need `install` to be there

**Comment by longnguyen2004** [comment]
Another question: How would I cross-compile with Clang? It doesn't use separate binaries for each target, but instead a single binary with a `--target=` argument to select the target. I tried setting `CFLAGS` but it doesn't seem to propagate to all the different Makefiles

**Comment by rmyorston** [comment]
Sorry, off the top of my head I have no idea.

I don't think I've ever knowingly used Clang to *compile* anything much less *cross-compile*.

**Comment by longnguyen2004** [comment]
Alright guess I'll have to go through all the Makefiles myself xD for now I'll close this
