### ISSUE TITLE
ls -d output escaped backslashes

### ISSUE THREAD

**Issue by longnguyen2004** [rmyorston/busybox-w32#196]
While these 3 commands all work:
```
ls -d C:\Users
ls -d C:\\Users
ls -d C:/Users
```
the outputs of them are different...
![image](https://user-images.githubusercontent.com/15729831/90333097-01e13100-dfed-11ea-8f36-5967c8a4d9a5.png)

This has tripped up some scripts that I tested.
We can either do: forward slash (Unix-style) or escaped backslash (Windows-style)

**Comment by rmyorston** [comment]
The behaviour is consistent, just not in the way you want!

In your first command ```C:\Users``` is equivalent to ```C:Users``` which on Windows is treated as a reference to the file ```Users``` in the current directory of the ```C:``` drive. (Windows has a current directory for each drive.) I don't know what your current directory on ```C:``` was when you ran that command. It might have been ```C:/``` or it could have been some other directory that has a ```Users``` subdirectory, the output would have been the same in either case. If your current directory on ```C:``` *didn't* have a ```Users``` subdirectory the output would have been ```ls: C:Users: No such file or directory```.

Anyway, all three commands show that ```ls``` doesn't normalise its arguments. This is also true for coreutils ```ls``` on Linux:
```
$ ls -d ./dir///
./dir///
```
The name is listed exactly as it was entered, even if it could do with being tidied up.

It's easy to modify busybox-w32 ```ls``` so it replaces backslashes with forward slashes, but that would only fix this particular case. Most commands don't normalise their file arguments, so eventually someone will want a fix for ```stat``` or ```dirname```.

How were your scripts tripped up by this behaviour? Is a more general solution possible?

**Comment by longnguyen2004** [comment]
Hmm alright guess I'll have to debug the script a bit. It was a libtool script that's usually used by various libraries

**Comment by rmyorston** [comment]
Do you know where the backslashes are coming from?

The shell replaces all backslashes in environment variables apart from ```SYSTEMROOT``` and ```COMSPEC```. I wouldn't expect those to be used by libtool.

I'm cautious about modifying ```ls``` in case it breaks other scripts that depend on the current behaviour.

**Comment by longnguyen2004** [comment]
I believe it was to get the full path of the library and pass it to the compiler, then somewhere along the way the unescaped backslashes get in. I'll still have to debug a bit though

**Comment by longnguyen2004** [comment]
Oh I figured it out now. libtool constructs a command on runtime, then uses `eval` to execute it. While doing so, it fails to escape any unescaped backslashes in file paths, which causes it to get thrown out by `eval`, causing the error.
Can you add an option to escape backslashes in `ls`, that's controlled by an environment variable? I think that's a suitable solution.

**Comment by rmyorston** [comment]
I prefer to change backslashes to forward slashes rather than escaped backslashes:
- Forward slashes can be replaced in-place; escaped backslashes require a new string to be created.
- Escaped backslashes are interpreted differently if placed in single quotes. Normally not a problem, but ```"\\Users\\rmy"``` is my home directory whereas ```'\\Users\\rmy'``` is a non-existent UNC path.

The 'fix_backslash' branch modifies ```ls``` to replace backslashes with forward slashed if the environment variable ```BB_FIX_BACKSLASH``` is set to 1. In all other cases the existing behaviour is preserved.

A pre-release binary is available: [busybox-w32-fix-backslash-gd13ee992a.exe](https://frippery.org/files/busybox/prerelease/busybox-w32-fix-backslash-gd13ee992a.exe)

**Comment by longnguyen2004** [comment]
Thanks for the fix. Although I've realized the problem is somewhere else, this could be useful for other stuff.
