### ISSUE TITLE
Backslash not replaced in pwd and ls

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#198]
Backslash not replaced in pwd and ls.

See:
```
C:\>busybox ash
C:/ $ pwd
C:/
C:/ $ cd \\\\NAS326\\folder
//NAS326/folder $ pwd
\\NAS326\folder/
//NAS326/folder $
```

No change with: BB_FIX_BACKSLASH=1

Also:
```
//NAS326/folder $ ls -d \\\\NAS326\\folder
\\NAS326\folder
```

**Comment by rmyorston** [comment]
```pwd``` is a different case. The directory argument to the ```cd``` built-in is normalised so it can have backslashes replaced unconditionally. Fixed and a new [prerelease](https://frippery.org/files/busybox/prerelease/busybox-w32-PRE-3579-ge1a7b5a4c.exe) issued.

```ls``` Works For Me™. Did you export the variable?

**Comment by ale5000-git** [comment]
I have missed export, thanks.
Everything is fixed.
