### ISSUE TITLE
printf cannot output % in octal escape \045

### ISSUE THREAD

**Issue by yindian** [rmyorston/busybox-w32#199]
It is expected to output `%` for `printf '\045'` , which is what we get in bash or dash. However, this seems to be broken in busybox-w32 release FRP-3532-g01a256149 and FRP-3578-g359211429, while it works in FRP-3466-g53c09d0e1.

More tests: `printf "foo\045bar\nfoo\045\045bar\n"` should output
```
foo%bar
foo%%bar
```
instead of
```
foobar
foo%bar
```

```
for c in `seq 0 255`; do printf `printf '\%03o' $c`; done | wc -c
```
should get `256` instead of `255`

**Comment by rmyorston** [comment]
Thanks for the report. Should be fixed now. There's a new pre-release binary [on my website](https://frippery.org/files/busybox/prerelease).

**Comment by yindian** [comment]
Thanks for your quick response. I have tested the pre-release binary and it works great. Nice!
