### ISSUE TITLE
Is there any chance to have arm64-based windows 10 version?

### ISSUE THREAD

**Issue by donmor** [rmyorston/busybox-w32#206]
For devices like rpi4, surface pro x, etc.

**Comment by mizvekov** [comment]
Second this. Nowadays clang has working support for ARM64, both for for MSVC and Mingw drivers.

**Comment by rmyorston** [comment]
Prerelease binaries for Windows on ARM are now available from [my website](https://frippery.org/files/busybox/prerelease). The most recent will always be `busybox_pre64a.exe`; currently this is a copy of `busybox-w64a-PRE-5279-ge765357e5.exe`.

The binary has been cross-compiled on Fedora Linux using [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). I don't have any hardware running Windows on ARM so my testing has been done using a QEMU emulated CPU and wine-arm64, as described in this [blog post](https://www.linaro.org/blog/emulate-windows-on-arm/).

I've no idea if it works on real hardware.

**Comment by PeronGH** [comment]
> I've no idea if it works on real hardware.

I tested it, and it runs. However, in `bash`, it still crashes when permission is denied or when trying to `cd` into a non-existent directory. Additionally, the `arch` command now returns `unknown`, but at least it doesn't crash the program like the x86 version. I guess it's an improvement, but it still needs some fixes.

**Comment by rmyorston** [comment]
OK, there's a new prerelease where `uname(2)` knows about aarch64.

The issue with the shell failing on errors is probably related to `longjmp(3)`. It's no longer a problem in the clang build on x86_64, and the related failure of `test 3 -eq w` has been fixed in the aarch64 build.

I can _see_ the shell problem in my emulated CPU/wine-arm64 virtual machine. Fixing it is another matter...

**Comment by rmyorston** [comment]
And now there's another new prerelease (PRE-5282). This uses a different exception handling method. This _might_ have made the problems in the shell go away.

I still see some random segfaults in my test VM, but frankly I'm astonished it works at all.

**Comment by rmyorston** [comment]
I've been able to try the Windows on ARM build on actual hardware. Recent builds appear to work without issues in my limited testing. Whether they'll work for what _you_ want to do, only you can tell.

**Comment by rmyorston** [comment]
The FRP-5301 release includes a Windows on ARM binary.
