### ISSUE TITLE
Set home path and / or an arg for a .profile or .bashrc file as command args

### ISSUE THREAD

**Issue by diginfo** [rmyorston/busybox-w32#211]
Firstly Thanks :-)

I've not used MSDOS for probably 20 years and are now forced to, this makes life a lot easier.

I have searched google and the issues here, but I cannot find an answer to this ??

Is it possible to set the home / pwd during startup with a command arg and is it possible to have a .profile file that can be passed to busybox to execute whenever the shell is opened ??

Again, many thanks

**Comment by avih** [comment]
If you invoke `busybox sh -l` (login shell) then `~/.profile` will run, and you can use it to CD to any dir you like. I don't _think_ `sh` itself accepts an argument for the initial working dir.

**Comment by rmyorston** [comment]
>Firstly Thanks :-)

You're welcome. I'm glad you find it useful.

Shells are inconsistent in how they handle start-up. Here's what the shell in busybox-w32 does:

- When started as a login shell it sources ```/etc/profile``` and ```$HOME/.profile```. On UNIX this happens automatically during the login process, on Windows you have to specify the ```-l``` option yourself.
- busybox-w32 has an undocumented shell option ```-d``` which allows you to specify the current directory of the new shell. This has to appear *before* the ```-s``` or ```-c``` options.
- The ```-s``` option allows the shell to continue reading commands from stdin after processing any other command line arguments. The ```-c``` option allows a command to be specified on the command line. These can be combined to let you run or source a script of your choosing. (However, this doesn't work in bash or the upstream BusyBox shell, which is compatible with bash in this respect. The busybox-w32 shell is compatible with dash.)

For example, to start a shell with ```C:/Users``` as its current directory, sourcing a file in my home directory:
```
~ $ cat startup
#!/bin/sh

echo hello start up
export IM_START_UP=1
~ $ sh -d C:/Users -s -c ". ~/startup"
hello start up
C:/Users $ echo $IM_START_UP
1
C:/Users $
```
To *run* the script instead:
```
~ $ sh -d C:/Users -s -c ~/startup
hello start up
C:/Users $ echo $IM_START_UP

C:/Users $
```

**Comment by diginfo** [comment]
@rmyorston & @avih - thanks so much for helping.

The solution that worked perfectly for me was using the ~/.profile option as I am calling the shell with: `busybox64 sh -l`

In this file I can change my paths and define my aliases & paths etc etc- perfect !

Many Thanks, I will close the issue.

**Comment by avih** [comment]
I think bash will source ~/.bashrc every time it's invoked (interactively?), in addition to some other file which is sourced when invoked as a login shell.

Does busybox-w32 have any file which gets sourced on all (interactive?) invocations?

**Comment by rmyorston** [comment]
There isn't a specific file but the ```ENV``` variable, which is specified by POSIX, lets you do something similar. The dash man page explains it thus:

```
     If the environment variable ENV is set on entry to an interactive shell,
     or is set in the .profile of a login shell, the shell next reads commands
     from the file named in ENV.  Therefore, a user should place commands that
     are to be executed only at login time in the .profile file, and commands
     that are executed for every interactive shell inside the ENV file.  To
     set the ENV variable to some file, place the following line in your
     .profile of your home directory

           ENV=$HOME/.shinit; export ENV

     substituting for “.shinit” any filename you wish.
```

**Comment by avih** [comment]
Thanks, I wasn't aware of that.

> ... and commands that are executed for every interactive shell inside the ENV file.

However, as far as I can tell POSIX doesn't limit it to interactive shells:

> ENV  This variable can be used to set aliases and other items local to the invocation of a shell. The file referred to by ENV differs from $HOME/.profile in that .profile is typically executed at session start-up, whereas the ENV file is executed at the beginning of each shell invocation. The ENV value is interpreted in a manner similar to a dot script, in that the commands are executed in the current environment and the file needs to be readable, but not executable. However, unlike dot scripts, no PA TH searching is performed. This is used as a guard against Trojan Horse security breaches.

**Comment by rmyorston** [comment]
From [Section 2.5.3 Shell variables](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_03):
>This variable, when and only when an interactive shell is invoked...

**Comment by avih** [comment]
Indeed. Thankis.
