### ISSUE TITLE
Getting a busybox version banner

### ISSUE THREAD

**Issue by d-faure** [rmyorston/busybox-w32#215]
In #171, I managed to get a shell banner using the following command line:
```
head --help 2>&1 | head -n 2
```
But it would be nice to have a simpler way to get it, such as:
```
busybox --version
```

**Comment by rmyorston** [comment]
The shell in BusyBox has a banner if the build-time configuration option ```CONFIG_FEATURE_SH_EXTRA_QUIET``` is not set. Both upstream BusyBox and busybox-w32 have it set in the default configuration, though.

**Comment by d-faure** [comment]
The idea was to get a way to have the minimal build details available, whatever flags was choosen at build-time. Therefore the busybox specific version flag seemed a good idea.

But effectively, looking more deeply at the code in [hush.c](https://github.com/rmyorston/busybox-w32/blob/e957318f5f9c618f8bd98e2aa5d92e80916c4154/shell/hush.c#L10510) and in [ash.c](https://github.com/rmyorston/busybox-w32/blob/e957318f5f9c618f8bd98e2aa5d92e80916c4154/shell/ash.c#L10336), the banner is available for interactive shells only, which relies on the `-i` invocation option (and therefore justify its existence).

Could you please disable the `CONFIG_FEATURE_SH_EXTRA_QUIET` in your future build in order to get a startup banner when starting busybox with the `-i` option ?

**Comment by rmyorston** [comment]
Sorry, no, I won't disable ```CONFIG_FEATURE_SH_EXTRA_QUIET``` in the default build. I tried disabling it and the result was just too noisy for my taste. The banner appears for any interactive shell not just those with the ```-i``` option set.

The most reliable way to get the version is probably ```busybox | head -1```. That'll work even if help messages are disabled in the build, though not if the ```busybox``` applet itself is disabled!

**Comment by d-faure** [comment]
it's kinda pity that the control of the banner was so coarse, but hopefully, we have a solution which deserve to be noticed somewhere.
I'm closing the topic for now.
