### ISSUE TITLE
windows7(64bit) BusyBox64 Cannot create symbolic link

### ISSUE THREAD

**Issue by jiuweiljp** [rmyorston/busybox-w32#217]
-----------------------------------------------
BusyBox v1.34.0-FRP-3902-g61e53aa93 (2021-03-02 15:10:05 GMT)
(mingw64-gcc 10.2.1-2.fc33; **mingw64-crt** 7.0.0-2.fc33; glob)

ln -s  Can't run
-----------------------------------------------
BusyBox v1.34.0-FRP-3902-g61e53aa93 (2021-03-02 15:10:01 GMT)
(mingw32-gcc 10.2.1-2.fc33; **mingw32-crt** 7.0.0-2.fc33; glob)

ln -s  ok
-----------------------------------------------

Microsoft Windows [version 6.1.7601] 
NTFS Partition

**Comment by rmyorston** [comment]
This should be fixed in the [latest 64-bit prerelease binary.](https://frippery.org/files/busybox/prerelease/busybox_pre64.exe)

**Comment by jiuweiljp** [comment]
Thank
