### ISSUE TITLE
odd busybox sh applet stderr behavior

### ISSUE THREAD

**Issue by jonforums** [rmyorston/busybox-w32#218]
On Win10 x64 using powershell 7.1.3 and the simple test case from below, it appears `busybox` adds extra (internal debugging?) data to the child exe's `stderr`.

```powershell
PS $ busybox | busybox head -2
BusyBox v1.34.0-FRP-3902-g61e53aa93 (2021-03-02 15:10:05 GMT)
(mingw64-gcc 10.2.1-2.fc33; mingw64-crt 7.0.0-2.fc33; glob)

# busybox's sh applet adding extra data to an exe's stderr
PS $ busybox.exe sh -c './fopen.exe'
--> unable to open 'R:/foo.log'
sh: ./fopen.exe: No error
PS $ $?
False

# blackhole stderr
PS $ busybox.exe sh -c './fopen.exe 2> /dev/null'
PS $ $?
False
```

Simple test code built via [w64devkit](https://github.com/skeeto/w64devkit):

```c
// build via:
//     $ gcc -Wall -Wextra -pedantic -specs=ucrtbase.spec -s -o fopen.exe fopen.c
#include <stdio.h>
#include <time.h>

#define TIME_STR_MAX 32

static
FILE *logme;

static size_t
getTimestamp(char buf[], size_t max)
{
    time_t now;
    struct tm utc;

    time(&now);
    errno_t err = gmtime_s(&utc, &now);
    if (err) {
        fprintf(stderr, "Problem converting current time to UTC\n");
        return 0;
    }

    return strftime(buf, max, "%Y-%m-%dT%H:%M:%S", &utc);
}

int
main(void)
{
    char timebuf[TIME_STR_MAX];

    logme = fopen("R:/foo.log", "a+b");
    if (logme == NULL) {
        fprintf(stderr, "--> unable to open 'R:/foo.log'\n");
        return -1;
    }

    size_t rc = getTimestamp(timebuf, TIME_STR_MAX);
    if (rc == 0) {
        fprintf(stderr, "--> unable to calculate timestamp\n");
        return -1;
    }
    fprintf(logme, "[%s] Hello world from %s\n", timebuf, "Dino");
    fclose(logme);
}

// vim: et
```

**Comment by rmyorston** [comment]
There's a flaw in the implementation of ```execve(2)``` in busybox-w32. It's unable to distinguish between a program failing to run and its main function returning -1. The error message you're getting from the shell should only appear when the program fails to run.

I'll consider whether anything can be done about this. In the meantime you may wish to use return values other than -1. The standard ```EXIT_SUCCESS``` and ```EXIT_FAILURE``` values are good.

**Comment by jonforums** [comment]
It worked; should have been using `EXIT_FAILURE` in the first place. Too bad `-pedantic` wasn't my safety net. Thanks

**Comment by rmyorston** [comment]
I've fixed ```execve(2)``` so it can handle a program returning a status of ```-1```. The most recent [prerelease binaries](https://frippery.org/files/busybox/prerelease) have this fix if anyone would like to play with it.

Trivia for the curious: the shell in busybox-w32 (like most Unix shells) puts the return status of the last command in the ```$?``` variable. However, only the least significant 8 bits of the status value are returned. Thus if a program has an exit status of ```-1```, ```$?``` contains ```255```. Similarly, ```-2``` and ```-128``` come out as ```254``` and ```128```.

**Comment by avih** [comment]
> However, only the least significant 8 bits of the status value are returned. Thus if a program has an exit status of -1, $? contains 255. Similarly, -2 and -128 come out as 254 and 128.

I vaguely recall something about it in POSIX, but I can't find it now. IIRC AT&T ksh can return values bigger than 255 for internal things, however, for external programs all shells I have access to seem to return a value in the range of 0-255 (as in the value cast to `uint8_t` like in your examples).

Shells I tested the following c program:
```C
#include <stdlib.h>

int main(int argc, char **argv) {
        return argc > 1 ? atoi(argv[1]) : 0;
}
```

Using https://github.com/avih/shcmp I tested the following shells: bash, bash_posix, dash_58, dash_591, dash_5102, dash_5111, dash_master, ksh93, ksh2020, ksh93u_m, loksh, oksh, mksh, mksh_posix, pdksh, bb_ash, bosh, bosh_posix, pbosh, yash, nbsh, fbsh

bash is 5.0.17, loksh/oksh are open bsd shell on linux (pdksh derivative), nbsh/fbsh are net/free bsd shells (ash derivatives), [p]bosh are schily-tools (derivatives of Sun shell) and the _posix variants are invoked with posix-compliance CLI args.

I tried with negative values and values bigger than 255, and all these shells return the value cast to `uint8_t`.

**Comment by jonforums** [comment]
The w64 prerelease binary worked great. @avih interesting shell test results of `uint8_t` handling of two's complement...thanks.

**Comment by rmyorston** [comment]
The latest release (FRP-4264-gc79f13025) includes the fix for this issue.
