### ISSUE TITLE
patch new file? After patching, the MD5 values of the two files are still different.

### ISSUE THREAD

**Issue by jiuweiljp** [rmyorston/busybox-w32#219]
busybox_pre64.exe:BusyBox v1.34.0-PRE-3911-g375cda9a8 (2021-05-13 17:51:38 BST) 
os: windows 7 (64bit)
---------------------
old file content
---------------------
```
nanddump -f hg8321_mt_mtd0 /dev/mtd0
nanddump -nf hg8321_mt_mtd0_noecc /dev/mtd0
nanddump -of hg8321_mt_mtd0_oob /dev/mtd0
nanddump -nof hg8321_mt_mtd0_oob_noecc /dev/mtd0

nanddump -f hg8321_mt_mtd1 /dev/mtd1
nanddump -nf hg8321_mt_mtd1_noecc /dev/mtd1
nanddump -of hg8321_mt_mtd1_oob /dev/mtd1
nanddump -nof hg8321_mt_mtd1_oob_noecc /dev/mtd1
```
---------------------
new file content
---------------------
```
nanddump -f hg8321_mt_mtd0_1 /dev/mtd0
nanddump -nf hg8321_mt_mtd0_1_noecc /dev/mtd0
nanddump -of hg8321_mt_mtd0_oob_1 /dev/mtd0
nanddump -nof hg8321_mt_mtd0_oob_noecc_1 /dev/mtd0

nanddump -f hg8321_mt_mtd1 /dev/mtd1
nanddump -nf hg8321_mt_mtd1_noecc /dev/mtd1
nanddump -of hg8321_mt_mtd1_oob /dev/mtd1
nanddump -nof hg8321_mt_mtd1_oob_noecc /dev/mtd1
```
---------------------
$\>diff old new >patch1

$>patch -p0 <patch1        ( run error , patch new?  )
  patching file new
  Hunk 1 FAILED 1/1.

```
$>patch -p0 old <patch1
patching file old
```
---------------------
continue...
$\>md5sum old new
2f8aed1e41b051770ff5eca6d470db11  old
a87b2f366a776a649ac39ef2e54eac1a  new

Note: I open old and new files with a text editor, which have the same content, but I don't know why MD5 values are different.
If you continue to use the diff command.

$\>diff old new   ( The old file has been patched, but running the diff command found that the old new file is still different )
```
--- old
+++ new
@@ -1,9 +1,9 @@
-nanddump -f hg8321_mt_mtd0_1 /dev/mtd0
-nanddump -nf hg8321_mt_mtd0_1_noecc /dev/mtd0
-nanddump -of hg8321_mt_mtd0_oob_1 /dev/mtd0
-nanddump -nof hg8321_mt_mtd0_oob_noecc_1 /dev/mtd0
-
-nanddump -f hg8321_mt_mtd1 /dev/mtd1
-nanddump -nf hg8321_mt_mtd1_noecc /dev/mtd1
+nanddump -f hg8321_mt_mtd0_1 /dev/mtd0
+nanddump -nf hg8321_mt_mtd0_1_noecc /dev/mtd0
+nanddump -of hg8321_mt_mtd0_oob_1 /dev/mtd0
+nanddump -nof hg8321_mt_mtd0_oob_noecc_1 /dev/mtd0
+
+nanddump -f hg8321_mt_mtd1 /dev/mtd1
+nanddump -nf hg8321_mt_mtd1_noecc /dev/mtd1
 nanddump -of hg8321_mt_mtd1_oob /dev/mtd1
 nanddump -nof hg8321_mt_mtd1_oob_noecc /dev/mtd1
```
----------------------
continue...
Copy old new patch1 files to Ubuntu
$patch - p0 < Patch1
patching file old
$md5sum old new
a87b2f366a776a649ac39ef2e54eac1a  new
a87b2f366a776a649ac39ef2e54eac1a  old

**Comment by rmyorston** [comment]
```patch``` is inserting Unix-style line endings (LF) when it makes changes. The original files have DOS-style line endings (CRLF).

The command ```diff -b old new``` ignores differences in whitespace and should show no difference between the files. Converting the line endings in the patched file with ```unix2dos old``` should make the checksums match.

I'll have a think about what can be done to make this sort of workflow better on Windows...

**Comment by jiuweiljp** [comment]
thank !

The patch command modifies the new file by default.

**Comment by rmyorston** [comment]
>I want the patch command to patch old files by default

I'm no expert on ```patch``` but the behaviour here does appear to be incorrect.

There's an upstream [bug report](https://bugs.busybox.net/show_bug.cgi?id=11981) which seems to cover this.

(The issue with line endings is, of course, specific to Windows.)

**Comment by avih** [comment]
> I'll have a think about what can be done to make this sort of workflow better on Windows...

FWIW, Gnu patch has this, I think it should cover the use case? :
```
-l  or  --ignore-whitespace
    Match patterns loosely, in case tabs or spaces have been munged
    in your files.  Any sequence of one or more blanks in the patch
    file matches any sequence in the original file, and sequences
    of blanks at the ends of lines are ignored.  Normal characters
    must still match exactly.  Each line of the context must still
    match a line in the original file.
```

However, `patch` should *not* behave like so by default IMHO, even on Windows, at which case I doubt this option's value, as one would still need to be aware of the issue in the first place.

Additionally, the patched file could end up with mixed line-endings, and handling that is an additional chore which is needs either heuristics or an additional option.

Overall, IMHO, users which process text files with POSIX tools on Windows should ensure they're used with files which have POSIX line endings, especially when tools to convert between POSIX and Windows line endings exist.

**Comment by jiuweiljp** [comment]
> > I want the patch command to patch old files by default
> 
> I'm no expert on `patch` but the behaviour here does appear to be incorrect.
> 
> There's an upstream [bug report](https://bugs.busybox.net/show_bug.cgi?id=11981) which seems to cover this.
> 
> (The issue with line endings is, of course, specific to Windows.)

thank.

I saw https://bugs.busybox.net/show_bug.cgi?id=11981 This bug has been reported
