### ISSUE TITLE
Consider asking github support to sever this repo "fork" status

### ISSUE THREAD

**Issue by garoto** [rmyorston/busybox-w32#221]
While this is none of my concern, but I learned\[1\] that Github `forks` have some inherent disadvantages as far as GH's web interface goes, and clearly, calling your `fork` a `fork` at this point in time is quite the misnomer.

\[1\]: https://github.com/chrisant996/clink/issues/109

**Comment by realthunder** [comment]
@rmyorston, I have no problem changing the parent status of my fork. Just tell me what I shall do. I can't access the github support [ticket](https://support.github.com/ticket/1242738),

**Comment by rmyorston** [comment]
@realthunder Hmm, I wondered if the ticket might not be public.  Though GitHub Support did say:
>If you're in touch with them, you could ask realthunder to authorize this request by replying to this message with an email address associated with their GitHub account?

Which suggests they think you should be able to see their message. Dunno how.

Anyway, they also said:
>Or you could get them to give authorization in a comment on that issue?

Which, I think, you've done above. We'll see if that's good enough for them.

Thank you!

**Comment by rmyorston** [comment]
OK, Support have made rmyorston/busybox-w32 the root of the network. Searching for 'busybox' on GitHub now finds my repo rather than realthunder/busybox.w32.

Thanks to @garoto for pointing this out and @realthunder for cooperating in making the change happen!

**Comment by avih** [comment]
> and @realthunder for cooperating in making the change happen!

I presume also for starting this project? :)

**Comment by garoto** [comment]
Nice that it all went so smoothly, kinda impressed. And kudos to both @realthunder for stepping in for @rmyorston on his continuous work on the port.

**Comment by rmyorston** [comment]
@avih Actually, busybox-w32 was started by Duy Nguyen (GitHub user @pclouds), though they'd pretty much stopped work on it when I picked it up in 2012. When the pclouds/busybox-w32 repo was deleted in 2018 GitHub's algorithm  chose realthunder/busybox-w32 as the replacement root.

**Comment by garoto** [comment]
Had no idea yours and realthunder's repos were both forks of a deleted repo. Assuming GH chooses a new root when that happens based on fork age?
