### ISSUE TITLE
Tar XZ and LZMA can only be decompressed

### ISSUE THREAD

**Issue by jiuweiljp** [rmyorston/busybox-w32#222]
E:\busybox>xz
BusyBox v1.34.0-PRE-4231-gfd6f917a6 (2021-07-05 12:46:39 BST)

Usage: xz -d [-cfk] [FILE]...

Decompress FILEs (or stdin)

        -d      Decompress
        -c      Write to stdout
        -f      Force
        -k      Keep input files
        -t      Test integrity

E:\busybox>lzma
BusyBox v1.34.0-PRE-4231-gfd6f917a6 (2021-07-05 12:46:39 BST)

Usage: lzma -d [-cfk] [FILE]...

Decompress FILEs (or stdin)

        -d      Decompress
        -c      Write to stdout
        -f      Force
        -k      Keep input files
        -t      Test integrity

**Comment by rmyorston** [comment]
There are a couple of things going on here.  Upstream BusyBox only supports decompression of XZ and LZMA data. When ```tar``` wants to compress to these formats it tries to run an external program that has support for compression. The ```xz``` and ```lzma``` applets in BusyBox aren't suitable for this as they only support decompression.

busybox-w32 ```tar``` always tries to use the applets and therefore fails when asked to  compress to XZ or LZMA. It's unlikely that suitable compression programs will be available in many common scenarios where busybox-w32 is being used. However it would be possible to at least make busybox-w32 _try_ to execute such an external program.

**Comment by rmyorston** [comment]
A proper fix for this is out of scope for busybox-w32: support for the required compressors is an upstream issue.

With the latest version we now have feature parity with upstream: any attempt to generate an XZ or LZMA compressed tar file will try to run an external program. This will almost certainly fail, though it's now failing for a different reason.

There are new prerelease binaries in the [usual place.](https://frippery.org/files/busybox/prerelease)

**Comment by avih** [comment]
> any attempt to generate an XZ or LZMA compressed tar file will try to run an external program

For reference, stand alone `xz.exe` for Windows can be obtained here https://tukaani.org/xz/

Not sure how LZMA is different and/or which program it's trying to use other than `xz`.

**Comment by jiuweiljp** [comment]
Thanks Reply.
--------------------
I tested busybox version 1.33.1 in ubuntu, tar lzma xz can compress.
--------------------
```
admin1@virtualbox-16:/app/busybox/busybox-1.33.1$ ./busybox tar cavf test.tar.lzma busybox
busybox
admin1@virtualbox-16:/app/busybox/busybox-1.33.1$ file test.tar.lzma 
test.tar.lzma: LZMA compressed data, streamed
admin1@virtualbox-16:/app/busybox/busybox-1.33.1$ ./busybox tar cavf test.tar.xz busybox
busybox
admin1@virtualbox-16:/app/busybox/busybox-1.33.1$ file test.tar.xz
test.tar.xz: XZ compressed data
```

**Comment by jiuweiljp** [comment]
> There are a couple of things going on here. Upstream BusyBox only supports decompression of XZ and LZMA data. When `tar` wants to compress to these formats it tries to run an external program that has support for compression. The `xz` and `lzma` applets in BusyBox aren't suitable for this as they only support decompression.
> 
> busybox-w32 `tar` always tries to use the applets and therefore fails when asked to compress to XZ or LZMA. It's unlikely that suitable compression programs will be available in many common scenarios where busybox-w32 is being used. However it would be possible to at least make busybox-w32 _try_ to execute such an external program.

========================
I tested that in ubuntu busybox ver 1.33.1, it does call external xz and lzma.
But under windows BusyBox v1.34.0-PRE-3911-g375cda9a8 (2021-05-13 17:51:38 BST) does not call external xz and lzma

```
D:\shell\busybox\x64>xz --help
Usage: xz [OPTION]... [FILE]...
Compress or decompress FILEs in the .xz format.

  -z, --compress      force compression
  -d, --decompress    force decompression
  -t, --test          test compressed file integrity
  -l, --list          list information about .xz files
  -k, --keep          keep (don't delete) input files
  -f, --force         force overwrite of output file and (de)compress links
  -c, --stdout        write to standard output and don't delete input files
  -0 ... -9           compression preset; default is 6; take compressor *and*
                      decompressor memory usage into account before using 7-9!
  -e, --extreme       try to improve compression ratio by using more CPU time;
                      does not affect decompressor memory requirements
  -T, --threads=NUM   use at most NUM threads; the default is 1; set to 0
                      to use as many threads as there are processor cores
  -q, --quiet         suppress warnings; specify twice to suppress errors too
  -v, --verbose       be verbose; specify twice for even more verbose
  -h, --help          display this short help and exit
  -H, --long-help     display the long help (lists also the advanced options)
  -V, --version       display the version number and exit
D:\shell\busybox\x64>tar cavf temp_lzma.tar.xz ..\busybox.exe
..\busybox.exe
BusyBox v1.34.0-PRE-3911-g375cda9a8 (2021-05-13 17:51:38 BST)

Usage: xz -d [-cfk] [FILE]...

Decompress FILEs (or stdin)

        -d      Decompress
        -c      Write to stdout
        -f      Force
        -k      Keep input files
        -t      Test file integrity
```

**Comment by rmyorston** [comment]
PRE-3911-g375cda9a8 is rather old. The most recent prereleases are always those without the version: [busybox_pre.exe](https://frippery.org/files/busybox/prerelease/busybox_pre.exe) and [busybox_pre64.exe](https://frippery.org/files/busybox/prerelease/busybox_pre64.exe).

As I write this the version of the latest prerelease is PRE-4258-g45863925a.

**Comment by jiuweiljp** [comment]
Thank.
The latest version successfully calls external xz and lzma.
