### ISSUE TITLE
ANSI colors lost after MSYS/Cygwin command

### ISSUE THREAD

**Issue by Klexer** [rmyorston/busybox-w32#223]
Whenever I call an MSYS/Cygwin command from Busybox shell, I end up losing the ANSI colors. The colors return after the Busybox command `ls --color`, but this problem did not exist until Q1 2021 (`busybox-w64-FRP-3812-g12e14ebba.exe`, 2021-01-18 was and is still okay).
___
_**w10@Busybox:**_**~**$ `gcc -dumpmachine`
`x86_64-pc-msys`
[1;32mw10@Busybox:[1;34m\~?[0m\$ `_`
___
With `ansicon ...` or `cmd /c ...` I can prevent the colors from being lost. Nevertheless, I would be happy if the ANSI colors were to return after MSYS/Cygwin commands. Windows commands like System32\OpenSSH do not cause any problems.

**Comment by rmyorston** [comment]
It seems that MSYS/Cygwin applications reset the console's virtual terminal processing mode. This wasn't a problem until the default setting for ANSI emulation in busybox-w32 was changed shortly after the FRP-3812 release.

A workaround is to set the Windows environment variable ```BB_SKIP_ANSI_EMULATION=0```.

I've also applied a fix. The most recent [prerelease](https://frippery.org/files/busybox/prerelease) binaries have this.

**Comment by Klexer** [comment]
Thank you for the quick remedy. I tried the two suggested solutions. 1) set environment variable, or 2) new pre-release version.

In addition, I compiled your last master branch with and without changed setting of `CONFIG_SKIP_ANSI_EMULATION_DEFAULT` in the `./.config` file.

All options work on my 64 and 32 bit machines. I really appreciate it.  👍
