### ISSUE TITLE
Touch does not accept ISO dates

### ISSUE THREAD

**Issue by vapaamies** [rmyorston/busybox-w32#230]
BusyBox `touch`:
````
touch -m -d "2020-07-16 23:14:13 +0300" pet.exe
touch: invalid date '2020-07-16 23:14:13 +0300'
````
[MinGit](https://github.com/git-for-windows/git/releases) `touch`:
````
touch -m -d "2020-07-16 23:14:13 +0300" pet.exe

````

**Comment by rmyorston** [comment]
Timezone offsets aren't supported in upstream BusyBox so aren't available in busybox-w32 either.

I've started work on getting them supported upstream.

**Comment by rmyorston** [comment]
Here's how it played out:
- First upstream patch prepared the ground by changing how dates are parsed. No functional changes but a saving of 289 bytes.
- Second upstream patch added support for ISO 8601 timezone offsets. Added 141 bytes, but upstream still gets increased functionality and reduced size.
- Synchronised  busybox-w32 with upstream and added timezone code that's missing from the Microsoft C runtime.

With the most recent [prerelease](https://frippery.org/files/busybox/prerelease) binaries it's possible to do this:
```
~ $ touch -m -d '2020-07-16 23:14:13 +0300' pet.exe
~ $ stat pet.exe | grep Modify
Modify: 2020-07-16 21:14:13.000000000 +0100
~ $
```

**Comment by vapaamies** [comment]
Awesome! Thank you!
