### ISSUE TITLE
Unboxing BusyBox - 14 new vulnerabilities

### ISSUE THREAD

**Issue by ejzhang** [rmyorston/busybox-w32#236]
https://jfrog.com/blog/unboxing-busybox-14-new-vulnerabilities-uncovered-by-claroty-and-jfrog/
https://threatpost.com/busybox-security-bugs-linux-devices/176098

**Comment by rmyorston** [comment]
The issues were fixed in the upstream BusyBox 1.34.0 release. The latest busybox-w32 release (FRP-4487-gd239d2d52) was synchronised with upstream after that so it isn't vulnerable.
