### ISSUE TITLE
Strange uname issue

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#238]
Create a `test.sh` file:
```
#!/bin/sh

uname
```

Then if you run `busybox ash ./test.sh` you get: `Windows_NT`
but if you enter inside `busybox ash` and then run `./test.sh` you get: `./test.sh: line 3: uname: command not found`

**Comment by rmyorston** [comment]
Works for me.

Do you have a (non-busybox-w32) shell in ```/bin/sh```?

**Comment by ale5000-git** [comment]
Azz, now I remember that I had done a junction from `C:\bin` to `C:\Ruby-x64\msys64\usr\bin`, so yes.
Sorry.
