### ISSUE TITLE
Chocolatey package?

### ISSUE THREAD

**Issue by geraldcombs** [rmyorston/busybox-w32#24]
Would it be possible to create a busybox package for [Chocolatey](http://chocolatey.org/)?

**Comment by alejandro5042** [comment]
Related: `busybox` is available from scoop: https://github.com/lukesampson/scoop

**Comment by rmyorston** [comment]
It seems that a package is available now: [https://chocolatey.org/packages/busybox](https://chocolatey.org/packages/busybox)
