### ISSUE TITLE
ANSI code in PS1 and moving cursor in command history

### ISSUE THREAD

**Issue by HuidaeCho** [rmyorston/busybox-w32#243]
When I include ANSI codes in PS1, using the up-arrow and left-arrow to move the cursor in the previous command counts invisible characters in the prompt at the first column. For example, if I set ``PS1="\033]0;Hello\007\w> "``, the first part of PS1 ``\033]0;Hello\007`` is used to set the window title and is not printed in the prompt. However, after running a long command line that spans multiple lines, going back to that command and moving the cursor across lines waits (is stuck) at the first column until the left-arrow key consumes the same number of characters in the ANSI code. In this specific case, I have to hit the left-arrow 10 extra times at the first column to move to one line above because ``\033`` + ``]0;Hello`` + ``\007`` is total 10 characters.

I'm using this version:
```
BusyBox v1.36.0-FRP-4621-gf3c5e8bc3 (2022-02-28 07:17:58 GMT)
(mingw64-gcc 11.2.1-3.fc35; mingw64-crt 9.0.0-2.fc35; glob)
```
How to reproduce it
```bash
> busybox64 sh
> export PS1="\033]0;Hello\007\w> "
> echo very long echo line very long echo line very long echo line very long echo line very long echo line very long very long echo line very long echo line
# make sure the above command is long enough so it spans more than one line
# run the above echo command
# hit up-arrow to display the same command again
# keep hitting left-arrow so you can move to the first line of the command
# observe that you have to hit left-arrow 10 extra times at the first column to move to the first line
```

**Comment by cochon-git** [comment]
Try:
export PS1="\[\033]0;Hello\007\]\w> "

Bracketing the escape sequences in \[ ... \] marks them as 'non printing'

It's not peculiar to busybox it's the same in other shells

**Comment by HuidaeCho** [comment]
@cochon-git Oh! You're right. That works. Thanks a lot! Closing this issue.
