### ISSUE TITLE
HOME env variable is not correctly handled by bash applet

### ISSUE THREAD

**Issue by javacommons** [rmyorston/busybox-w32#244]
* When I set Window's HOME env variable to C:\User\user\home5 and execute "busybox bash -l", the current directory goes to C:/Users/user.

* When I execute "cd" just after "busybox bash -l", the current directory goes to the expected C:\User\user\home5.

```
> busybox pwd
D:/
> echo %HOME%
C:\Users\user\home5
> busybox bash -l
~ $ pwd
C:/Users/user
~ $ cd
~/home5 $ pwd
C:/Users/user/home5
```

* .profile seems to be read from the expected directory C:\User\user\home5.

**Comment by rmyorston** [comment]
The shell in busybox-w32 now respects ```$HOME``` when started with the ```-l``` option.

New [prerelease](https://frippery.org/files/busybox/prerelease/) binaries are available.

As has been reported before (issue #27) there's a quirk in how tilde expansion in the shell interacts with ```$HOME```. This is probably wrong too, but it's an upstream issue so any fix will require coordination with them.

**Comment by javacommons** [comment]
Thank you for your quick responce!
I noticed that "busybox_pre64.exe bash -l" goes to "C:\User\user\home5" now.

Then, I found another issue:

```
>busybox_pre64.exe bash -l
~/home5 $ pwd
C:/Users/user/home5
~/home5 $ ls ~/ (Hitting tab lists under C:\User\user, not under C:\User\user\home5)
```

When loggin into busybox bash (with "busybox_pre64.exe bash -l"), prompt says "~/home5 $".
That means "~/" in command line means "C:\User\user"; this leads wrong file name completion.
If "ls ~/ (TAB)" lists under "C:\User\user\home5" (%HOME%), bash applets is perfect (for me)!

Thanks in advance.

**Comment by rmyorston** [comment]
Your issue with the prompt and file name completion is the same as the one I mentioned above. The problem in this case is in the line editing library rather than the shell. It's also an upstream issue so it may take a bit longer to sort out.

**Comment by javacommons** [comment]
> > The problem in this case is in the line editing library rather than the shell. It's also an upstream issue so it may take a bit longer to sort out.

> Understood. I hope some day this problem be solved too.

I might have found the solution for the the line editing library problem; I tested myself and worked as expected.
When you have time, please apply and check the modification below:

[Modification of libbb/lineedit.c]
```
static NOINLINE const char *get_homedir_or_NULL(void)
{
#if 0x1
	const char *hp = getenv("HOME");
	if (hp != NULL && *hp != '\0') {
		return hp;
	}
#endif
	if (!got_user_strings)
		get_user_strings();
	return home_pwd_buf;
}
```

**Comment by rmyorston** [comment]
Indeed, ```lookupvar()``` is the correct way to do it, but it's a static function in ash.

I've already sent a [patch](http://lists.busybox.net/pipermail/busybox/2022-March/089539.html) upstream which allows for this. It uses the equivalent function for hush, the other shell in BusyBox (which hasn't been ported to busybox-w32).

On reflection it should probably use ```getenv()``` when the line editing code isn't being used from a shell. I'll think about this and may issue a new version of the patch.

**Comment by javacommons** [comment]
> I've already sent a [patch](http://lists.busybox.net/pipermail/busybox/2022-March/089539.html) upstream which allows for this. It uses the equivalent function for hush, the other shell in BusyBox (which hasn't been ported to busybox-w32).

Could you put the patched binary in https://frippery.org/files/busybox/prerelease/ so that I could test it?

**Comment by rmyorston** [comment]
I've make a new upstream [patch](http://lists.busybox.net/pipermail/busybox/2022-March/089540.html).

Since this hasn't been applied yet I've put it on the 'tilde' branch in busybox-w32. There's a binary based on this (busybox_tilde64.exe) in the [prerelease](https://frippery.org/files/busybox/prerelease) directory.

**Comment by javacommons** [comment]
> Since this hasn't been applied yet I've put it on the 'tilde' branch in busybox-w32. There's a binary based on this (busybox_tilde64.exe) in the [prerelease](https://frippery.org/files/busybox/prerelease) directory.

Thank you very much.
I tested busybox_tilde64.exe and it looks good to me!
I'll use this binary for my work until the official release.

```
> busybox_tilde64.exe pwd
D:/
> busybox_tilde64.exe bash -l
~ $ pwd
C:/Users/user/home5
~ $ ls ~/ (TAB lists under C:/Users/user/home5 ==> OK)
~ $ export HOME=C:/Users/user
~/home5 $ ls ~/ (TAB lists under C:/Users/user ==> OK)
~/home5 $ 
```

**Comment by javacommons** [comment]
https://github.com/rmyorston/busybox-w32/blob/master/libbb/lineedit.c#LL264-LL270

Seems lineedit.c is ready for tilde mode, how about merging tilde branch to master branch.

Thanks in advance.

**Comment by rmyorston** [comment]
Actually, support for proper tilde handling is already in master. It came via upstream rather than the tilde branch. Both have the same patch.

The latest [prerelease binaries](https://frippery.org/files/busybox/prerelease) have this fix (and it will be in the next full release, whenever that may be).

**Comment by javacommons** [comment]
> Actually, support for proper tilde handling is already in master. It came via upstream rather than the tilde branch. Both have the same patch.

> The latest [prerelease binaries](https://frippery.org/files/busybox/prerelease) have this fix (and it will be in the next full release, whenever that may be).

Thank you for your reply.
Great!
I checked the latest busybox_pre64.exe and it works perfect!
I'll use busybox_pre64.exe until the next full release.

**Comment by rmyorston** [comment]
Closing this issue as the latest release should have the necessary fixes.
