### ISSUE TITLE
Where to get very old busybox?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#245]
Hi, I know it is a strange request but if you have it somewhere I need a build of busybox-w32 from 2012 (the one that fail with "unzip: zip flags 1 and 8 are not supported" on certain zip files).
I need it to setup a testing environment to make sure zip files are compatible with unzip in old Android recoveries (that use busybox internally).
Thanks.

**Comment by rmyorston** [comment]
The oldest binary I can immediately lay my hands on is busybox-w32-TIG-931-g7e6a84d.exe which is dated 2012-11-29. I've put it in the [prerelease](https://frippery.org/files/busybox/prerelease/) directory.

**Comment by ale5000-git** [comment]
Thanks but unfortunately it seems already fixed in that build.
Look over the internet I see one person that report the problem on BusyBox v1.20.2-jb static (2012-07-27 02:57 +0200).

**Comment by ale5000-git** [comment]
After more research I see that to have that error must be an old version compiled without `ENABLE_DESKTOP`: https://git.busybox.net/busybox/tree/archival/unzip.c?h=1_24_stable#n554

**Comment by ale5000-git** [comment]
Probably there wasn't a build for Windows compiled in that way so I will find another way.
