### ISSUE TITLE
How execute external command (and not the internal applet)?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#246]
Hi,
first thanks for all your work :)

Most of the time I want to use internal applets but sometime I want to use external ones.
For example to use external find (but it is just an example).
The full path isn't static but it must be searched from PATH env.

All of these only find the internal applet:
which find
hash find
command -v find

Also `enable` (from bash) isn't supported.

Is there a way?

**Comment by rmyorston** [comment]
Possibly as an alias:
```
~ $ alias find=$(where find | sed 's/\\/\//g')
~ $ find
FIND: Parameter format not correct
~ $
```

**Comment by ale5000-git** [comment]
Thanks it works, but unfortunately isn't portable.
Afte some tests I have found that if I have my own custom find in the PATH I could use `alias find='find.'` to override it but unfortunately also this isn't portable.

Then I have found another way that work under https://busybox.net/live_bbox/live_bbox.html
but unfortunately not under Windows.

```
cd /tmp
echo '#!/bin/sh' > /tmp/find
chmod +x /tmp/find
PATH=".:$PATH"

busybox find (run busybox find)
busybox env find (run external find)
```

Is there any issue that prevent it from working on Windows or am I missing something?

**Comment by cochon-git** [comment]
The use of 'find' as an example clouds the issue a little, the desire could be Windows 'find' (search text in files) or an alternate (e.g. GNU) version of *nix 'find', and the existence/order of both in PATH will affect/confuse the outcome. So some tweak to PATH will probably always be required on Windows.

As an alternate approach which might work in your case... For enhanced/GNU stuff outside busybox I maintain a copy of MSYS2, have its 'bin' folder in PATH and leverage its version of nice, which has the added advantage of actually nice-ing jobs on Windows, so:

```
nice find *.xyz | xargs ls
nice xz filename
```

nice is not an internal app so steps you out of busybox (you could use 'cmd /c' but nice makes for more portable scripts) and when nice chain executes, say xz, it searches PATH externally and picks up a version of xz that does compression, the internal busybox xz doesn't.

The above works for simple cases like xz, or pipelined 'find -print' (provided the alternate 'find' is earlier in PATH than Windows 'find') but anything more complex like 'find -exec' will be operating outside of busybox and thus reliant on finding external versions of other utility programs (as will be the case no matter what solution you find).

**Comment by rmyorston** [comment]
>Is there any issue that prevent it from working on Windows or am I missing something?

Live BusyBox is built with ```FEATURE_PREFER_APPLETS``` disabled whereas my busybox-w32 binaries have it enabled. The configuration I use really does have a strong preference for applets.

**Comment by ale5000-git** [comment]
@cochon-git
It was only to have a simple example, I have a script that automatically alter PATH and add a folder relative to the script (so the outer folder can be moved) that contain a shell script named `find`, then I source an external shell script and I expect it to use my custom `find` but instead it use the applet.

On Windows I can use `alias find='find.'` but I prefer a more portable way (that work also under Linux).

**Comment by ale5000-git** [comment]
```
override_applet()
{
  if test "$(uname -o)" != 'MS/Windows'; then
    full_path="$(busybox which "${1}")" || { echo "Failed to override ${1}"; return 1; }
    # shellcheck disable=SC2139
    alias "${1}"="${full_path}"  # This expands when defined, not when used (it is intended)
    unset full_path
  else
    # shellcheck disable=SC2139
    alias "${1}"="${1}."  # This expands when defined, not when used (it is intended)
  fi
}

override_applet find
```

I have come up with the above mentioned code.
It isn't elegant but works and don't depend on system components.
I wonder if anyone have a better solution.

**Comment by rmyorston** [comment]
Other ideas:

>I have a script that automatically alter PATH and add a folder relative to the script

Could this script generate a file which defines aliases for stuff in the folder and sets ```ENV``` to point to it?

Or... Since you control what goes in this folder can you arrange that the stuff you want to run from there has names that don't match applet names?

Incidentally, another (non-portable) way to run ```find``` from the path instead of the applet is to mix up the case. ```FIND``` or ```FinD``` won't match the applet name but will (case-insensitively) match a file on disk.

**Comment by ale5000-git** [comment]
I can set ENV vars but I cannot change the underline code that call find.
But you idea can be used with small changes, I could set the path of the override folder in an ENV var in the part of code where I set it and then use it where I set the alias.
Thanks.
