### ISSUE TITLE
mktemp and env -i

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#247]
If in live busybox I use
`env -i busybox ash`
and then inside it
`mktemp`
it works.

But in busybox-w32 it doesn't work:
`mktemp: (null): No such file or directory`

**Comment by rmyorston** [comment]
If the environment variable ```TMPDIR``` doesn't exist or is empty, ```mktemp``` falls back to using ```/tmp```. On Windows it's quite likely that ```/tmp``` doesn't exist.

The error isn't very helpful, it must be said.

**Comment by ale5000-git** [comment]
Is it possible to fallback to GetTempPathA win API if the env isn't set?

**Comment by ale5000-git** [comment]
I have tried to set it but it still error out:
```
env -i busybox ash
TMP=c:/TEST
TMPDIR=c:/TEST
mktemp
```
mktemp: (null): No such file or directory

**Comment by rmyorston** [comment]
It has to be an environment variable. You need to export it.

**Comment by rmyorston** [comment]
There are a couple of problems with the error message:
- The presence of ```(null)``` is an upstream regression. I've submitted a patch.
- It's quite hard to know what to report. Depending on the options the applet uses one of three different library calls: ```mktemp(3)```, ```mkstemp(3)``` or ```mkdtemp(3)```. Each of these can return different errors. They also might not report the name of the file they failed to create. In these circumstances it looks very easy to create a misleading message. I think upstream is probably right to just give up and only report the error code.

**Comment by ale5000-git** [comment]
I don't know the underline code but I think "Unable to find the temp directory" instead of "No such file or directory" would be more clear.

**Comment by rmyorston** [comment]
>I think "Unable to find the temp directory" instead of "No such file or directory" would be more clear.

It would, but that part of message is generated by running ```strerror(3)``` to convert the error code into a string. We have no control over it.

**Comment by ale5000-git** [comment]
What about from mktemp code contatenate string with strerror(3) result?
So it will become: `mktemp: No such file or directory (unable to find temp)`

**Comment by rmyorston** [comment]
Yes, I could add a more specific message for that particular error. But that's only one possible error condition. It isn't practical to provide meaningful messages to cover everything that could go wrong.

**Comment by ale5000-git** [comment]
I know but in this case the error was particularly confusing.
It is your choice anyway :)
