### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#249]
I know this code is wrong but it shouldn't cause the shell to exit:
`echo text >&9999`
This instead cause the creation of a file:
`echo text >&9999999999`

I think it would be better if they report `Bad file descriptor`

**Comment by rmyorston** [comment]
It's an upstream issue. I've submitted a [patch](http://lists.busybox.net/pipermail/busybox/2022-April/089634.html).

**Comment by ale5000-git** [comment]
Thanks.

**Comment by rmyorston** [comment]
It's taken a while, but upstream have finally had a look at this issue. They've applied a different fix.

Try the latest [prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5429 or above).

**Comment by ale5000-git** [comment]
@rmyorston
Thanks, it now works a lot better but why 3 different errors?

```
echo text >&99999999
ash: fcntl(1,F_DUPFD,100000000): Too many open files
echo text >&999999999
ash: fcntl(1,F_DUPFD,1000000000): Too many open files
echo text >&9999999999
ash: syntax error: bad fd number
```

**Comment by rmyorston** [comment]
>why 3 different errors?

Because different things go wrong?

The upstream commit are 0829fce079dae45737330114c27886cb8af85043 and 08fb86726b508eb99502a6681da94395c4e4580c.

**Comment by ale5000-git** [comment]
@rmyorston
It is just a minor thing but "Too many open files" seems a bit misleading.

**Comment by rmyorston** [comment]
>`Too many open files` seems a bit misleading.

Perhaps so, but that's the message upstream chose to use. I don't plan to take any action.
