### ISSUE TITLE
Empty environment variable value replaced by 0 via time command (4621)

### ISSUE THREAD

**Issue by ko1nksm** [rmyorston/busybox-w32#250]
The value of the environment variable is replaced by 0 if it is empty.

```console
$ V='' sh -c 'echo {$V}'
{}

$ V='' time sh -c 'echo {$V}'
{0}
```

**Comment by rmyorston** [comment]
This issue should be fixed in the latest [prerelease](https://frippery.org/files/busybox/prerelease) binaries.

**Comment by ko1nksm** [comment]
It seems that empty environment variables are now removed.

```sh
# busybox-w64-FRP-4621-gf3c5e8bc3.exe
$ VAR='' sh -c 'env | grep VAR'
VAR=

# busybox-w64-PRE-4645-g386fd4d71.exe
$ VAR='' sh -c 'env | grep VAR'
```

**Comment by rmyorston** [comment]
OK, let's try again. Here's the script I've used for testing:
```sh
#!/bin/sh

echo
echo === Case 1
printf "want 'V=set' got '%s'\n"   $(V=set env sh -c 'env | grep ^V=')
printf "want 'V='    got '%s'\n"   $(V= env sh -c 'env | grep ^V=')
printf "want ''      got '%s'\n"   $(env sh -c 'env | grep ^V=')
echo
echo === Case 2
printf "want 'V=set' got '%s'\n"   $(V=set sh -c 'env | grep ^V=')
printf "want 'V='    got '%s'\n"   $(V= sh -c 'env | grep ^V=')
printf "want ''      got '%s'\n"   $(sh -c 'env | grep ^V=')
echo
echo === Case 3
printf "want 'set'   got '%s'\n"   $(V=set env sh -c 'echo ${V-unset}')
printf "want ''      got '%s'\n"   $(V= env sh -c 'echo ${V-unset}')
printf "want 'unset' got '%s'\n"   $(env sh -c 'echo ${V-unset}')
echo
echo === Case 4
printf "want 'set'   got '%s'\n"   $(V=set sh -c 'echo ${V-unset}')
printf "want ''      got '%s'\n"   $(V= sh -c 'echo ${V-unset}')
printf "want 'unset' got '%s'\n"   $(sh -c 'echo ${V-unset}')
```
The main thing of interest is when the environment variable is empty: ```V=```:
- the previous release, FRP-4487, works correctly in all cases;
- the current release, FRP-4621 fails in cases 1 and 3;
- the previous prerelease, PRE-4645, fails in case 1 and 2;
- the current prerelease, PRE-4646 works in all cases.

It's possible a build for UCRT won't work properly, but at present I only make binaries for MSVCRT.

**Comment by ko1nksm** [comment]
Thanks for the quick fix! I tested with PRE-4646. It seems to work fine.
