### ISSUE TITLE
Symlinks, hardlinks and junctions

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#251]
1) Symlinks do works but require admin rights (nothing can be done for this).

2) Hardlinks of files do work, hardlinks of folders aren't allowed.
On Live busybox it return: `ln: ./folder_name: Operation not permitted`
On Windows it return `ln: ./folder_name: Permission denied`
If possible it would be nice to have the same error.

3) So the only thing left for folders without admin rights is junction.
Is it possible to add a parameter like `-j` to `ln` to make directory junctions (it should fail for files)?

**Comment by ale5000-git** [comment]
I have also tried this: `cmd.exe /C "mklink /J "${1}" "${1}""`
but trying to quote it correctly from inside a shell script is madness.

**Comment by rmyorston** [comment]
Of course, I don't know _exactly_ what you're trying to do, but do you need the outer quotes?

**Comment by ale5000-git** [comment]
`mklink` can create junctions/symlinks/hardlinks but it isn't a standalone executable so it only works inside cmd.exe
`/C` parameter of cmd.exe make it execute a command and exit.

While cmd.exe is pretty lenient and probably works also without it, I think it is safer with quote since it is a command run from the `/C` parameter.

**Comment by ale5000-git** [comment]
Even without the outer quotes it doesn't work:
```
create_junction()
{
  cmd.exe /C mklink /J "${1:?}" "${2:?}"
}
```

If the folder have spaces it consider it a different parameter.

**Comment by rmyorston** [comment]
Never mind the additional complication of running ```mklink``` from a shell function: are there _any_ circumstances in which a command being run via ```cmd /c``` can have arguments containing whitespace?

**Comment by ale5000-git** [comment]
In the command `cmd.exe /C mklink /J "${1:?}" "${2:?}"`
technically all this `mklink /J "${1:?}" "${2:?}"` is the argument of /C, but as said cmd.exe is lenient so I will just skip outer quotes.
There is also /K but it is alternative of /C so it isn't usually a problem.

But quote for "${1:?}" and "${2:?}" are stricly needed since on Windows most paths have spaces, like for example C:\Program Files (x86), so all commands that use paths should be quoted.

**Comment by ale5000-git** [comment]
I didn't make any change, you can see it with: `cmd /s /c echo mklink /j "aa" "bb"`

**Comment by rmyorston** [comment]
We don't want to _see_ the quotes, we want them to allow whitespace in arguments.
```
~ $ create_junction() {
>     cmd /s /c mklink /j "${1:?}" "${2:?}"
> }
~ $ mkdir -p "hello world/dir"
~ $ create_junction "hello world/dir_junction" "hello world/dir"
Junction created for hello world/dir_junction <<===>> hello world/dir
~ $ ls "hello world"
dir           dir_junction
~ $

```

**Comment by ale5000-git** [comment]
Strangely your sample works but my code no, see:
```
~ $ mkdir -p "${TEMP}/MYTEMP-a02984/MYFOLDER"
~ $ cmd /s /c mklink /j "${TEMP}/MYTEMP-a02984/MYJUNCTION" "${TEMP}/MYTEMP-a02984/MYFOLDER"
Invalid option - "Users".
~ $
```

Strangely I have the issues even without sapces in the folder name.

**Comment by rmyorston** [comment]
Ah yes, forward slashes are used to introduce options in Windows. I guess the space in my example prevented ```mklink``` from seeing the first forward slash as an option.

BusyBox ash supports pattern substitution in variables (a bashism) so we can do this:
```
~ $ create_junction() {
>     cmd /s /c mklink /j "${1//\//\\}" "${2//\//\\}"
> }
~ $ mkdir -p a/dir
~ $ create_junction c:/Users/rmy/a/dir_junction a/dir
Junction created for c:\Users\rmy\a\dir_junction <<===>> a\dir
~ $
```

**Comment by rmyorston** [comment]
I decided it was easier to make a new applet than to add an option to ```ln```. With the latest [prerelease](https://frippery.org/files/busybox/prerelease) you can do ```jn dir junction```, where ```dir``` must be an existing directory and ```junction``` must not exist.

**Comment by ale5000-git** [comment]
Unfortunately I got some issues, the junctiont was created and visible from `ls -la` but it cannot be opened from explorer.

Just tried:
```
C:/$mkdir a
C:/$jn a b
```

**Comment by rmyorston** [comment]
The old 'off-by-one' problem: ```MultiByteToWideChar()``` includes the terminating NUL in its return value so my string lengths were wrong. Should be fixed in the latest prerelease.
