### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#252]
I have always though BusyBox was GPL-2.0-only, but [here](https://github.com/rmyorston/busybox-w32/blob/master/libbb/appletlib.c#L12) I see `Licensed under GPLv2 or later`.

Could you please change the message when your run busybox from "Licensed under GPLv2" to "Licensed under GPLv2 only" or "Licensed under GPLv2 or later" to clarify what is the right license?

**Comment by rmyorston** [comment]
The upstream page about [licensing](https://busybox.net/license.html) says:
>Even though BusyBox code, as a whole, can only be used under GPL version 2, some individual files may have more permissive licenses: "GPL version 2 or later" — meaning that you can also reuse the code from this source file for a project which is distributed under GPLv3, and "Public domain" - the code in these files have no licensing restrictions whatsoever.

Any individual file should be _compatible_ with GPLv2 but the actual terms may be different.

**Comment by ale5000-git** [comment]
Ok thanks.
