### ISSUE TITLE
env -i

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#253]
After this:
```
exec env -i busybox ash
set
```

On BusyBox for Windows I get:
```
BB_GLOBBING='0'
FUNCNAME=''
HOSTNAME='PC NAME'
IFS='
'
LINENO=''
OLDPWD='C:/my-test-folder'
OPTIND='1'
PATH='/sbin;/usr/sbin;/bin;/usr/bin'
PPID='1'
PS1='\w \$ '
PS2='> '
PS4='+ '
PWD='C:/my-test-folder'
SHLVL='1'
```

On BusyBox Live I get:
```
IFS='
'
OPTIND='1'
PATH='/sbin:/usr/sbin:/bin:/usr/bin'
PPID='1' 
PS1='\w \$ '
PS2='> ' 
PS4='+ ' 
PWD='/'
```

The additional variables (specially BB_GLOBBING, FUNCNAME and OLDPWD) on Windows are strictly necessary?

This: PATH='/sbin;/usr/sbin;/bin;/usr/bin'
doesn't seems correct on Windows.

**Comment by rmyorston** [comment]
```set``` is a shell builtin which prints _shell_ variables. In your tests the shell is being run with an empty environment, it sets some _shell_ variables and ```set``` prints them.

If you want to see whether ```env -i``` is clearing _environment_ variables you need to run something like ```env -i env``` or ```env -i printenv```. Doing that on Windows I get:
```
~ $ env -i printenv
BB_GLOBBING=0
~ $
```
The environment variable ```BB_GLOBBING``` is set by busybox-w32 on start up to indicate that Windows globbing shouldn't be applied to arguments in future. It's mentioned in the **Wildcards** section of the release notes for [FRP-3532](https://frippery.org/busybox/release-notes/FRP-3532.html). So, ```printenv``` _is_ being run with an empty environment to which ```BB_GLOBBING``` is added during start up.

The shell also seems to export a few things to the environment:
```
~ $ env -i sh
~ $ printenv
SHLVL=1
OLDPWD=C:/Users/rmy
BB_GLOBBING=0
PWD=C:/Users/rmy
~ $
```

**Comment by ale5000-git** [comment]
I use it inside a shell script to reset everything like this:
```
if ! "${ENV_RESETTED:-false}"; then
  THIS_SCRIPT="$(realpath "${0}" 2>&-)" || exit 1
  exec env -i ENV_RESETTED=true THIS_SCRIPT="${THIS_SCRIPT}" PATH="${PATH}" ash "${THIS_SCRIPT}" "$@" || exit 1
fi
```

FUNCNAME and OLDPWD don't seems to be set in Live BusyBox and neither in Bash online.

**Comment by rmyorston** [comment]
I added the following to the start of your script extract:
```
#!/bin/sh
printenv
echo ---
```
When I run the resulting script in busybox-w32 ash it prints the original environment followed by this from the second shell:
```
SHLVL=1
ENV_RESETTED=true
PATH=C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/ 
BB_GLOBBING=0           
PWD=C:/Users/rmy
THIS_SCRIPT=C:/Users/rmy/scripto
---                             
~ $
```
There's no ```FUNCNAME``` and no ```OLDPWD```.

If I replace ```ash``` with ```bash``` and run the script on Linux I get:
```
PWD=/home/rmyf35
THIS_SCRIPT=/home/rmyf35/scripto
ENV_RESETTED=true
SHLVL=1
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rmyf35/.local/bin:/home/rmyf35/bin
_=/usr/bin/printenv
---
~ $
```
Apart from ```BB_GLOBBING``` in one and ```_``` in the other these are pretty much equivalent.

**Comment by rmyorston** [comment]
```OLDPWD``` is no longer set when ```env -i sh``` is run. I've also fixed a problem with ```cd``` and symlinks.

Both of these date back three years to issues #147 and #148.

**Comment by ale5000-git** [comment]
I was confused by the fact that I was using env -i with exec and it effectively reset both environment variables and shell variables when used in this way but you are right.

The only remaing question is this: env -i ash -c 'echo $PATH' that return `/sbin;/usr/sbin;/bin;/usr/bin`
I think this would be the best hardocded replacement `C:/Windows/system32;C:/Windows`, it could cover most cases.

**Comment by rmyorston** [comment]
Yes, it's probably not worth going beyond a simple hardcoded string. Try the latest prerelease.

**Comment by ale5000-git** [comment]
It works perfectly, thanks.
