### ISSUE TITLE
export error bugged handling

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#255]
If I insert an invalid command like this:
`export @@@@@@@@@@@@@@@@@`
it should follow the set -/+e.

Instead inside script it stop it whatever set -e was specified or not.
Instead in an interactive shell it doesn't stop even if set -e is specified.

The same happens for:
`export -f name`
that isn't supported.

**Comment by rmyorston** [comment]
>Instead inside script it stop it whatever set -e was specified or not.
Instead in an interactive shell it doesn't stop even if set -e is specified.

This is the behaviour I see for all shells derived from ash: BusyBox ash, dash and {Free,Net}BSD sh. The Korn shell also does this.

zsh and the original Bourne shell in UNIX v7 always exit from a script but do respect the ```errexit``` setting in an interactive shell.

The only shell I've tried that follows ```errexit``` in all cases is bash.

**Comment by ale5000-git** [comment]
I was trying to use:
`export -f -- "${1:?}" 2>/dev/null || true`
in a way it will get executed only on shells supporting it and still continuing without where it isn't supported.

So isn't there any standard way to go on?

**Comment by ale5000-git** [comment]
Thanks, I have found a way to make it being ignored:

```
#!/bin/sh

set -eo pipefail

func_1()
{
  :
}

my_export()
{
  export -f func_1 2>/dev/null
}

my_export | cat || true

echo 'Good'
```
