### ISSUE TITLE
How detect when read -t1 timeout?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#257]
From bash manual of read:
`The exit status is greater than 128 if the timeout is exceeded`

Test on bash online result in 142.
Test on Busybox result in 1.

How detect when read -t1 timeout?
Is there a manual of busybox read (including all return values and supported parameters)?

**Comment by rmyorston** [comment]
>How detect when read -t1 timeout?

If you need to distinguish between a timeout and some other failure there isn't a portable way to do that. BusyBox ash, Korn shell and zsh all return 1 on timeout.

>Is there a manual of busybox read

No, shell builtins don't support a ```--help``` option like BusyBox applets. There's a comment in the source:
```
/*
 * The read builtin. Options:
 *      -r              Do not interpret '\' specially
 *      -s              Turn off echo (tty only)
 *      -n NCHARS       Read NCHARS max
 *      -p PROMPT       Display PROMPT on stderr (if input is from tty)
 *      -t SECONDS      Timeout after SECONDS (tty or pipe only)
 *      -u FD           Read from given FD instead of fd 0
 *      -d DELIM        End on DELIM char, not newline
 * This uses unbuffered input, which may be avoidable in some cases.
 * TODO: bash also has:
 *      -a ARRAY        Read into array[0],[1],etc
 *      -e              Use line editing (tty only)
 */
```

**Comment by ale5000-git** [comment]
Ok thanks.
