### ISSUE TITLE
The behaviour with junctions and cd is a bit strange

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#259]
Cookies is a presetted Windows junction.

See this example:
~ $ cd Cookies
~/AppData/Local/Microsoft/Windows/INetCookies $ cd ..
~ $

`..` no longer point to upper folder.

**Comment by rmyorston** [comment]
This is a known problem with symlinks (and now junctions). We keep coming back to issue #147: specifically in this case [this comment](https://github.com/rmyorston/busybox-w32/issues/147#issuecomment-478524563).

The shell and the line editing code have different ideas about the current directory. Also, the current directory needs to be canonicalised or ```ls``` gets confused. Plus, upstream BusyBox has exactly the same behaviour so any fix will probably need to go there too.

I'll see what I can do.

**Comment by ale5000-git** [comment]
There is also another issue (I'm not sure if is related):
```
~ $ cd Cookies
~/AppData/Roaming/Microsoft/Windows/Cookies $ cd ..
~ $ ls *

...

Cookies:
ls: can't open 'Cookies': Permission denied

...
```

How you can see the junction is accessible by `cd Cookies` but not accessible by `ls *` (the same for all other junctions).

**Comment by ale5000-git** [comment]
I have found it online [here](https://rakhesh.com/windows/start-menu-and-other-directory-junctions-access-denied/):

> The important thing with both directory junctions and soft links is that they can have their own ACLs. So while a user might have full permissions to the target folder, the directory junction or soft link itself may not grant the user permissions and so the contents cannot be accessed via the directory junction or soft link. That’s what happening here too.

> Compare the ACLs of the target and directory junction and we see the problem:
> 
> icacls "Start Menu"
> Start Menu Everyone:(DENY)(S,RD)
>            NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
>            BUILTIN\Administrators:(I)(OI)(CI)(F)
>            CAIN\Rakhesh:(I)(OI)(CI)(F)
> 
> icacls "c:\Users\Rakhesh\AppData\Roaming\Microsoft\Windows\Start Menu"
> c:\Users\Rakhesh\AppData\Roaming\Microsoft\Windows\Start Menu NT AUTHORITY\SYSTEM:(OI)(CI)(F)
>                                                               BUILTIN\Administrators:(OI)(CI)(F)
>                                                               CAIN\Rakhesh:(OI)(CI)(F)
> 
> (I could have used the Explorer GUI here but I prefer icacls. In the GUI we have to dig down a bit more to see the relevant ACEs).
> 
> Notice a DENY entry for Everyone on the directory junction for listing the contents (RD).

**Comment by rmyorston** [comment]
Right, ACLs. I don't suppose there's much we can do about that.

Back to the original issue. It looks quite straightforward to get the shell and the line editing code to agree on the current directory. However it requires the upstream patch I submitted for issue #244 and that hasn't been accepted yet. I don't want to carry these patches in busybox-w32 so the fix for this will need to wait.

**Comment by rmyorston** [comment]
My patches have been applied upstream and busybox-w32 now includes them. The most recent [prerelease](https://frippery.org/files/busybox/prerelease) binaries should fix this issue.

**Comment by ale5000-git** [comment]
Thanks, currently I'm a bit busy but I will test it as soon as possible.

**Comment by ale5000-git** [comment]
It works perfectly, thanks :)
