### ISSUE TITLE
CGI capable ?

### ISSUE THREAD

**Issue by vertikalm** [rmyorston/busybox-w32#262]
Hi. Thanks for your work.
I use the cgi feature from 'httpd' busybox module  frequently under *nix.
This is really implemented in your windows binary? Apparently your source code have cgi features.
I must take care with anything?
My cgi-binaries are the same in both platforms. Compiled in 32 and 64. Also tryed busybox w32/w64.

**Comment by rmyorston** [comment]
No, CGI isn't in the busybox-w32 binary. The source code is present but it's turned off at build-time because it needs support for ```vfork(2)```.

**Comment by rmyorston** [comment]
FYI, the latest [prerelease](https://frippery.org/files/busybox/prerelease) binaries (PRE-5245 and above) have support for CGI enabled.

**Comment by vertikalm** [comment]
Oh, great news.
Thank you very much for this improvement, and for your reminder.
