### ISSUE TITLE
Should tar extract as much as possible despite errors?

### ISSUE THREAD

**Issue by lunakid** [rmyorston/busybox-w32#265]
In some quick tests, after properly extracting a bunch of files, while also having a few permission denied errors (e.g. creating symlinks), `tar x` seems to stop prematurely, skipping some remaining non-problematic items. (It's not immediately obvious why it extracted some, but not those remaining others.)

If there was only one error per run, I'd guess it just aborted on the first one, but it does seem to continue after several (which also feels like the correct behavior).

**Comment by rmyorston** [comment]
In general, how ```tar``` handles errors is determined by upstream BusyBox. As a special case busybox-w32 treats failure to create a symlink as a non-fatal error. That seemed the pragmatic thing to do.

If you can provide a specific example I might be able to explain the behaviour you're seeing. Whether we can then go on to improve the behaviour of ```tar``` would depend on the details of the case.

**Comment by lunakid** [comment]
This simple test archive [bb.tar.gz](https://github.com/rmyorston/busybox-w32/files/9439454/bb.tar.gz) has no symlinks, but a copy of `busybox.exe` to trigger the permission error by doing the untar with a local `busybox.exe` in the same dir, so  

  `busybox tar xf bb.tar` _(I gunzipped it first in a separate step)_

will be unable to unpack the .exe onto itself. 
It does extract the HTML file OK though, but not f1 and f2 from the archive.

HTH.

**Comment by lunakid** [comment]
This simple test archive [bb.tar.gz](https://github.com/rmyorston/busybox-w32/files/9439454/bb.tar.gz) has no symlinks, but a copy of `busybox.exe` to trigger the permission error by doing the untar with a local `busybox.exe` in the same dir, so  

  `busybox tar xf bb.tar` _(I gunzipped it first in a separate step)_

will be unable to unpack the .exe onto itself. 
It does extract the HTML file OK though, but not f1 and f2 from the archive.

HTH.

**Comment by lunakid** [comment]
Cleaned up my comment above to make the point clear: the non-fatal (permission denied, and possibly other, if any) errors should _not_ give the same error message as the fatal ones, to avoid the false appearance inconsistent extracting behavior. 

Can the non-fatal ones e.g. have some tag (like "; continuing...")?

**Comment by rmyorston** [comment]
To answer the original question: it would be nice if upstream BusyBox did match the behaviour of GNU tar. However, I can see why they've done it the way they have. Allowing processing to continue after errors would undoubtedly require more code.

Anyway, I've taken a slightly different approach to the problem at hand. The latest [prerelease](https://frippery.org/files/busybox/prerelease) binaries _appear_ to treat failure to create symlinks as a fatal error. In fact, though, they continue to try to extract as much as possible.

I hope this will reduce the apparent inconsistency while still being convenient for users who lack the necessary privilege to create symlinks.

**Comment by rmyorston** [comment]
The changes are in the latest release.
