### ISSUE TITLE
Allow custom override of builtin applets

### ISSUE THREAD

**Issue by avih** [rmyorston/busybox-w32#271]
Sometimes a user has some binaries they prefer over the builtin applets. This can be external `less` with more features, or (gnu) `make`, or `vi`, etc.

However, currently, even if such binaries are at the PATH, the builtin applets still take priority when invoked "normaly", unless the external utilities are invoked e.g. like `less.exe` or `path/to/less` etc.

I know busybox can be configured to search PATH first (I haven't tried it), however, for busybox-w32 it's also not necessarily ideal, as some commands could be strictly windows binaries - but the user prefers the unix-y applets.

So this issue is about choosing some method to allow overriding of some applets from PATH, and I think it would be useful to set it up from CLI while launching busybox.

Some ideas I had:
- Use an env var, e.g. BB_PATH which is like PATH but searched before applets.
- Use some marker at PATH, e.g. `@` so that all paths before it are searched before applets, e.g. `PATH="c:/mybins;@;$PATH"`
- Use an env var, or CLI option, which specifies which applets should not override PATH, e.g. `busybox --prefer-path=less,make,vi sh -l` or the same list in some env var like `BB_PREFER_PATH=less,make,vi` (or both - the option sets the var, and the var can be changed also later).
- Choose something much simpler and more robust which I didn't think of ;)

**Comment by ale5000-git** [comment]
There is already: `BB_OVERRIDE_APPLETS`.
More info here: https://frippery.org/busybox/release-notes/FRP-4716.html

**Comment by avih** [comment]
> There is already: `BB_OVERRIDE_APPLETS`.

Nice, thanks. That sounds quite close to my suggestion of BB_PREFER_PATH, though it's not trivial to set it up from a windows shortcut (because it's not easy to setup env vars specific for a windows shortcut).

Maybe support for a cli option --override-applets can be added, which sets this var if it's not set?

Is there some unified documentation of all the busybox-w32 "special features"? like all the BB_* vars, sh `-d` option (start in a dir), and possibly others?

**Comment by ale5000-git** [comment]
To run a script:
`busybox.exe ash -c "export BB_OVERRIDE_APPLETS='make'; ./my_script.sh"`.

To run a shell that remains open:
`busybox.exe ash -s -c "export BB_OVERRIDE_APPLETS='make'"`

**Comment by avih** [comment]
> To run a script: `busybox.exe ash -c "export BB_OVERRIDE_APPLETS='make'; ./my_script.sh"`
> 
> To run a shell that remains open: `busybox.exe ash -s -c "export BB_OVERRIDE_APPLETS='make'"`

Sure, or even simpler `busybox.exe sh -c "BB_OVERRIDE_APPLETS=make ./my_script.sh"` etc, however, it's not easy to setup for a login shell like this without ending up with two shells, and also, setting up quotes inside quotes (e.g. if BB_OVERRIDE_APPLETS needs to override more than one applet with space between them) can be painful in cmd.exe and windows shortcuts.

**Comment by ale5000-git** [comment]
You can also use batch files like I'm doing:
https://github.com/micro5k/microg-unofficial-installer/blob/main/build.bat
https://github.com/micro5k/microg-unofficial-installer/blob/main/cmdline.bat

**Comment by avih** [comment]
> You can also use batch files like I'm doing:

Using a barch has other issues, like interpreting ^C and asking whether to terminate the batch etc.

**Comment by ale5000-git** [comment]
I can't help you without knowing the real use case, otherwise it is just a guessing game :)

**Comment by avih** [comment]
As stated at the first message: a way to custom override of some applets, preferably with a way to set it up via a shortcut, e.g. to a login shell (and not ending up running from a batch file or with two shells).

**Comment by ale5000-git** [comment]
Instead of executing the script you can source it and it will avoid having two shells.

**Comment by avih** [comment]
> Instead of executing the script you can source it and it will avoid having two shells.

Just show me how to create a shortcut which starts a login shell with BB_OVERRIDE_APPLETS="make less"

**Comment by rmyorston** [comment]
>Just show me how to create a shortcut which starts a login shell with BB_OVERRIDE_APPLETS="make less"

To override one applet in a shortcut:
```
   C:\path\to\busybox.exe sh -l -s -c "export BB_OVERRIDE_APPLETS=make"
```
More than one, dunno. Maybe comma separators are a good idea.

**Comment by avih** [comment]
> More than one, dunno. Maybe comma separators are a good idea.

Indeed, but this is a specific solution for this specific problem.

My suggestion was generic, which makes it simpler to setup any number of env vars, one at a time, without running a shell line and stumbling over shell quoting inside windows commands quoting.

With my suggestion, it could have been, for instance:
```sh
busybox "--env=BB_OVERRIDE_APPLETS=make less" sh -l
```

Some values could still be complex to enter, but also guaranteed to be simpler to enter compared to a posix shell line as a windows command argument.

**Comment by avih** [comment]
Anyway, I'm closing this issue because BB_OVERRIDE_APPLETS does generally answer the question and allow such overrides.

However, my question about a central place which documents the special controls of busybox-w32 remains.

I'm aware of `sh -d` and BB_SKIP_ANSI_EMULATION, and now also of BB_OVERRIDE_APPLETS.

Courtesy search for `"BB_` finds the following which can be relevant to this -w32 version: BB_FIX_BACKSLASH, BB_SYSTEMROOT, BB_GLOBBING (less than I thought there would be).

And there could be more env vars or special options which are not used at upstream busybox and may be useful to end users (i.e. not strictly debugging features).

It would be nice to have these extras documented in one place.

**Comment by rmyorston** [comment]
Or single quotes! Like @ale5000-git said!
```
C:\path\to\busybox.exe sh -l -s -c "export BB_OVERRIDE_APPLETS='make less'"
```

**Comment by avih** [comment]
> > I'm aware of sh -d
> 
> Ssssh! Don't tell everyone

I actually find this one quite useful.

As for the others, yes, it's possible to use a shell line for those, though I didn't consider that `-s` can be used together with `-c` and `-l`, and so my attempts with -c always ended with two shells, like with `busybox sh -c "VAR=VAL sh -l'`, and sh -l -c didn't work as I hoped without -s.

So -s indeed makes it possible to set up arbitrary vars in a login shell. I definitely can imagine values which would be harder to specify at a shell line inside windows argument compared to just the value as an argument, though probably still possible also as a shell line.

As for the docs, are there others you consider useful beyond the ones mentioned above?

**Comment by rmyorston** [comment]
```-d``` may be useful but it's totally non-portable. I think it's unique to busybox-w32 ash.

```-s``` isn't all that portable either. Upstream BusyBox changed the behaviour of ```-s``` to match bash in commit f3634584d. I changed it back to match dash in busybox-w32 commit 6a7524634e.

I can't think of any other useful documentation.

**Comment by avih** [comment]
For future reference, since `BB_OVERRIDE_APPLETS` seem to effectively disable these applets (even if the name doesn't exist outside of busybox), here's my take on prefering external over applets, but still use the applet if it's not avilable externally, for instance, to be placed at `~/.profile`:
```sh
BB_PREFER_EXTERNAL="ar make less strings vi xxd"

# apply BB_PREFER_EXTERNAL: disable applets if they exist externally.
# note: applets stay disabled even if their availability changes later.
[ -z "${BB_PREFER_EXTERNAL-}" ] || [ "${BB_OVERRIDE_APPLETS+x}" ] \
|| export BB_OVERRIDE_APPLETS="$(
    for x in $BB_PREFER_EXTERNAL; do
        export "BB_OVERRIDE_APPLETS=$x"
        command -v "$x" >/dev/null && printf "%s " "$x"
    done
)"
```

**Comment by ale5000-git** [comment]
@avih
If you need to do it only for few cases it is simple to do it like this:

```
#!/usr/bin/env sh

# Helper to prefer external commands
pech()
{
  local _command_path=''

  _command_path="$(env which "${1:?}")" || _command_path="$(command -v "${1:?}")" || return 1
  shift
  "${_command_path:?}" "${@}"
}

pech ls -la
```
