### ISSUE TITLE
getopt -n option is ignored

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#274]
Hi,
this:
`getopt -o '' -l opt1,opt2 -n 'my_script' -- "--opt3"`
should result in:
`my_script: unrecognized option '--opt3'`
but instead it result in:
`getopt: unknown option -- opt3`

The program name isn't respected, and also the message is different.

**Comment by rmyorston** [comment]
The BSD manpage for ```getopt(1)``` offers this wisdom:
```
BUGS
      Whatever getopt(3) has.
```
That's the case here. ```getopt(3)``` in Mingw-w64 is different from ```getopt(3)``` in glibc.

The issue with the program name has been fixed. The format of the message hasn't.

**Comment by ale5000-git** [comment]
This:
`getopt -n 'my_script' -o 'l' -- '-ls'`
result in this:
```
 -lmy_script: unknown option -- s
 --
```
instead of:
```
my_script: invalid option -- 's'
 -l --
```

**Comment by rmyorston** [comment]
Yes, output on stdout and stderr is being interleaved.
