### ISSUE TITLE
busybox64 change broke previously working makefiles, starting point for bisect provided

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#286]
# Problem

Building `containerd`'s Makefile invoked from a newer version of Busybox is broken.

This works correctly on BusyBox v1.34.0-FRP-3902-g61e53aa93 (2021-03-02 15:10:05 GMT)

# Reproduction

Prerequisites:
 - busybox64.exe from https://frippery.org/files/busybox/busybox64.exe
 - GNU make, git, golang (`choco install -y make git.portable golang`)

Then, execute this script:
```
git clone https://github.com/containerd/containerd.git
cd containerd
git checkout fed7df1e258461d0a6ffa04d0224a33b34ae4ad3
CGO_ENABLED=0 make binaries
```

Expect the binaries to build. Instead, you see this error:
```
makefile:38: expected separator
```

for reference, here is line 38 from that Makefile:
```
ifneq "$(strip $(shell command -v $(GO) 2>/dev/null))" ""
```

# Suggested bisect:

**Known bad version:**
```
BusyBox v1.36.0-FRP-4784-g5507c8744 (2022-11-09 08:26:33 GMT)
(mingw64-gcc 11.2.1-5.fc36; mingw64-crt 9.0.0-4.fc36; glob)
```

**Known good version:**
```
BusyBox v1.34.0-FRP-3902-g61e53aa93 (2021-03-02 15:10:05 GMT)
(mingw64-gcc 10.2.1-2.fc33; mingw64-crt 7.0.0-2.fc33; glob)
```

**Comment by rmyorston** [comment]
The FRP-4784-g5507c8744 release includes a new `make` applet. This will be run in preference to any external `make` program.

You can override the preference for the internal `make` by setting a variable in the shell:
```
export BB_OVERRIDE_APPLETS="make"
```

**Comment by doctorpangloss** [comment]
Is it realistic to improve the conformance of the make applet? What would the next step be?

If not I will close the issue and probably build with the applet disabled.

**Comment by rmyorston** [comment]
The `make` applet is based on my [public domain POSIX make](https://frippery.org/make/). As the name suggests its aim is to be POSIX compliant. The current POSIX standard for `make` is rather weak but the up-coming revision will result in a rather more useful utility.

`pdpmake` has a number of extensions modelled on features in GNU `make`, but I don't have any particular plan to add more.

**Comment by ale5000-git** [comment]
@doctorpangloss
Alternatively you could also ask containerd to change Makefile to be POSIX compliant.

**Comment by doctorpangloss** [comment]
this is now resolved on the latest busybox64.exe since the applet was renamed `pdpmake`

**Comment by doctorpangloss** [comment]
In the latest prerelease, `make` is still pointing to the applet

**Comment by ale5000-git** [comment]
The point is that there is `pdpmake` and `make`, so you can disable with` export BB_OVERRIDE_APPLETS="make"` and you will still be able to use it with `pdpmake`.

**Comment by rmyorston** [comment]
The default build of busybox-w32 includes the `make` applet with the name `make` and the alias `pdpmake`.

Possible ways to use a third-party `make`:
- `export BB_OVERRIDE_APPLETS="make"`
- `alias make="/path/to/make.exe"`
- Build a custom executable with `make` disabled. This is what [w64devkit](https://github.com/skeeto/w64devkit) does.
