### ISSUE TITLE
SHLVL issues

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#302]
I have tried this code on [Bash Online](https://replit.com/languages/bash):
`busybox sh -c 'echo $SHLVL; exec sh -c "echo \$SHLVL"'`
and I get:
```
2
2
```

Instead on BusyBox for Windows I get:
```
2
3
```

Is it a bug?

**Comment by rmyorston** [comment]
>Is it a bug?

Maybe. Maybe not.

I don't know what Bash Online is doing, but on my Linux machine I get:
```
[rmy@random ~]$ busybox sh -c 'echo $SHLVL; exec sh -c "echo \$SHLVL"'
2
3
```
You need to be careful when testing this:
- `SHLVL` isn't specified in POSIX and it isn't available in all shells.
- If a shell doesn't support `SHLVL` and you run it from a shell that does the variable will be inherited but never changed.
- In the example above the first `sh` is definitely the BusyBox shell. The second? It depends.

**Comment by ale5000-git** [comment]
So it is an upstream issue, thanks for the help.

**Comment by rmyorston** [comment]
I've had a look at what would be required to make BusyBox `ash` work like `bash`.

Decrementing `SHLVL` in `exec` is simple enough. The difficult part is not decrementing it if we're in a subshell. `bash` tracks whether it's in a subshell; BusyBox `ash` doesn't and I don't immediately see an easy way to replicate what `bash` does. I'll leave it at that for now.

I've noticed some unrelated issues with subshells in busybox-w32 which I'll investigate further.

**Comment by ale5000-git** [comment]
The upstream ticket is here => https://bugs.busybox.net/show_bug.cgi?id=16141
