### ISSUE TITLE
trap INT doesn't work

### ISSUE THREAD

**Issue by ildar-shaimordanov** [rmyorston/busybox-w32#303]
It seems that INT trapping doesn't work on Windows. It takes place on both Win10 and Win11 with both 32- and 64-bit versions of BusyBox.

```
>busybox.exe sh -i
~/Downloads $ ctrl_c() { uname -srvmo ; }
~/Downloads $ trap ctrl_c INT
~/Downloads $ ^C
~/Downloads $
~/Downloads $ ctrl_c
Windows_NT 10.0 17763 i686 MS/Windows
~/Downloads $
~/Downloads $ busybox 2>&1 | head -1
BusyBox v1.37.0-FRP-4882-g6e0a6b7e5 (2023-02-15 21:58:52 GMT)
~/Downloads $
```

Check with Alpine Linux:

```
/ # ctrl_c() { uname -srvmo ; }
/ # trap ctrl_c INT
/ # ^CLinux 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 Linux
/ #
/ # ctrl_c
Linux 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 Linux
/ #
/ # busybox 2>&1 | head -1
BusyBox v1.35.0 (2022-07-18 12:23:02 UTC) multi-call binary.
/ #
```

Please advise and point me to the right way, if I missed something.

**Comment by rmyorston** [comment]
It's possible to register traps for the signals Windows knows about, but they don't currently do anything.

Only the ERR and EXIT traps work at the moment.

**Comment by rmyorston** [comment]
The [latest prerelease](https://frippery.org/files/busybox/prerelease) binaries include support for trapping the INT signal. They also have fake HUP and QUIT signals.

I've tried various shells (bash, ksh, zsh and upstream BusyBox ash) to see how they handle trapping INT. There are slight differences between them. busybox-w32 ash is no exception. It may not behave _exactly_ like your shell of choice.

**Comment by ale5000-git** [comment]
I just found this:
> You can use this trap to reset trap set earlier:
> trap '' ERR
> 
> help trap says use '' to ignore, - to reset to default behaviour.

Is it supported?

**Comment by rmyorston** [comment]
>Is it supported?

Yes. Both `trap - whatever` and `trap '' whatever` are supported.

**Comment by ildar-shaimordanov** [comment]
Confirm that. But `read` locks INT ending on CTRL+C and waits pressing ENTER.

Below is test script:

```shell
#!/bin/sh

check_it() { echo 'trapped'; }

trap check_it INT
sleep 100
read -r a
```

Expected action:
1. Run the script
2. Press CTRL+C twice
3. Return to the command prompt

Actual action:
1. Run the script
2. Press CTRL+C twice
3. Press ENTER
4. Return to the command prompt

**Comment by rmyorston** [comment]
On Linux with `/bin/sh` as an alias for bash the test script does indeed show the 'expected' action. If the first line is changed to `#!/bin/bash` we get the 'actual' action instead.

Anyway, try the latest [prerelease](https://frippery.org/files/busybox/prerelease). I'll go no further than to say it works 'differently'. In this context there's no saying what's 'expected' or 'correct'.

**Comment by ildar-shaimordanov** [comment]
It seems a bit crazy. Initially I checked it with bash in Cygwin and one of bash implementation in Linux. Couple hours I checked it with few shells on top of few OSes: bash, sh (with is a symlink) and dash. It works differently on different versions of bash and different distros. Let's leave it as it is to this moment. Thank you. It works.
