### ISSUE TITLE
time seems to search relative paths at $PATH

### ISSUE THREAD

**Issue by avih** [rmyorston/busybox-w32#310]
Test case:
```sh
$ # create ./foo/bar script which prints its $0
$ mkdir -p foo
$ printf %s\\n '#!/bin/sh' 'printf %s\\n "I am $0"' > foo/bar && chmod +x foo/bar
$ ./foo/bar
I am ./foo/bar
$ PATH= time ./bar  # as expected - ./bar doesn't exist - it's at ./foo/
time: can't execute ./bar: No such file or directory
$ PATH=$PWD/foo time ./bar  # should not work - ./bar is relative to $PWD
I am C:/tests/foo/./bar
real    0m 0.03s
user    0m 0.00s
sys     0m 0.01s
```

I don't know the scope of the issue, whether only `time` is affected, but it looks like that `time` concats relative application paths to elements of PATH even when the app path is relative.

As far as I can tell upstream busybox doesn't have this issue.

**Comment by rmyorston** [comment]
Yes, it's a bug in busybox-w32. It should be fixed in the [latest prerelease](https://frippery.org/files/busybox/prerelease).

**Comment by avih** [comment]
Confirmed fixed. Thanks.

(how do you prefer to close the issue? by me after confirmation? by you after $whatever?)

**Comment by rmyorston** [comment]
I prefer to leave issues open until a few weeks after the fix has appeared in a full release.

If there are any problems with the fix it's easier for people to find it that way.

**Comment by avih** [comment]
For what it's worth, in mpv we close issues immediately after a fix was pushed (typically automatically via the commit message itself, which contains "Fixes #WHATEVER"). If it turns out it was not fixed properly then we can always re-open or open a new one.

Anyway, sounds like you prefer to close it yourself, yes?

**Comment by rmyorston** [comment]
>Anyway, sounds like you prefer to close it yourself, yes?

Yes.

**Comment by ale5000-git** [comment]
@rmyorston
While you are at it, it would be nice if possible to add also: `/system/bin`

I'm working on shell scripts for Android and they only have 2 pathes for sh:
- `/sbin/sh`
- `/system/bin/sh`
and the first one is already supported.

**Comment by rmyorston** [comment]
I'm not convinced support for `/system/bin` is generally useful.

**Comment by ale5000-git** [comment]
I'm not sure of the generally usefulness, but I have asked just because the code is already here so the coding effort is probably minimal but it is your decision of what to do.
