### ISSUE TITLE
tr issue

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#312]
This is the correct way to mix parameters:
`echo "123   456eee789" | tr -d -s 'e' ' '`
but this instead should return an error as it do on Bash:
`echo "123   456eee789" | tr -s ' ' -d 'e'`

Or I'm wrong?

**Comment by avih** [comment]
> This is the correct way to mix parameters:
> `echo "123 456eee789" | tr -d -s 'e' ' '`

Yes. This deletes `e` and squeezes spaces.

> but this instead should return an error as it do on Bash:
> `echo "123 456eee789" | tr -s ' ' -d 'e'`

Bash doesn't have a `tr` builtin, so you end up using your system `tr`, which is probably gnu.

This string is interpreted as this (posix) form:
```
tr [-c|-C] [-s] string1 string2
```

Where string1 is space, and string2 is `-d`. so spaces are squeezed and then replaced with the respective char at string2 which is `-`. The extra char of string2 (`d`) is correctly ignored.

busybox `tr` also seems to ignore the excess argument[s?] after string2, in this case `e`, while gnu `tr` notices that this form doesn't have a use for that extra args, and errors.

I'm not seeing specific reference to extra unused arguments at the POSIX spec, but I think erroring on unused extra arg is the better behavior.

**Comment by rmyorston** [comment]
I've submitted an upstream patch to display the usage message if `tr` doesn't have exactly one or two non-option arguments.

**Comment by ale5000-git** [comment]
Thanks :)

**Comment by rmyorston** [comment]
Upstream have taken the patch. With the [latest prerelease](https://frippery.org/files/busybox.prerelease):
```
~ $ echo "123   456eee789" | tr -s ' ' -d 'e'
BusyBox v1.37.0-PRE-4973-g8cdeb571c (2023-04-17 07:35:55 BST)

Usage: tr [-cds] STRING1 [STRING2]

Translate, squeeze, or delete characters from stdin, writing to stdout

        -c      Take complement of STRING1
        -d      Delete input characters coded STRING1
        -s      Squeeze multiple output characters of STRING2 into one character
```
