### ISSUE TITLE
gsudo interacts incorrectly with shell utilities when running without symlinks

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#313]
# Reproduction

```
# in an administrative shell
choco install -y gsudo
```

```
touch C:/test.txt
sudo ln -s C:/test.txt C:/windows/test.txt
```

Observe `ln` is not a command `sudo` can find. While this is expected, it interacts poorly with day-to-day use of elevation from a logged in session of Windows. PS remote / OpenSSH users always run in administrative privileges so do not need to elevate.

# Possible Solutions

 - Add a `sudo` applet based on `gsudo` that elevates. This can be really small (like 3 real lines of code).
 - Add a directory to PATH for the executed process containing the links to the applets.

The same issue occurs with `runas` so this isn't specific to `gsudo`. That package is my preferred elevation tool.

**Comment by avih** [comment]
> Add a sudo applet based on gsudo that elevates. This can be really small (like 3 real lines of code).

busybox-w32 does have `su`, which can be used with similar effect.

> Add a directory to PATH for the executed process containing the links to the applets.

This is up to you. You can use `busybox --install` to add links to the applets, but it's up to you to add them to the path. Do note that some of those have he same name as windows commands, but with different semantics. So it's not something which busybox-w32 should do automatically whenever it executes a program.

Alternatively, you could always use `sudo busybox ln -s ...`.

**Comment by rmyorston** [comment]
`gsudo` has built-in knowledge of a few shells. It looks at the name of the binary to determine which shell is being used.

Fortunately, `bash` is one of the the shells it knows about. So if you rename `busybox.exe` to `bash.exe` and use that binary to start your shell `gsudo` will know what to do with it.

**Comment by doctorpangloss** [comment]
> So if you rename busybox.exe to bash.exe and use that binary to start your shell gsudo will know what to do with it.

I've been naming it `sh.exe` in order to not interfere with WSL2 `bash.exe`. I am going to open a ticket with gsudo.

**Comment by doctorpangloss** [comment]
> busybox-w32 does have `su`, which can be used with similar effect.

I experienced an issue with `su` that I ticketed here: https://github.com/rmyorston/busybox-w32/issues/314

> Do note that some of those have he same name as windows commands

That's why I don't want to do that.

**Comment by gerardog** [comment]
I think this one is fixed at https://github.com/gerardog/gsudo/issues/254#issuecomment-1522258937
Feel free to test it... I was looking for a test case on how to handle quotes...

**Comment by doctorpangloss** [comment]
Resolved!
