### ISSUE TITLE
jobs / fg / bg ?

### ISSUE THREAD

**Issue by mentalisttraceur** [rmyorston/busybox-w32#32]
I just noticed that although I can put jobs in the background, e.g.
```
$ sleep 10 && echo hi & # works as expected
```
..the commands for managing those background jobs seem missing:
```
~ $ jobs
ash: jobs: not found
~ $ fg
ash: fg: not found
~ $ bg
ash: bg: not found
```

**Comment by rmyorston** [comment]
Job control has been deliberately disabled.  It relies on far too many POSIX concepts to work as-is on Windows: pids, process groups, wait, signals, /dev/tty.

**Comment by mentalisttraceur** [comment]
Alright. That's what I was afraid of - we'd talked about signals before so I know that's not really a trivial task to fix, guess I was hoping maybe the shell had some other means besides signals to fall back on that I just didn't know about or something, but I guess that wouldn't really make sense.
