### ISSUE TITLE
sh, powershell and ubuntu.exe interact poorly to put the shell into a bad state

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#321]
This marks a return to the issues similar to `less`:

In busybox sh:
```
powershell
wsl --install Ubuntu
```
Observe you are prompted to specify a username:

```
~ $ powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\bberman> wsl --unregister ubuntu
Unregistering.
The operation completed successfully.
PS C:\Users\bberman> wsl --install ubuntu
Ubuntu is already installed.
Launching Ubuntu...
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:
```

At this point, hit Ctrl+C. The shell is now cursed similarly to the issue here: #306 .

**Comment by rmyorston** [comment]
I haven't been able to test this. I can't get WSL to work. However:
- I don't think it's necessary to run wsl from PowerShell. It should work from the busybox-w32 shell. That would avoid the problem, but isn't a solution.
- Did you test this with the release version of busybox-w32 (FRP-4882) or the prerelease that resolved the other issue (PRE-4922)? I think the prerelease should also fix this.

**Comment by doctorpangloss** [comment]
This is resolved in 5005.
