### ISSUE TITLE
(Question) Arrays in bash scripts?

### ISSUE THREAD

**Issue by DocMAX** [rmyorston/busybox-w32#326]
It seems busyboxs script "engine" does not support arrays like

```
var=( one two three )
for file in ${files[@]}
```

Am i right?
Can it be done?

**Comment by rmyorston** [comment]
The shell in busybox-w32 doesn't support arrays. Nor does `ash` in upstream BusyBox.

Arrays are one of the features of `bash` that BusyBox doesn't implement.

**Comment by DocMAX** [comment]
Thanks!

**Comment by avih** [comment]
Note that the main compliance target of ash in busybox is to be POSIX compliant.
See the specifications here https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html

Bash has many non standard (non POSIX) features, which one should avoid if they intend their script to be portable across different systems.

busybox ash does support some bash features (like local variables), but not arrays.
For what it's worth, the debian system shell - `dash` - also doesn't support arrays.

busybox `bash` and `sh` are simply an alias for `ash`, with exactly the same set of features.

**Comment by DocMAX** [comment]
With the available features in BusyBox, I was able to do away with arrays.

**Comment by ale5000-git** [comment]
@DocMAX
There is a POSIX-compliant implementation of arrays: https://github.com/krebs/array
