### ISSUE TITLE
`test -x` fails to follow some wierd kinds of links

### ISSUE THREAD

**Issue by OldWorldOrdr** [rmyorston/busybox-w32#327]
`test -x` fails when run on some links, even if the link points to an executable file, for example take this function from pfetch
```sh
has() {
    _cmd=$(command -v "$1") 2>/dev/null || return 1
    [ -x "$_cmd" ] || return 1
}
```
This fails to detect `winget` even if it is in $PATH, because the first version in $PATH is `C:\Users\Joey\AppData\Local\Microsoft\WindowsApps\winget.exe` which is a link to `C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.19.10173.0_x64__8wekyb3d8bbwe\winget.exe`

I'm not sure whats going on with this link, msys2 programs say it's a symlink, everything else says its not, it's not a symlink, not a hardlink, I don't know what it is.

**Comment by rmyorston** [comment]
The man page for `test` in GNU coreutils says:
```
       -f FILE
              FILE exists and is a regular file

       -x FILE
              FILE exists and the user has execute (or search) access
```
These are not equivalent.

Is there some specific problem this issue is intended to solve?

**Comment by OldWorldOrdr** [comment]
Windows does not have POSIX file permissions, so everything is executable, however when using this project `test -x` always fails

**Comment by rmyorston** [comment]
The weird links are reparse points with the tag `IO_REPARSE_TAG_APPEXECLINK`. Microsoft says they're:
>Used by Universal Windows Platform (UWP) packages to encode information that allows the application to be launched by CreateProcess.

But doesn't consider them important enough to document properly.

There's some useful information about them in this [StackOverflow thread](https://stackoverflow.com/questions/62474046).

I've added support for them in busybox-w32 `readlink(2)` and `lsattr(1)`, much as was done previously for junctions. They're treated as symbolic links, which is the closest thing in POSIX.

Try the [latest prerelease binary](https://frippery.org/files/busybox/prerelease).

**Comment by OldWorldOrdr** [comment]
latest prerelease fixed the issue
