### ISSUE TITLE
Add a way to hide "protected operating system files"

### ISSUE THREAD

**Issue by OldWorldOrdr** [rmyorston/busybox-w32#328]
Windows has a second kind of hidden file called "protected operating system files", these are separate from normal hidden files and almost never need to be interacted with by the user (in my over a decade of using Windows I've never had to once).  It would be nice to have an option to hide them in `ls`.

**Comment by OldWorldOrdr** [comment]
support for the gnu ls `-I` option would also be nice but that sounds like something that should be implemented upstream

**Comment by rmyorston** [comment]
The [latest prerelease](https://frippery.org/files/busybox/prerelease) binaries support omitting files with hidden system attributes from the listing. I chose to do this when the `-a` or `-A` option is given twice. This has the advantage of not having to invent another option name: BusyBox `ls` already uses all 32 bits of the option flag.

Support for `-I` is certainly a matter for upstream.
