### ISSUE TITLE
[question] How to get a build version like FRP-XXX-g<hash>

### ISSUE THREAD

**Issue by avih** [rmyorston/busybox-w32#330]
When building using `make mingw64_defconfig && make` the version embedded at `busybox.exe` looks like this:
```
BusyBox v1.37.0.git (2023-06-03 13:23:02)
```
It's useful as it has the date, but it's lacking a reference to an explicit git commit hash, or "FRP counter" (or both).

For instance, the version at the pre-releases look like this:
```
BusyBox v1.37.0-PRE-5014-ge013876e1 (2023-06-03 07:33:46 BST)
```
which, IMHO, is a lot more useful than the default.

I can make it be like the pre-releases version, using this diff:
```diff
diff --git a/Makefile b/Makefile
index f1d6b20b4..f165dd1cb 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 1
 PATCHLEVEL = 37
 SUBLEVEL = 0
-EXTRAVERSION = .git
+EXTRAVERSION = -PRE-$(shell git rev-list --count FRP..HEAD)-g$(shell git rev-parse --short HEAD)
 NAME = Unnamed
 
 # Colon is used as a separator in makefiles.  Strip any drive prefix
```

But I was wondering whether there's some make target or some way to produce [pre-]release-like version numbers without local patches.

I do realise that the patch above is not great while developing, as each change in version (e.g. after pushing a commit) seem to trigger a full rebuild, however, it is useful when one intends to archive the build.

**Comment by rmyorston** [comment]
No, there isn't a standard way to generate the `EXTRAVERSION`. I just have a couple of scripts to build release and prerelease binaries which handle that sort of housekeeping.

The version string can be obtained with this command: `git describe --match FRP`.

**Comment by avih** [comment]
> The version string can be obtained with this command: `git describe --match FRP`.

Right. I was sure there's a shorter method than mine, and now I know there is ;)

Any reason not to push the build scripts to the repo, other than they maybe require cleanups and some generalization (which would be understandable) ?

**Comment by rmyorston** [comment]
>Any reason not to push the build scripts to the repo

Apart from their being ugly and not very interesting, no. I'll get round to it sometime.

Indeed, according to the GPL I probably should be shipping them.

**Comment by avih** [comment]
> Apart from their being ugly and not very interesting, no. I'll get round to it sometime.

Appreciated.

I do maintain a patchset on top of master, so I don't mind an additional local patch for this, but would be nice to have for completeness.

**Comment by rmyorston** [comment]
The build scripts are now in the `examples/mswin-build` directory.

**Comment by avih** [comment]
Yeah. Noticed that. Thanks!

**Comment by avih** [comment]
It's been answered. Shall we close this issue? (I don't recall if @rmyorston prefer to close it himself, or that OP closes it).

**Comment by rmyorston** [comment]
I prefer to leave issues open until a full release has been made with any related fix.
