### ISSUE TITLE
ls -L option doesnt respect -aa or -AA

### ISSUE THREAD

**Issue by OldWorldOrdr** [rmyorston/busybox-w32#331]
if ls -AA -L is run then symbolic links that are system protected will show up in output, for example "My Documents" in home, and "My Music", "My Pictures", "My Videos", in Documents, most of these only exist for compatibility with old programs that expect those directories to exist since they did on old versions of windows and do not need to be shown to users.

**Comment by rmyorston** [comment]
`ls -L` wasn't checking the attributes of the symbolic link (or equivalent) to see if it was affected by `-a` or `-A`.

Try the latest prerelease.

**Comment by OldWorldOrdr** [comment]
fixed
