### ISSUE TITLE
broken symlinks break `ls`

### ISSUE THREAD

**Issue by OldWorldOrdr** [rmyorston/busybox-w32#333]
broken symlinks will produce a `No such file or directory` error when listing a directory with one

to reproduce
```sh
mkdir testdir
ln -s /doesntexist
ls
```
error: `ls: ./doesntexist: No such file or directory`

**Comment by rmyorston** [comment]
No, I don't see the problem.

`ls -L` reports "No such file or directory" but not `ls`.

**Comment by OldWorldOrdr** [comment]
oh i didnt realize that was normal behavior
