### ISSUE TITLE
How kill all descendant processes?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#334]
Hi, this is just a question.

For this simple case:
`sleep 20 && echo doh &`
it is enough to do this:
`pkill -KILL -P "${$}"`

But for more complicate cases like this:
```
var="$({
  cat &
} | hexdump -d -n 32)"
```

How to kill it?

I have found this:
`kill $(ps -s $$ -o pid=)`
and this:
```
list_descendants ()
{
  local children=$(ps -o pid= --ppid "$1")

  for pid in $children
  do
    list_descendants "$pid"
  done

  echo "$children"
}

kill $(list_descendants $$)
```
but they do not work due to limitations in the BusyBox version of them.

Any suggestion?
Thanks in advance.

**Comment by ale5000-git** [comment]
I have noticed this doesn't work:
`pgrep -a -s 0`

Have I done something worng?

**Comment by rmyorston** [comment]
Use a negative pid to kill all children or use the job id:
```
~ $ sh -c 'sleep 10' &
[1] 2080
~ $ kill -- -2080
[1]+  Terminated                 sh -c "sleep 10"
~ $ sh -c 'sleep 10' &
[1] 3600
~ $ kill %1
[1]+  Terminated                 sh -c "sleep 10"
~ $
```
>pgrep -a -s 0
>
>Have I done something worng?

No, it's just that session ids aren't supported on Windows.

**Comment by ale5000-git** [comment]
I need to call all descendants but not the main script.
I'm not expert about this but where do I get the negative pid or the job id?
It isn't interactive, and I cannot use $! since it is executed under a subshell.

**Comment by rmyorston** [comment]
If it isn't interactive you won't have a job id. Use `ps` to get the pid? I don't know.

**Comment by ale5000-git** [comment]
I'm trying but I even can get it to work:
`ps --ppid "$$"`

**Comment by ale5000-git** [comment]
This list descendants but it seems not the ones inside the subshell:
```
_list_descendants()
{
  local _children="$(pgrep -P "${1?}")"

  for _pid in ${_children?}
  do
    printf '%s ' "${_pid?}"
    _list_descendants "${_pid?}"
  done
}
_list_descendants "${$}"
```

**Comment by rmyorston** [comment]
You need the pids of the background jobs. They're children of the subshells, not the current process.
```
( sleep 100 && echo doh & echo $! >pids )
( sleep 100 && echo doh & echo $! >>pids )
( sleep 100 && echo doh & echo $! >>pids )
( sleep 100 && echo doh & echo $! >>pids )
cat pids
```

**Comment by ale5000-git** [comment]
It works, thanks :)
