### ISSUE TITLE
use "[ -e ~/xxx ]", error: "sh: and: unknown operand, "

### ISSUE THREAD

**Issue by aswjh** [rmyorston/busybox-w32#34]
sh/ash/bash have the same problem.

**Comment by rmyorston** [comment]
Does the path to your home directory contain spaces?  C:/Users and Settings, perhaps?

There's a known problem with tilde expansion of such paths.  It affects not only the BusyBox shell but ash from which it is derived.

See https://github.com/pclouds/busybox-w32/issues/2

**Comment by aswjh** [comment]
Yes, [ -e "~/xxx" ] is ok. Thank you.

**Comment by rmyorston** [comment]
Tilde expansion has been fixed in upstream BusyBox and hence in busybox-w32.  It should no longer be necessary to quote tilde expansions where the path contains spaces.

**Comment by aswjh** [comment]
Good news
