### ISSUE TITLE
Wildcard expansion

### ISSUE THREAD

**Issue by ilg-ul** [rmyorston/busybox-w32#35]
I'm a bit confused about your comment in the home page:

> ... the binaries provided here are configured with wildcard expansion disabled. This is the preferred option when the BusyBox shell is being used. (Unix-style shells expand wildcards on the command line before running programs ...

I did some tests and apparently your shell did not expand wildcards, but after changing `CONFIG_NOGLOB=n` it did. Were the wildcard expanded by the shell, or by the utilities (I tried rm & ls from within sh).

My specific need for BusyBox is as shell for make, in the open-source [GNU ARM Eclipse plug-ins](http://gnuarmeclipse.livius.net/blog/) project. I build both make and busybox from sources, as documented in my [wiki](http://gnuarmeclipse.livius.net/wiki/How_to_cross_build_Windows_Build_Tools) page.

The make files generated by the plug-ins do not use wildcards, but in Eclipse it is also possible to build un-managed projects, using custom make files, where I need to support wildcard expansion, otherwise some builds written on GNU/Linux might fail.

Any thoughts on the wildcard expansion?

**Comment by rmyorston** [comment]
Sorry you were confused by my note on wildcards.  The explanation on the web page is far too short.  If it's any consolation I'm equally confused by your claim that the shell in my binaries doesn't expand wildcards.

Let me attempt a longer explanation.  Normally arguments to Windows command line programs are processed by the C runtime.  Wildcards on the command line are expanded according to Windows' rules regarding quoting and special characters.  In contrast, Unix shells perform wildcard expansion before the arguments are passed to the program.

BusyBox on Windows is (obviously) a Windows command line program.  However, I only ever want to use it to run shell scripts or as an interactive shell interpreter, replacing the Windows command prompt.  In these cases wildcard expansion will always be performed by the shell:  there's no need for the binary to do it for us.  Thus I configure the executable with globbing turned off.

Once the BusyBox shell is running it performs its own wildcard expansions.  Starting from a Windows command prompt:

```
C:\Users\rmy>busybox sh
$ touch 123a 123b
$ ls
123a 123b
$ rm 123*
$ ls
$
```
If you copy busybox.exe to rm.exe and try the same thing (having recreated the test files) you get:

```
C:\Users\rmy>rm 123*
rm: can't remove '123*': No such file or directory
C:\Users\rmy>
```

Which shows that the rm.exe binary doesn't expand wildcards.

Now, how this affects make on Windows I really don't know.  How does make know to use the BusyBox shell?

**Comment by ilg-ul** [comment]
> I'm equally confused by your claim that the shell in my binaries doesn't expand wildcards.

ok, we'll test this thoroughly and let you know the results.

> How does make know to use the BusyBox shell?

if it finds a /bin/sh in the path, it uses it, otherwise it uses cmd.exe, generally with devastating results for paths processing.

**Comment by ilg-ul** [comment]
I confirm, the shell built with your default configuration **does** expand wildcards, the issue was a misunderstanding and can be closed.
