### ISSUE TITLE
Cannot count jobs with `jobs | wc -l`

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#350]
Playing with busybox, unicode and starship prompt (it has option to show jobs num) unveil this issue
```
busybox-w32/shell on  cmdtiming via C v16.0.5-clang took 3s
❯ notepad &
[1] 2332

busybox-w32/shell on  cmdtiming via C v16.0.5-clang
❯ jobs | wc -l
0
```
Redirection to file however works. This seems related to #176 
```
busybox-w32/shell on  cmdtiming via C v16.0.5-clang
❯ jobs > jobs.lst

busybox-w32/shell on  cmdtiming via C v16.0.5-clang
❯ cat jobs.lst
[1]+  Running                    notepad
```

**Comment by avih** [comment]
FYI, this seem to also happen with the non-unicode binary (provided by w64devkit 1.20.0).

**Comment by rmyorston** [comment]
The problem is exactly the same as the previous one with `alias` and `history`. It also affects `trap`.

I'm working on it...

**Comment by rmyorston** [comment]
The `jobs` built-in should now work in pipelines, command substitution and process substitution.

Try the most recent [prerelease binary](https://frippery.org/files/busybox/prerelease).

**Comment by naksyl** [comment]
Nice. I was hope to put job number onto PS1, but of course it's a failure - I forgot that command substitution involves new subshell with "clean" environment. I am looking at the code to see what can be done on this subject, but that is another story for a new issue. Even if there is no interest with such feature, maybe someone can answer my questions.

Anyway, I can confirm the issue is fixed and can be closed.
