### ISSUE TITLE
`make` - dealing with absolute path in target name

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#353]
`make` applet recognize absolute path as 2 items:
- target: single letter (drive name)
- dependency: filename relative to current drive + `:`

Example:
 
`$ cat Makefile`
```Makefile
startdir = $(PWD)

$(startdir)/file:
        echo $@

# single letter target name test
z:
	echo $@
```
`$ echo pwd=$PWD; make; make z`
```
pwd=C:/Users/naksyl/Projekty/dbuild/make/pkg
make: nothing to be done for /Users/naksyl/Projekty/dbuild/make/pkg/file:
echo C
C
echo z
z
```
`mingw32-make` from w64devkit and 'posix' `make` from msys (through the magic of path conversion i guess) handle this `Makefile` correctly:
`echo pwd=$PWD; c:/w64devkit/bin/mingw32-make.exe; c:/w64devkit/bin/mingw32-make.exe z`
```
pwd=C:/Users/naksyl/Projekty/dbuild/make/pkg
echo C:/Users/naksyl/Projekty/dbuild/make/pkg/file
C:/Users/naksyl/Projekty/dbuild/make/pkg/file
echo z
z
```

**Comment by rmyorston** [comment]
The latest [prerelease binaries](https://frippery.org/files/busybox/prerelease) allow target names of the form `c:/path` as a non-POSIX extension.
- The default build enables non-POSIX extensions so `c:/path` targets should work out of the box.
- There's a new `windows` pragma to enable support for `c:/path` in POSIX mode. This also requires the use of the `target_name` or `posix_202x` pragma to allow slashes in target names.
```
.POSIX:
.PRAGMA: windows target_name
```
- Target names of the form `c:path` aren't allowed, but it's probably unwise to use them.

**Comment by naksyl** [comment]
> Target names of the form c:path aren't allowed, but it's probably unwise to use them.
Totally agreed. Personally I do not know about this path style (and never used) before I discovered bysybox-w32
