### ISSUE TITLE
Shebang line `#!/bin/busybox sh` fails with SEGV ($?=139)

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#357]
Example session:

```
~ $ cat script
#!/bin/busybox sh

~ $ ./script
SEGV

~ $ echo $?
139
```

**Comment by rmyorston** [comment]
Thanks for the report. That is indeed a bug.

It should be fixed in the [latest prerelease binaries](https://frippery.org/files/busybox/prerelease).
