### ISSUE TITLE
`httpd` - CTRL-C signal handling regression

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#365]
It looks like [FRP-5007](https://frippery.org/busybox/release-notes/FRP-5007.html) signal handling improvements introduce regression of `httpd -f` (FRP-4882 works). 
Sending `CTRL+C` when running with `-f` (foreground) causes the program hangs no longer serving directory. `curl localhost` also hangs. 

Running from Windows `cmd` shell `busybox-w64-FRP-5007-g82accfc19.exe httpd -f` correctly handles `CTRL+C` (cmd kills it?)

**Comment by rmyorston** [comment]
The problem was in the shell.  It should be OK now.
