### ISSUE TITLE
`PATH` - implicitly added current directory

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#368]
Today some installer put extra semicolon on `PATH`. This leads to unexpected results.

Cases when current directory is added implicitly:
- `PATH` ends with semicolon `;`
- `PATH` contains 2 consecutive semicolons `;;`
- `PATH` is empty or unset

```sh
~ $ cat hello
#!/bin/echo

~ $ PATH='C:/Windows'

~ $ hello
lash: hello: not found

~ $ PATH='C:/Windows;'

~ $ hello
hello

~ $ PATH='C:/Windows;C:/Windows/System32'

~ $ hello
lash: hello: not found

~ $ PATH='C:/Windows;;C:/Windows/System32'

~ $ hello
hello

~ $ PATH=''

~ $ hello
hello
```

**Comment by avih** [comment]
Except for empty/unset, this is [specified](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap08.html):
> A zero-length prefix is a legacy feature that indicates the current working directory. It appears as two adjacent <colon> characters ( "::" ), as an initial <colon> preceding the rest of the list, or as a trailing <colon> following the rest of the list.

On linux, all shells which I have access to also interpret leadiing/trailing/double separator in PATH as current directory (bash, dash, ksh93, loksh, mksh, pdksh, bosh, yash, free/net bsd sh, and nore).

However, it's also noted that:
> A strictly conforming application shall use an actual pathname (such as .) to represent the current working directory in PATH

Meaning, as far as I can tell, that anyone who sets PATH should specify current dir as `.` and not empty component, but I think PATH should stilll be interpreted including the legacy behavior - as evident in all shells.

As for empty (nul) PATH, most shells still interpret it as current dir.

As for unset PATH, it's interpreted as current dir by bash, dash, busybox ash, freebsh sh, netbsd sh.

So overall, butsybox sh does align with the common shells.

**Comment by naksyl** [comment]
> So overall, butsybox sh does align with the common shells.

I just not expected such behavior but if this aligns with standard so shall be that way. closing

**Comment by avih** [comment]
For future reference, you can add this to your `~/.profile`:
```sh
# disable current-dir in PATH
PATH=$(printf %s "${PATH-}" | sed -e 's/^;\+//' -e 's/;\+/;/g' -e 's/;\+$//')
[ "${PATH-}" ] || PATH=z:/non/existing/dir
```

**Comment by naksyl** [comment]
Thanks for the tip. Just applied.
