### ISSUE TITLE
while loop taking '<' redirected input hangs

### ISSUE THREAD

**Issue by mentalisttraceur** [rmyorston/busybox-w32#37]
This hangs in busybox-w32's ash:
```
$ echo 'a
> b
> c' > test.txt
$ while read LINE; do echo $LINE; done < test.txt
```

Not terrible, because this works as a workaround:
```
$ cat test.txt | while read LINE; do echo $LINE; done
```
..but the above is a common-ish idiom.

**Comment by mentalisttraceur** [comment]
If you do the above in a shell script instead of on the command-line, you can still Ctrl-C out of it, so it's not a complete freeze - I presume something is just getting stuck in an infinite loop.

**Comment by rmyorston** [comment]
The problem is in the shell's `read` built-in.  When input is coming from a redirected file it gets stuck in a call to `poll`.  I'll continue digging...

**Comment by rmyorston** [comment]
It seems that GNUlib's `poll` implementation doesn't work quite right in this case.  Removing the call to `poll` in the `read` built-in fixes the problem and doesn't seem to break anything else, so let's go with that.
