### ISSUE TITLE
`sort`: support for sorting by version (`-V`) ?

### ISSUE THREAD

**Issue by naksyl** [rmyorston/busybox-w32#370]
Usage has `-V` option but:

```
~ $ printf '%s\n' 1.1 1.11 1.2 | sort -V
sort: unknown sort type

```
 
I'm guessing MinGW lacks some libc/posix functions here

**Comment by rmyorston** [comment]
Yes, version sorting needs `strverscmp`, which is a GNU libc thing. We'd need to pull in an implementation.

**Comment by rmyorston** [comment]
I've copied `strverscmp` from musl libc.

`sort -V` should work now.
