### ISSUE TITLE
Any chance to get netcat (nc) applet support?

### ISSUE THREAD

**Issue by linktohack** [rmyorston/busybox-w32#38]
Like above.
Thanks so much for such utility!
--QL

**Comment by rmyorston** [comment]
I tried a quick test build but couldn't immediately get anything to work.

I expect it's possible, but I'll need to think about it...

**Comment by linktohack** [comment]
Thanks for your reply! can't wait for it to be implemented!

**Comment by rmyorston** [comment]
I've added a basic netcat applet to busybox-w32.  It can act as a client or a server but no advanced options are supported.

**Comment by linktohack** [comment]
Works great for me, many thanks, @rmyorston!
