### ISSUE TITLE
Support NO_COLOR environment variable (it seems now only needed in ls.c)

### ISSUE THREAD

**Issue by janko-js** [rmyorston/busybox-w32#382]
Rationale:

https://no-color.org/

To support it, I think one new line has to be added (between 2 and 3) to the `ls.c` and one line and one comment have to be changed (3 and 4):

Before:

    if (ENABLE_FEATURE_LS_COLOR_IS_DEFAULT && !is_TERM_dumb()) {
        char *p = getenv("LS_COLORS");
        /* LS_COLORS is unset, or (not empty && not "none") ? */
        if (!p || (p[0] && strcmp(p, "none") != 0)) {

After:

        if (ENABLE_FEATURE_LS_COLOR_IS_DEFAULT && !is_TERM_dumb()) {
            char *p = getenv("LS_COLORS");
            char *no_c = getenv("NO_COLOR"); /* if set: no color. See: no-color.org */
            /* if NO_COLOR and LS_COLORS are unset, or later (not empty && not "none") ? */
            if ((!no_c && !p) || (p[0] && strcmp(p, "none") != 0)) {

I haven't tested it, just believe that it could be enough.

The idea is that the user can still set LS_COLORS to something not none to override user's "more global" NO_COLOR, as per in https://no-color.org/

**Comment by janko-js** [comment]
(Note: I've made a typo initially which I've edited afterwards: the correct name for the variable is NO_COLOR  (8 chars and singular not plural), per https://no-color.org/

**Comment by avih** [comment]
I don't see how this is relevant.

Which busybox-w32 applets output color by default, where this NO_COLOR env would make a difference?

**Comment by janko-js** [comment]
> Really it should be addressed to upstream BusyBox.

I'm sorry :(  I use your BusyBox, I haven't used the upstream for years, and I wasn't aware that it comes from there.

Sometimes an implemented solution gets pushed upstream, maybe this can help. I see I've missed " when present and not an empty string" I'm sorry about that.

The existing LS_COLORS=none already worked for my use case of using your busybox, I just hoped to motivate that more global approach of no-color.org where I saw it. Maybe it's better that you revert that change, as it shouldn't be mingw specific anyway? If you do want to solve it completely, it seems there would be more work to do to achieve full no-color.org logic, specifically from Faq answer 2, where, if the program insists to have color by default, like it was in busybox, then NO_COLOR allows turning that default off for all such applications, but also, per Faq 2, the user can still turn on the colors "per app". Your current solution doesn't cover that scenario. That gets messy if it has to be solved with # if directives, so maybe better reverting?

**Comment by rmyorston** [comment]
I often submit my changes to upstream BusyBox. I haven't done that for this one just yet. It isn't that intrusive so I'm happy to carry it in busybox-w32 for now. Upstream haven't been very responsive lately and there are more important issues for them to deal with than this.

I'm not sure I understand your concern about FAQ 2. The `ls --color` option allows the user to turn on colour:
```
export NO_COLOR=1
ls --color
```
The output is coloured in this case.

**Comment by janko-js** [comment]
I think the correct lines would be (again not tested, but I think it covers non emptiness and protects the p[0] too:

        char *p_no_c = getenv("NO_COLOR"); /* if set: no color. See: no-color.org */
        bool no_c = p_no_c && p_no_c[0] != 0;
        /* if NO_COLOR and LS_COLORS are unset, or later (not empty && not "none") ? */
        if ((!no_c && !p) || (p && p[0] && strcmp(p, "none") != 0)) {

**Comment by janko-js** [comment]
(deleted previous, I'm not sure I have thought about all the "unset" aspects, the truth tables I've made don't include null pointers -- "unset" cases)

**Comment by janko-js** [comment]
Changing the basic assumption of "colors by default" for unset ls_colors would be much cleaner, I think, and would make NO_COLOR not needed at all, but somebody introduced that and now the complexity falls on somebody else.

**Comment by rmyorston** [comment]
The situation with colour in `ls` is complicated.

Neither coreutils `ls` nor FreeBSD `ls` enable colour by default. In each case it's necessary to use one of the `--color` options to enable colour. Therefore `NO_COLOR` is unnecessary.

BusyBox `ls` has a build-time configuration option to enable colour by default. This option is enabled in default builds of upstream and busybox-w32, despite the description of the option saying its use is not recommended. Changing this now is unlikely to be welcome.

When colour is enabled by default it's possible to turn it off either with the `--color=none` option or by a particular setting of the `LS_COLORS` environment variable.  The latter is unique to BusyBox.  Setting `LS_COLORS` to an empty string or `none` disables colour.

The use of `none` was a bad idea. It isn't a valid string for coreutils `ls`: it does disable colour there but it also issues a warning that the string can't be parsed.  An empty value, on the other hand, disables colour in coreutils `ls` without a warning.

Although particular settings of `LS_COLORS` can be used to _disable_ colour in BusyBox `ls`, no setting of it will _enable_ colour.  This is also true of coreutils `ls`.  That's not what `LS_COLORS` is for.

I think my recent change is the correct way to extend BusyBox to support `NO_COLOR` while retaining support for the existing (somewhat flawed) mechanism.

**Comment by janko-js** [comment]
> The use of none was a bad idea

As far as I understand, empty environment variable can neither be entered in windows dialog nor in bat files, so I understand, at least, why it was invented. I understood that it's not compatible outside of BusyBox. I didn't know that outside of BusyBox the command line switch is actually required to turn that on, thanks. Then what's there can really be enough.

Also many thanks for all your work on busybox-w32 . I really like to use it, it's marvelous that it's a single binary with all the functionality and careful adjustments needed for convenient work under Windows.
