### ISSUE TITLE
'schtasks' exits with an error when called from a script on Windows Server 2003 R2

### ISSUE THREAD

**Issue by vszakats** [rmyorston/busybox-w32#39]
When a shell script executed by busybox (latest binary build) calls the OS tool `schtasks.exe`, the tool fails with an error:

```bash
#!/bin/sh
schtasks.exe
```

```
> busybox.exe sh test.sh
ERROR: Class not registered
```

Same script when executed via:
```
GNU bash, version 3.1.23(6)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.
```

```
> sh.exe -c test.sh

TaskName                             Next Run Time            Status         
==================================== ======================== ===============
[...]
```

It appears to be working fine when run under Windows 7 (SP1 x64).

**Comment by rmyorston** [comment]
Also works in Windows 8.1.  I don't have access to Windows Server 2003.

Does it work with older binaries?  I'd suggest trying busybox-w32-TIG-1525-ge19594c.exe and busybox-w32-TIG-1657-g425eb69.exe

**Comment by vszakats** [comment]
With 1525, it fails the same way. Tried now all binaries between 1618 and 1658 and all of them fail, except those that display `: applet not found` and skip running the script, f.e. 1657.

**Comment by rmyorston** [comment]
Very odd.  Does schtasks work if you run it from an interactive BusyBox shell?

**Comment by vszakats** [comment]
It doesn't. But, this lead me to the solution: it's enough to reset `SYSTEMROOT` envvar to use backslashes:
```bash
#!/bin/sh
SYSTEMROOT="$(printf '%s' "${SYSTEMROOT}" | sed -e 's|/|\\|g')"
schtasks.exe
```

I'm guessing newer `schtasks` versions do not rely on this envvar, and above tested msys shell keeps the backslashes in envvars inherited from the calling process.

(This can be closed from my end.)

**Comment by rmyorston** [comment]
Interesting.  As a long-time UNIX user it seems more natural to have forward slashes in paths.  I haven't noticed this causing problems on Windows, though I now wonder if issue #16 is another example.  That involved Windows XP, which is even older than Windows Server 2003.

Anyway, now that you have a workaround I'll close this issue.

**Comment by vszakats** [comment]
Thank you very much for your help and insight.
