### ISSUE TITLE
diff: non binary safe

### ISSUE THREAD

**Issue by roytam1** [rmyorston/busybox-w32#4]
You may try to `diff -U8 bdf2hex.vs05.cpp bdf2hex.cpp` and your git version goes strange ( http://roy.dnsd.me/rmyorston-diff.txt ), while pclouds version works.

http://roy.dnsd.me/bdf2hex.vs05.cpp
http://roy.dnsd.me/bdf2hex.cpp

**Comment by rmyorston** [comment]
Should be fixed in current code.

**Comment by sergeevabc** [comment]
@rmyorston, any ideas why ```-y``` aka ```--side-by-side``` switch is not supported? Quite a [crucial switch][1].

[1]: https://stackoverflow.com/a/17195364

**Comment by sergeevabc** [comment]
Aggrrhh, suppressing common lines is not supported as well. I wonder how to compare huge files then?

**Comment by rmyorston** [comment]
@sergeevabc, the questions you raise would be better addressed upstream.
