### ISSUE TITLE
Variable substring matching pattern not recognized

### ISSUE THREAD

**Issue by vszakats** [rmyorston/busybox-w32#40]
This script is meant to extract the filename part from a pathspec in a portable way. It's expected to display `file.ext` twice, but it displays the whole input string instead when run with BusyBox:
```bash
#!/bin/sh
test='/dir/file.ext'
echo "${test##*[/|\\]}"
test='\dir\file.ext'
echo "${test##*[/|\\]}"
```

BusyBox v1.24.0-TIG-1784-gdb98881 (2015-04-22 21:47:46 BST) multi-call binary:
```
/dir/file.ext
\dir\file.ext
```

3.1.23(6)-release:
```
file.ext
file.ext
```

It's an upstream issue, in case it isn't an intentional omission. The pattern matching rules are described [here](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13).

**Comment by rmyorston** [comment]
It looks as though the issue was fixed in dash with [this commit] (http://git.kernel.org/cgit/utils/dash/dash.git/commit/?id=7cfd8be0dc83342b4a71f3a8e5b7efab4670e50c). I'll see if it can be ported to BusyBox ash.

**Comment by vszakats** [comment]
Thank you for the quick follow-up, fingers crossed for a successful port.

**Comment by rmyorston** [comment]
Well, that was a bit more tricky than I'd have liked but a patch to fix the reported issue (plus several other unrelated ones) has been accepted by upstream BusyBox.  Can you check that the latest busybox-w32 binary works for you?

**Comment by vszakats** [comment]
I've made some quick tests and everything seems to work well, including the new pattern matching. Just seeing the commits it was indeed an extensive update; thank you and upstream folks very much for following through this. I'll keep an eye on my logs in the next days for anything irregular. Thanks again!

**Comment by mentalisttraceur** [comment]
@vszakats Not directly related to the issue, but can you still consider the above example "portable" if you now know that recent (d)ash versions did not support it?

Bigger issue: Backslashes are legal characters in *nix filenames, but if I'm on *nix, and I place the file named `foo\bar.txt` inside `/tmp`, your substitution will return bar.txt, which is not the filename.

If I may make a small assumption about your likely usecase, and make a suggestion accordingly, I would first check if `uname`'s output matches the shell glob `*_NT`, and then define your substitution in those terms:

```
case `uname` in
*_NT)
    pathsep=\\
    ;;
*)
    pathsep=/
esac
# Then later, assuming $pathname contains the path you need to strip:
printf '%s\n' "${pathname##*$pathsep}"
```
(`printf` instead of `echo` because if your filename is `-n` after removing the directory part, echo will have undefined behavior.)

**Comment by vszakats** [comment]
It was not meant as the ultimate pathname splitting solution, just one that lead me discovering this feature missing and what was short enough to demonstrate it. Your points are all valid, though I think relying on `uname` content can be fragile (but `*_NT*` would cover most Windows flavors), and it assumes that the input pathname uses platform _native_ pathseps. Latter is not always true, f.e. with `busybox-w32`, `$0` will inherit the pathseps passed to `busybox.exe sh <script-name>` as-is, and they are accepted in both Windows and *nix format there.

Am I reading it right that this (d)ash feature is missing from recent versions?

**Comment by rmyorston** [comment]
The fix for this bug was applied to dash in September 2007 but the first release after that seems to have been 0.5.5 in January 2009.  RHEL/CentOS 6 has dash 0.5.5.1, so has the fix.  Later Red Hat /Fedora systems will undoubtedly be OK.  I don't know about other OSes or variants of ash.

**Comment by vszakats** [comment]
Ah okay, thanks for clarifying, so it is a relatively recent fix and there might be unfixed versions out there. That's indeed something to consider.

This is an alternative:
```bash
pathname="$(echo "${pathname}" | tr '\\' '/')"
echo "${pathname##*/}"
```

(or with `printf` instead)

**Comment by mentalisttraceur** [comment]
Ah, you're absolutely right @vszakats about native pathspecs. I assumed your usecase was one where, indeed, pathspecs were wanted in their "native" form, regardless of what the shell script itself was using. (I.e. perhaps your shell scripts were to be used by Windows users who would happily feed them Windows backslash-separated paths.)

When I'm on Windows I tend to just try to make my commandline experience as *nix-like as possible, so I've only rarely had to deal with that issue myself, so I guess I just didn't think of it.

But anyway, you're definitely right, and I just knee-jerked upon seeing the words "portable" and felt compelled to point out portability issues instinctively. I think though, without explicitly ruling out support for paths with backslashes in them on *nix, I you can't really have universal solution (runnable on both *nix and Win unmodified) without using some sort of conditional cue to indicate if the backslashes need to be converted or treated as literals (whether that be `uname` invoked in the script, a command line option, or whatever).

**Comment by vszakats** [comment]
You're right, there is a compromise to make depending on the exact use-case. I'd be personally a bit worried to use backslashes in *nix filenames, even if they are formally valid. Those may test the limits of scripts and tools, similarly to how spaces-in-pathnames may cause all sorts of problems under Windows. If it is under one's control, that is.

**Comment by mentalisttraceur** [comment]
(Apologies for basically turning this into a completely off-maintaining-busybox-w32 discussion, but I just thought of another unmentioned detail)
@vszakats You might already know this but I had forgotten: on modern Windows, _both_ `/` and `\` are considered path separators. I've edited my comment above, but just in case I also wanted to comment here.

**Comment by vszakats** [comment]
Yes indeed, this is something easily forgotten. One should prepare for both. Thanks for the update @mentalisttraceur.

As for this issue, all my busybox scripts run fine since this update, no regressions.
