### ISSUE TITLE
Imprecise timeout or sleep

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#400]
This works fine in the online bash shell:
`timeout 5.99 sleep 5.98; echo $?`
but on BusyBox it timeout.

I'm sure why but in the past I also get this to fail `timeout 6 sleep 5; echo $?` but now it works.

**Comment by rmyorston** [comment]
BusyBox `timeout` accepts fractional times but silently truncates them to an integer value. The example above is therefore _effectively_:
```
timeout 5 sleep 5.98; echo $?
```

The problem is in the upstream code so any fix will need to be acceptable to them.

**Comment by ale5000-git** [comment]
This also timeout:
`timeout 6 sleep 5.9; echo $?`

**Comment by rmyorston** [comment]
>This also timeout:
>`timeout 6 sleep 5.9; echo $?`

That one, I think, is _my_ problem, so can be fixed without reference to upstream.

**Comment by ale5000-git** [comment]
Thanks, for the other one I will report it upstream when I get some time.

**Comment by ale5000-git** [comment]
This works perfectly: `timeout 5.99 sleep 5.95; echo $?`
It seems good enough for almost all uses, thanks a lot.

**Comment by rmyorston** [comment]
This issue should be fixed in the latest release, FRP-5398.

**Comment by rmyorston** [comment]
The upstream patch has also been applied, so fractional timeouts are supported there too now.
