### ISSUE TITLE
[QUESTION] Parametrize output descriptor

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#412]
Hi,
since in some cases I want to change where the output go I wonder if this is POSIX compliant and really portable:
```
send_output()
{
  echo 1>&"${1:?}" "${2:?}"
}

send_output 1 'Prova 123'
send_output 2 'Prova 345'
```

**Comment by avih** [comment]
I think it's valid that `word` can be expanded. POSIX says:
> The redirection operator:
> [n]>&word
> shall duplicate one output file descriptor from another, or shall close one. If word evaluates to one or more digits, the file descriptor denoted by n, or standard output if n is not specified, shall be made to be a copy of the file descriptor denoted by word; if the digits in word do not represent a file descriptor already open for output, a redirection error shall result; see [Consequences of Shell Errors](file:///T:/bak-2019-10-18/d-etexts/private/POSIX-1003.1-sus_html-master--d2023-02-25--PRIVATE-COPY/sus_html-master/html/utilities/V3_chap02.html#tag_18_08_01). If word evaluates to '-', file descriptor n, or standard output if n is not specified, is closed. Attempts to close a file descriptor that is not open shall not constitute an error. If word evaluates to something else, the behavior is unspecified.

Also, you can also use eval (carefully), e.g. `eval "myfunc >&$whatever"`

**Comment by ale5000-git** [comment]
Thanks for the reply, is there anyone else that has this in many shells (especially old ones)?

**Comment by rmyorston** [comment]
>it says something like "word is subject to tilde expansion, parameter expanstion, ...", which it does not say here

To avoid needless repetition they define the expansions in the introductory part of 2.7:
>If the redirection operator is "<<" or "<<-", the word that follows the redirection operator shall be subjected to quote removal; it is unspecified whether any of the other expansions occur. For the other redirection operators, the word that follows the redirection operator shall be subjected to tilde expansion, parameter expansion, command substitution, arithmetic expansion, and quote removal. Pathname expansion shall not be performed on the word by a non-interactive shell; an interactive shell may perform it, but shall do so only when the expansion would result in one word.

So we should be fine.

>Is there anyone else that has tested the code (my code, not eval because it likely has a lot of sided effects) in many shells (especially old ones)?

The oldest shell I had ready access to is the one from Version 7 UNIX in [ V7/x86](https://www.nordier.com/articles/v7x86_vbox.html). But it's far too old to understand your code.

The next oldest was bash 1.14 from 2000, where it works as intended.

**Comment by ale5000-git** [comment]
Thanks to both for the help.
