### ISSUE TITLE
ls causes OneDrive to download files from server

### ISSUE THREAD

**Issue by Peter0x44** [rmyorston/busybox-w32#414]
Currently, running `ls` in a onedrive directory will cause all files within it to be downloaded if they are not "synced" already.
MSYS2 seems to have a related issue here:
https://github.com/msys2/MSYS2-packages/issues/3049

I'm not sure if this can be fixed, or if it's worth the effort to do so, but I figured I'd open this issue to get some discussion going.

**Comment by rmyorston** [comment]
Most likely it's because busybox-w32 looks inside many files to see if they're executable. It checks for shebang and executables that don't have the standard extensions. There may be other prodding of files it does that has the same effect.

Any fix would probably result in reduced functionality.

**Comment by Peter0x44** [comment]
@rmyorston This worked for my case, thanks!
