### ISSUE TITLE
-X turns forward slashes in URLs in the parent's environment variables into backslashes, it should not

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#415]
`sh -X` should probably not turn all environment variable forward slashes into back slashes.

```
C:\Users\doctorpangloss>set TEST="http://hello.com"

C:\Users\doctorpangloss>echo %TEST%
"http://hello.com"

C:\Users\doctorpangloss>busybox sh -X
~ $ echo $TEST
"http:\\hello.com"
```

It should still be http://hello.com

**Comment by rmyorston** [comment]
Indeed, it shouldn't do that.

Try the latest [prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5342 or above).

**Comment by doctorpangloss** [comment]
resolved
