### ISSUE TITLE
Can you bring bmake to Windows?

### ISSUE THREAD

**Issue by iahunq2** [rmyorston/busybox-w32#417]
I tried to compile it under MSYS2 (MSYS POSIX Environment) but I failed. The binary is created. But the tests failed.

https://www.crufty.net/help/sjg/bmake.html

It could live in busybox-w32 as bmake, so there will be no conflict with the default pdpmake.

**Comment by rmyorston** [comment]
Sorry, I have no plan to do that.

**Comment by iahunq2** [comment]
OK.

**Comment by ale5000-git** [comment]
@iahunq2
Busybox already include a POSIX implementation of make.

**Comment by iahunq2** [comment]
> @iahunq2 Busybox already include a POSIX implementation of make.

It's useless!

**Comment by ale5000-git** [comment]
If the programs use non-standard feature of make is only their issue and their task to fix it.
Just because developers like to use non-standard make features, it doesn't make a POSIX make any less useful.
