### ISSUE TITLE
Failed to run python, xp

### ISSUE THREAD

**Issue by aswjh** [rmyorston/busybox-w32#42]
![bb2](https://cloud.githubusercontent.com/assets/6280240/7977213/5bb6b228-0a77-11e5-9e2f-896ffe324a61.png)

**Comment by rmyorston** [comment]
Issue #16 has the same error, also on Windows XP.  Issue #39 has a different error, but again was specific to Windows XP.  In that case the solution was to ensure that the `SYSTEMROOT` environment variable used backslash as the path separator.

busybox-32 makes environment variable names upper case and changes backslashes to slashes in environment variable values.  It's possible that this is confusing Windows XP.  Unfortunately I don't have access to Windows XP, so I can't investigate this myself.

To prevent busybox-w32 from changing the environment execute this sequence of commands in the Windows Command Prompt:

```
set xpath=%path%
set path=
set PATH=%xpath%
busybox sh
```
Does python now run in the shell?  If so I'll look into making a permanent fix.

**Comment by aswjh** [comment]
Yes, it works, thank you.
![bb2](https://cloud.githubusercontent.com/assets/6280240/7996134/ce85ca10-0b0c-11e5-8ab9-a006d492aee5.png)

**Comment by rmyorston** [comment]
I've added a `-X` shell option which prevents busybox-w32 from changing the backslashes in environment variables to slashes.  It must be the first argument.
```
busybox sh -X
```

**Comment by aswjh** [comment]
Working properly, thanks.
