### ISSUE TITLE
[Question] Any way to make mintty work better with busybox-w32 ash?

### ISSUE THREAD

**Issue by shunf4** [rmyorston/busybox-w32#420]
I would be very glad if I can use [mintty](https://mintty.github.io) with busybox-w32, like:

```
C:\cygwin64\bin\mintty.exe -e busybox ash
```

It opens busybox ash, but it has a wrong `$HOME`, given by mintty/cygwin-newlib:

```
C:/Users/shunf4 $ echo $HOME
C:\cygwin64\home\shunf4
C:/Users/shunf4 $
```

Cancelling `$HOME` and relaunching it doesn't work:

```
C:/Users/shunf4 $ HOME= ash
~ $ echo $HOME

~ $
```

This breaks many use cases of mine.

Digging into the code, I found it's because of this:

https://github.com/rmyorston/busybox-w32/blob/5c1a3b00e235da31b2c73bae18aa5622d820b68a/shell/ash.c#L15843-L15864

https://github.com/rmyorston/busybox-w32/blob/5c1a3b00e235da31b2c73bae18aa5622d820b68a/shell/ash.c#L15804-L15819

Mintty(or newlib?) "standardize"s all env vars to upper case for its child process, so "mixed_case" is not detected, and login-related env vars' initialization is also skipped. so no `HOME` and `USER` env vars available in ash:

https://github.com/rmyorston/busybox-w32/blob/5c1a3b00e235da31b2c73bae18aa5622d820b68a/shell/ash.c#L15894-L15900

Knowing this, then I can workaround by reverting the case of `PATH` and `COMSPEC`:

```
C:\cygwin64\bin\mintty.exe -e busybox ash -c "env -u HOME -u PATH -u COMSPEC Path=\"$PATH\" ComSpec=\"$COMSPEC\" ash"
```

Is there a better, more direct way? Or, a better way to detect busybox ash launching from another busybox invocation other than looking at the case of environment variables?

**Comment by ale5000-git** [comment]
Doesn't it works like this?
`mintty.exe -e busybox ash -s -c 'HOME='`

**Comment by shunf4** [comment]
> > Doesn't it works like this? (after the fix of ProgramData) `mintty.exe -e busybox ash -s -c 'unset HOME'`
> 
> More like this:
> 
> ```
> mintty.exe -e busybox ash -c "env -u HOME ash"
> ```

Or this:

```
mintty.exe -e busybox env -u HOME ash
```

Considering mintty is more of a Cygwin thing and much used in `mintty.exe /bin/bash -il` form (which needs to read `~/.bashrc` etc), I may have to live with mintty's setting `HOME`, and unavoidably using `unset HOME` or `env -u HOME` in my use case.

**Comment by rmyorston** [comment]
I've added a hack to try and detect the use of mintty.

Try the latest [prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5349 or above).

**Comment by shunf4** [comment]
Neat, now `C:\cygwin64\bin\mintty.exe -e busybox.exe ash` runs well.

**Comment by shunf4** [comment]
> Neat, now `C:\cygwin64\bin\mintty.exe -e busybox.exe ash` runs well.

Only when invoked from cmd.

If invoked from a cygwin envrionment like `$ mintty -e busybox bash`, then `PS1` breaks, all backslashes replaced by a slash. May `PS1` be excluded from `setwinxp`?

**Comment by rmyorston** [comment]
If you don't want backslashes to be converted use `$ mintty -e busybox bash -X`.
