### ISSUE TITLE
Duplicate with which -a

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#427]
In bash online this only return unique values:
```
PATH="${PATH}:/usr/bin/find:/bin/find:/usr/bin/find:/bin/find"
which -a find
```

Instead on BusyBox for Windows this will return duplicates:
```
PATH="${PATH};C:/Windows/system32;C:/Windows/system32"
which -a find
```

**Comment by avih** [comment]
> In bash online this only return unique values:
> 
> ```
> PATH="${PATH}:/usr/bin/find:/bin/find:/usr/bin/find:/bin/find"
> which -a find
> ```

It returns a single value because you're adding file names instead of directories.

Try this instead, just duplicate the path, e.g. on ubuntu in bash:
```sh
$ PATH=$PATH:$PATH which -a find
/usr/bin/find
/bin/find
/usr/bin/find
/bin/find
```

So it looks to me that busybox-w32 behaves like bash.

**Comment by ale5000-git** [comment]
Damn, this happen when copy-pasting in hurry.
Sorry.
