### ISSUE TITLE
Cannot copy and paste a 1112 character string into busybox on Windows, but pasting into Python in the same shell or Powershell works fine

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#429]
Pasting small but long lines of text fails frequently.

**Reproduction**:

1. Copy this blob of text:

```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1
```

Observe the last character is `1`.

2. Open busybox in Windows Terminal.
3. Paste.
4. Observe the `1` is missing at the end of the paste. This should not happen.
5. Open powershell.
6. Paste.
7. Observe you see the final 1.
8. Open busybox.
9. Open python inside busybox.
10. Paste.
11. Observe you see the final 1.

**Comment by avih** [comment]
This is the same as in upstream busybox.

I'm guessing it's controlled by the config value CONFIG_FEATURE_EDITING_MAX_LEN, which defaults to 1024.

So you can build bb-w32 yourself with a bigger configured value, or maybe the default for windows can be increased a bit, but keep in mind that the line edit in busybox (including -w32) is not the most efficient, especially when it spans multiple lines, so placing such a long input at the line-edit prompt is sub-optimal anyway.

But yeah, increasing it to 2048 for instance would probably be OK.

**Comment by doctorpangloss** [comment]
Is there any reason `CONFIG_FEATURE_EDITING_MAX_LEN` can't be a really, really large number?

**Comment by avih** [comment]
> Is there any reason `CONFIG_FEATURE_EDITING_MAX_LEN` can't be a really, really large number?

I'm guessing memory usage and efficiency of the editing algorithms, but it's a complete guess.

Why won't you build it with the maximum size (about 37000) and report back if you observe any issues when placing many KB of text at the prompt?

**Comment by rmyorston** [comment]
@doctorpangloss It depends what you mean by really, really large. How big is that, exactly?

In practical terms there's little point in going above 32KB, though quite a bit less than that is probably enough for most people.

**Comment by avih** [comment]
I wonder what are the practical use cases for pasting several KB into the shell prompt.

The most I can think of is e.g. a huge URL which one intends to use with curl or wget, for instance, though URLs are typically also limited in length by browsers and possibly other tools (e.g. in Edge it's 2K, though other browsers have higher limit).

Another thing, maybe, is pasting a big script snippet which one wants to execute at the current shell, but it's quite ill-advised to do that.

What other practical use cases are there?

**Comment by ale5000-git** [comment]
I was about to copy on cmdline a json strong of length of 2176 to testing the parsing function and got truncated, isn't possible to increase the dafault value of max length to 8191 ot match the limit of the command prompt in Windows?

According to this document the limit of normal command prompt is 8191: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

**Comment by rmyorston** [comment]
We don't really care what the Windows command prompt does, but since nobody has suggested a concrete value to use I've set the buffer size to 8192 bytes. This happens to be the maximum the BusyBox configuration allows (though that's neither here nor there, we could use something bigger if we wanted).

If you want a [prerelease](https://frippery.org/files/busybox/prerelease), PRE-5439 or above is the one to go for.

**Comment by ale5000-git** [comment]
> We don't really care what the Windows command prompt does

If I'm not wrong when executing a busybox applet directly from cmd/Windows Terminal (ex: busybox wget) we are still limited by Windows limitations.
Also when executing a busybox applet from a batch we have the same limit.
In addition also when executing an external app from busybox we have the same limit.

And even the expanded env vars have the same limit, so if, for example, I have a PATH env var with an expanded length of over 8191 and execute an external process it will be ignored (and maybe the external app crash).

Quote:
`Even though the Win32 limitation for environment variables is 32,767 characters, Command Prompt ignores any environment variables that are inherited from the parent process and are longer than its own limitations of 8191 characters (as appropriate to the operating system).`

**Comment by rmyorston** [comment]
If you use command prompt you're subject to its limitations. If you don't you may be subject to other, different limitations of Windows.

My point was just that since the use of command prompt is voluntary it needn't be a consideration in choosing a maximum paste size for the busybox-w32 shell.
