### ISSUE TITLE
'ed' command is unexpected

### ISSUE THREAD

**Issue by wanghan519** [rmyorston/busybox-w32#431]
```
seq 4 > a.txt
seq 11 14 > b.txt
ed a.txt

2r b.txt
,p
```
1
2
11
3
12
13
14
4

3 should be after 14, but now it's after 11.

win10 22H2
busybox v1.37.0-FRP-5398-g89ae34445

thank you

**Comment by rmyorston** [comment]
The same issue is present in upstream BusyBox on Linux. I'll look into it.

**Comment by rmyorston** [comment]
I have a fix for the issue. It's available in the latest [prerelease binaries](https://frippery.org/files/busybox/prerelease) on my website (PRE-5435 or above).

I've also submitted a patch upstream.

**Comment by rmyorston** [comment]
Just for the record, upstream BusyBox have accepted the patch, so `ed` now works correctly there too.
