### ISSUE TITLE
Allow to override Content-Length in wget

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#432]
When manually providing Content-Length it is sent two times; this problem doesn't happen in stand-alone wget.
The reason I set it manually is to send to headers in a specified order.
Is it possible to allow it?

Example:
`wget -O - --header 'Content-Type: text/plain;charset=UTF-8' --header "Content-Length: 2" --header 'Other-Header: 1' --post-data '{}' -- "${url}"`

**Comment by rmyorston** [comment]
It's an upstream issue really, but just for you...

[Prereleases](https://frippery.org/files/busybox/prerelease), PRE-5440 or above.

**Comment by ale5000-git** [comment]
Thanks, it works perfectly.
I will request the fix upstream today.
