### ISSUE TITLE
history started printing to stderr, which is unexpected

### ISSUE THREAD

**Issue by doctorpangloss** [rmyorston/busybox-w32#433]
in `BusyBox v1.37.0-PRE-5439-g2df01b247 (2024-07-26 09:35:41 BST)`, `history` is now printing to `stderr`. Is there a way to change the behavior back to `history` printing to stdout, i.e., so that `history | grep ...` works again? Or, is there a way to make the busybox command line behave more like `zsh` with regards to completion?

**Comment by rmyorston** [comment]
Not just PRE-5439, this also affects the FRP-5398 release.

It's an upstream bug. Commit fd47f056765aed515f4c71118813f07be1402bee incorrectly changed the function used by the shell to print history.

I'll fix it later. In the meantime `history 2>&1 | grep ...` is a workaround.

**Comment by rmyorston** [comment]
Fixed in [prerelease](https://frippery.org/files/busybox/prerelease) PRE-5441. A patch has also been submitted upstream.

**Comment by doctorpangloss** [comment]
thank you!

**Comment by rmyorston** [comment]
Just for the record, the patch has been accepted upstream, so we're now in sync on this issue.
