### ISSUE TITLE
$SHLVL in su is wrong

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#436]
From `busybox ash` I run `su`,
then (inside the su window):
```
$ echo $SHLVL
1
$ exec "C:/Program Files/Git/usr/bin/bash.exe"
$ echo $SHLVL
2
```

Why `$SHLVL` became **2** if I use exec?

**Edit:** I get the same issue also with `exec ash`

**Comment by rmyorston** [comment]
Apart from the reference to `su` this seems to be a duplicate of #302.

As mentioned there, bash decrements `SHLVL` in `exec` while upstream BusyBox (and so busybox-w32) don't. I looked for a way to replicate the bash behaviour in BusyBox, but without success.

**Comment by ale5000-git** [comment]
I didn't remember the old ticket, I will ask upstream them.
