### ISSUE TITLE
su => drop => su bug

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#437]
Execute:
```
busybox su
```

In the admin window now created execute:
```
exec drop
su
```

Now it appears another new window without admin rights but the title still say admin.

**Comment by rmyorston** [comment]
When the `drop` applet drops privilege the resulting state isn't _exactly_ like a truly unprivileged process.

The `su` applet uses the `ShellExecute()` `runas` verb to start the privileged shell. When `ShellExecute()` is run from a process which has had privilege dropped it treats it as a privileged process and _doesn't_ elevate privilege.

Things we could do:
- Have `su` detect that it's unable to start a privileged shell and refuse to proceed.
- Have `ash` detect that the new shell is unprivileged and omit the `(Admin)` from the title string.
- Nothing.

**Comment by ale5000-git** [comment]
In my opinion the first choice is the best since it is useless spawn a new window if it can't get privileges and if there is a specific error code it can be detected by the script.

**Comment by rmyorston** [comment]
`su` now detects when it can't raise privilege due to an earlier `drop`. It reports an error and returns an exit status of 2.

[Prerelease binaries](https://frippery.org/files/busybox/prerelease) with this fix are available (PRE-5445 or above).

**Comment by ale5000-git** [comment]
It works perfectly, thanks.
