### ISSUE TITLE
$PROMPT difference

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#441]
If I run `busybox ash` from `cmd.exe` then `$PROMPT` has a value of `$P$G`.
Instead if I rename `busybox.exe` to `ash.exe` and double click on it then `$PROMPT` is unset.

I wonder if this difference can cause any issue.

**Comment by rmyorston** [comment]
`PROMPT` isn't used by BusyBox and it isn't mentioned in POSIX so it's unlikely to cause any issues there.

It _is_ used by `cmd.exe`, but it can look after itself.

**Comment by ale5000-git** [comment]
I know about BusyBox and UNIX like app; I mean to ask if there may be problems about Windows app executed by BusyBox without `$PROMPT`.

**Comment by avih** [comment]
> I know about BusyBox and UNIX like apps; I mean to ask if there may be problems about Windows/DOS apps executed by BusyBox without `$PROMPT`.

There shouldn't be an issue. PROMPT is set by and is for for cmd.exe only, not for any other comsole apps.

If you run console apps from Windows expolorer, also there's no PROMPT.

**Comment by ale5000-git** [comment]
Ok, thanks for the reply.
