### ISSUE TITLE
--help go to stderr

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#445]
I don't remember correctly but wasn't `--help` changed to go to stdout?
Now it seems to go to stderr.

Since the help is explicitely requested doesn't it make sense to output to stdout like bash?

**Comment by rmyorston** [comment]
You're thinking of issue #395. That only resulted in a patch being sent upstream. It hasn't been accepted there yet. I'm awaiting their response before applying it here.

**Comment by garoto** [comment]
From a quick test: `pigz.exe`, `bzip2.exe` and `upx.exe` sent their `--help|-h` output to stderr. From what I gather, there's no real consensus.

**Comment by avih** [comment]
There are exceptions like you mentioned, but there is concensus, and that's stderr is used for error messages, while intentional request and output of help text is not an error message, therefore it should go to stdout.

**Comment by ale5000-git** [comment]
I have create a ticket to keep track of the problem: https://bugs.busybox.net/show_bug.cgi?id=16162

**Comment by rmyorston** [comment]
Upstream have taken the patch.  From PRE-5484 `--help` text goes to stdout.

**Comment by ale5000-git** [comment]
It works fine, thanks.
