### ISSUE TITLE
sh is borked on paths with non-ASCII characters

### ISSUE THREAD

**Issue by clin1234** [rmyorston/busybox-w32#447]
Launching external commands does not work, though shell built-ins do work.

```
PS C:\Users\שזדס> .\scoop\apps\w64devkit\current\bin\busybox.exe
BusyBox v1.37.0.git-5398-g89ae34445 (2024-08-01 15:18:13 UTC)
(glob)

PS C:\Users\שזדס> .\scoop\apps\w64devkit\current\bin\busybox.exe bash
~ $ s
bash: s: not found
~ $ sdf
bash: sdf: not found
~ $ env
bash: unable to spawn shell
~ $ export
export ALLUSERSPROFILE='C:/ProgramData'
export APPDATA='C:/Users/????/AppData/Roaming'
export BB_GLOBBING='0'
export CHOCOLATEYINSTALL='C:/Users/????/AppData/Local/UniGetUI/Chocolatey'
export COMMONPROGRAMFILES='C:/Program Files/Common Files'
export COMMONPROGRAMFILES_X86_='C:/Program Files (x86)/Common Files'
export COMMONPROGRAMW6432='C:/Program Files/Common Files'
export COMPUTERNAME='LAPTOP-12HPO6T3'
export COMSPEC='C:\Windows\system32\cmd.exe'
export CommonProgramFiles
export DRIVERDATA='C:/Windows/System32/Drivers/DriverData'
export GIT_INSTALL_ROOT='C:/Users/????/scoop/apps/git/current'
export HOME='C:/Users/????'
export HOMEDRIVE='C:'
export HOMEPATH='/Users/????'
export LOCALAPPDATA='C:/Users/????/AppData/Local'
export LOGNAME='????'
export LOGONSERVER='//LAPTOP-12HPO6T3'
export NUMBER_OF_PROCESSORS='20'
export ONEDRIVE='C:/Users/????/OneDrive'
export OS='Windows_NT'
export PATH='C:/Users/????/scoop/apps/w64devkit/current/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Windows/System32/OpenSSH/;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C:/Users/????/.cargo/bin;C:/Users/????/scoop/shims;C:/Users/????/AppData/Local/UniGetUI/Chocolatey/bin;C:/Users/????/AppData/Local/Microsoft/WindowsApps'
export PATHEXT='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL'
export PROCESSOR_ARCHITECTURE='AMD64'
export PROCESSOR_IDENTIFIER='Intel64 Family 6 Model 154 Stepping 3, GenuineIntel'
export PROCESSOR_LEVEL='6'
export PROCESSOR_REVISION='9a03'
export PROGRAMDATA='C:/ProgramData'
export PROGRAMFILES='C:/Program Files'
export PROGRAMFILES_X86_='C:/Program Files (x86)'
export PROGRAMW6432='C:/Program Files'
export PSMODULEPATH='C:/Users/????/Documents/WindowsPowerShell/Modules;C:/Program Files/WindowsPowerShell/Modules;C:/Windows/system32/WindowsPowerShell/v1.0/Modules'
export PUBLIC='C:/Users/Public'
export PWD='C:/Users/????'
export ProgramFiles
export SHELL='/bin/sh'
export SHLVL='1'
export SYSTEMDRIVE='C:'
export SYSTEMROOT='C:\Windows'
export TEMP='C:/Users/98BD~1/AppData/Local/Temp'
export TMP='C:/Users/98BD~1/AppData/Local/Temp'
export USER='????'
export USERDOMAIN='LAPTOP-12HPO6T3'
export USERDOMAIN_ROAMINGPROFILE='LAPTOP-12HPO6T3'
export USERNAME='????'
export USERPROFILE='C:/Users/????'
export WINDIR='C:/Windows'
export WSLENV='WT_SESSION::WT_PROFILE_ID'
export WT_PROFILE_ID='{61c54bbd-c2c6-5271-96e7-009a87ff44bf}'
export WT_SESSION='cdc81066-8a0b-481c-a611-2772de1b5205'
export ZES_ENABLE_SYSMAN='1'
~ $ which
bash: unable to spawn shell
~ $ alias
~ $ dfg
bash: dfg: not found
~ $
```

If it helps, I'm running Windows 11 21H2.

**Comment by avih** [comment]
Probably needs the unicode variant for that. See https://github.com/skeeto/w64devkit/issues/162#issuecomment-2295267026

**Comment by ghostplant** [comment]
> Probably needs the unicode variant for that. See [skeeto/w64devkit#162 (comment)](https://github.com/skeeto/w64devkit/issues/162#issuecomment-2295267026)

I uses Win10 32bit, is there a 32-bit prebuilt version that supports unicode?

**Comment by rmyorston** [comment]
@ghostplant I've built a 32-bit Unicode binary, just for you. It's based on the latest prerelease code. I don't have 32-bit Windows 10 so it's only been tested on 64-bit Windows 11.

It's available here: [busybox_pre32u.exe](https://frippery.org/files/busybox/prerelease/busybox_pre32u.exe)

**Comment by ghostplant** [comment]
@rmyorston Thank you! I tried that which works on some machines, but few of them reports malware and being deleted forcely. 

1. May I know how to refine the source to ensure it is not detected a malware?https://www.virscan.org/report/114fd013e27b1c45c3d92dbd7c860fccbdd0c04b176b39bfb8c7512ad970e5fe

2. I run this item on XP which reports not a valid Win32 application. Do you know why is that? The standard busybox32.exe runs without problems, but just have character display issues.

**Comment by avih** [comment]
> 1. May I know how to refine the source to ensure it is not detected a malware?

That does not depend on the source code. It depends on the virus scanner. If you don't trust the binary, feel free to build it yourself, but it's unlikely to change what the anti-virus reports.

> 2\. I run this item on XP which reports not a valid Win32 application

The unicode binary is for windows 10 or later.

The unicode binary can't run on XP. There's no solution for that currently, and don't hold your breath.

**Comment by ghostplant** [comment]
![image](https://github.com/user-attachments/assets/bb9e5d43-9779-4dfc-9aea-fa8af5d8076d)

OK, I verified that it doesn't work on Windows 2016 LTSC as well. Actually, is it possible to set default encoding type as local "ANSI"?

**Comment by avih** [comment]
No. For anything which is not windows 10 or later, use the normal binaries. Not the unicode binaries.

**Comment by ghostplant** [comment]
Do you know why normal binaries doesn't even support ANSI character display (the encoding type, such as GBK/..)?

**Comment by ale5000-git** [comment]
> Do you know why normal binaries doesn't even support ANSI character display (the encoding type, such as GBK/..)?

This problems happen only on your configuration, the normal binary for me display characters (of my language) correctly.
I suggest to open a new issue with all the details of your problem.
