### ISSUE TITLE
make reports random failure filename

### ISSUE THREAD

**Issue by janko-jj** [rmyorston/busybox-w32#449]
When the make process fails it seems that the filename is not correctly passed in some circumstances. If I run more times the same make, I get "random" filenames that sometimes match some part of some filename, sometimes it's just "something":

```
make: (:48): failed to build 'build/pp.rel' exit 1

make: (i-lib.c:48): failed to build 'build/pp.rel' exit 1

make: (¥³T:48): failed to build 'build/pp.rel' exit 1
```

The main file is "Makefile", but in this case in its line 13 is:   `include ../sub_make.inc`   and that make ends in line 25. I believe that line 48 must be the line 48 in the ../sub_make.inc  which is properly processed but then not printed correctly?

Observed on more versions, the lowest tried 

`BusyBox v1.37.0-FRP-5301-gda71f7c57 (2024-02-20 13:56:32 GMT)`

the highest tried

`BusyBox v1.37.0-PRE-5460-g4b7b4a960 (2024-08-19 08:29:23 BST)`

**Comment by rmyorston** [comment]
Thanks for the report. The problem should be fixed in the [latest prerelease](https://frippery.org/files/busybox/prerelease) binaries (PRE-5461 or above).

**Comment by janko-jj** [comment]
I consistently see the inc file name with PRE-5461, thanks!
