### ISSUE TITLE
Inclusion of ln applete and implemented as junctions

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#45]
It's a bit of work, but implementing ln as an applet but in the underlying implementation using NTFS junctions for the implementation.
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365006%28v=vs.85%29.aspx for more info.
The reason I would prefer this meathod is that the CygWin kludge for ln is specific to CygWin and has no use inside of Windows, and as for MinGW, if I remember right, it copies the file rather then use the native junction option to maintain usability with older windows filesystems.

**Comment by rmyorston** [comment]
I've enabled the `ln` applet in the default configuration.  It only supports hard links, though.

My understanding is that junctions only work for directories while symbolic links require additional privileges.  Later, perhaps.

**Comment by dgtlrift** [comment]
Seems to work as advertised... I'd close this with opening another specific to symbolic links to sit in your parking lot.
