### ISSUE TITLE
Override help with BB_OVERRIDE_APPLETS

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#452]
I was trying to override help with an external script but still make the original available with this:
```
export BB_OVERRIDE_APPLETS='help'
alias shellhelp="BB_OVERRIDE_APPLETS='' help"
```
but it doesn't seem to work.

Any suggestion?

**Comment by rmyorston** [comment]
`help` is a shell builtin, so it can't be overridden by `BB_OVERRIDE_APPLETS`.

>Any suggestion?

```
~ $ cat ~/bin/help
#!/bin/sh

echo "not help"
~ $ export PATH="C:/Users/rmy/bin;%builtin;$PATH"
~ $ alias shellhelp="env -i sh -c help"
~ $
~ $ help
not help
~ $ shellhelp
Built-in commands:
------------------
        . : [ [[ alias break cd chdir command continue echo eval exec
        exit export false getopts hash help history jobs kill let local
        printf pwd read readonly return set shift source test times title
        trap true type ulimit umask unalias unset wait [ [[ ar arch ascii
        ash awk base32 base64 basename bash bc bunzip2 busybox bzcat
        ...
```
The `%builtin` in `PATH` is a characteristic feature of `ash` (not available in GNU `bash`). See the [original ash man page](https://www.in-ulm.de/~mascheck/various/ash/ash-orig.1.html#pathsearch) and the [source of all ash wisdom](https://www.in-ulm.de/~mascheck/various/ash/) for details.

**Comment by ale5000-git** [comment]
Good suggestion, thanks.
