### ISSUE TITLE
Broken behaviour of shell (messed up prompt)

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#460]
I'm using the latest 32-bit prerelease.

I open ash and then run this:
`abcdefghi 2>&- something`

Then I press the up key to reuse the last command and it is messed up like this:
![messed-up](https://github.com/user-attachments/assets/7153e7d6-8037-4078-8a65-31eb7e666b07)

**Comment by rmyorston** [comment]
Well, that took longer to figure out than I'd have liked.

Try the [latest prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5485 or above).

**Comment by ale5000-git** [comment]
Thank you very much, it now works perfectly.
