### ISSUE TITLE
Problems with kill

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#465]
Example:
```
$ kill -9 9936
ash: can't kill pid 9936: Invalid argument
```

Without `-9` it works.

**Comment by rmyorston** [comment]
Should be fixed in the [latest prerelease](https://frippery.org/files/busybox/prerelease) (PRE-5510 or above).

**Comment by ale5000-git** [comment]
Thanks, the problem is fixed.
But I have one doubt when killing `$PPID` with:
`kill -9 $PPID`
shouldn't `$PPID` became 1 or I'm wrong?

**Comment by rmyorston** [comment]
>shouldn't $PPID became 1

POSIX says, of `PPID`:
>Set by the shell to the decimal value of its parent process ID during initialization of the shell.

There's no mention of a requirement for the value to be updated if the parent changes after initialisation.

I've tried a handful of shells and none of them updates `PPID`.

**Comment by ale5000-git** [comment]
Ok, so it is fine.
