### ISSUE TITLE
 awk escape backslash twice  in function gsub and sub's  replacement param

### ISSUE THREAD

**Issue by q5n** [rmyorston/busybox-w32#466]
I know gensub support \1 \2 ... \N replacement, then need escape backslash twice
but why gsub and sub's replacement need escape backslash twice？

**e.g.**

` echo "D:/Mydir/My.txt"|awk '{gsub(/\/M/,"\\m");print}'`
> output:
> `D:mydirmy.txt`

` echo "D:/Mydir/My.txt"|awk '{gsub(/\/M/,"\\\\m");print}'`
> output:
> `D:\mydir\my.txt`

**Comment by avih** [comment]
First of all, this behavior is the same as in upstream busybox, so if this is indeed a bug, then it should be reported there. I doubt the win32 variant does anything special (different than upstream) in how awk's `gsub` behaves.

However also, POSIX does have some wording about how the literal REPL string in gsub (as is the case in your examples) behaves with backslashes. It says this:
> Since it was unspecified what the special characters were, for portable scripts to guarantee that characters are printed literally, each character had to be preceded with a `<backslash>`. (For example, a portable script had to use `gsub( ERE, "\\h\\i" )` to produce a replacement string of "hi" .)

So it seems that double backslash in a literal STRING token makes the following char non-special, and if one wants to produce a literal backslash then this requires quad backslash, as you discovered (possibly even six backslashes - 4 for one literal backslash, and two to ensure the `m` is non-special).

However also, this indeed seems different betwen implementations of awk.

In gawk and goawk and the original awk ("one true awk"), for instance, `"\\m"` does what you want, while `"\\\\m"` produces (undesirable) `\\m` at the output.

In mawk, both `"\\m"` and `"\\\\m"` produce the same output which you want (`/M` is replaced with literal `\m`).

And in busybox awk, only `"\\\\m"` produces the output you want.

I'm not sure which of those are more correct as far as the current posix standard goes, but there is some historical baggage here.

Either way, this should probably be reported upstream IMO, after reading the POSIX awk spec carefully to ensure you understand how it's expected to behave according to the current standard.

**Comment by q5n** [comment]
@avih thanks for your reply！

I test it in busybox.net/live_bbox:
![image](https://github.com/user-attachments/assets/b823179c-c04d-4e32-9528-2ef3bd2f32c4)

**Comment by avih** [comment]
Then apparently it has changed since 2012. I tested with current busybox master (I just compiled it).

**Comment by q5n** [comment]
Yes, it was only changed in busybox-1.37.0 version

**Comment by rmyorston** [comment]
>Yes, it was only changed in busybox-1.37.0 version

busybox-w32 tracks the main branch of upstream BusyBox, not individual releases, so the change actually arrived in the FRP-5181 release:
```sh
~ $ echo "D:/Mydir/My.txt"|./busybox-w32-FRP-5007-g82accfc19 awk '{gsub(/\/M/,"\\\\m");print}'
D:\\mydir\\my.txt
~ $
~ $
~ $ echo "D:/Mydir/My.txt"|./busybox-w32-FRP-5181-g5c1a3b00e awk '{gsub(/\/M/,"\\\\m");print}'
D:\mydir\my.txt
~ $
```
The change was introduced by the upstream maintainer and _I_ don't have any particular reason to question their judgment on the matter.

As @avih suggests, if you have any queries about this you should address them upstream. They have a [mailing list](https://busybox.net/lists.html) and a [bug tracker](https://bugs.busybox.net/).

(And I note that bug [12531](https://bugs.busybox.net/show_bug.cgi?id=12531) makes _some_ mention of backslashes in regular expressions in `awk`, though I don't know if it's relevant.)

**Comment by q5n** [comment]
got it
