### ISSUE TITLE
I want to check the existence of file.exe with test -x file

### ISSUE THREAD

**Issue by vj23a** [rmyorston/busybox-w32#469]
Nice to meet you.
Can't you check the existence of file.exe using test -x file?

Example:
```
touch file.exe
test -x file; echo $?
0 -> 1
```
Please

**Comment by rmyorston** [comment]
Sure, `test -x` tests if a file exists and appears to be executable. It returns an exit code of 0 when the test succeeds.
```
~ $ touch file.exe
~ $ ls -l file.exe
-rwxrwxr-x    1 rmy      rmy              0 Oct 26 15:05 file.exe
~ $ if test -x file.exe; then echo 'it exists'; fi
it exists
~ $
```
Of course, an empty file isn't _really_ executable:
```
~ $ ./file.exe
sh: ./file.exe: Exec format error
~ $
```
It just _appears_ to be executable to `test` because busybox-w32 treats any file with the extension `.exe` as having execute permission.

**Comment by ale5000-git** [comment]
@vj23a
Any command returns 0 when succeed, any other value when fails.

As already said:
`test -x file` check that exist and is executable.
Just to test the existance there is: `test -e file`
To check that exist and is a regular file (not a folder or other): `test -f file`

To search an executable where you don't know the path you can use: `command -v file`

**Comment by vj23a** [comment]
When you run text -x file, I want you to check for the existence of the file name "file" + ".exe" (file.exe).

**Comment by ale5000-git** [comment]
That would be a bug.
Note that both `file` and `file.exe` may exist and may be different files, the test of existance isn't the one that shuold provide extension auto-completion.

If it is an executable you can do what you want with this:
if command -v 'file'  1>/dev/null; then
  echo 'Exist'
else
  echo 'Not exist'
fi

`command -v file` would find both `file` or `file.exe` (as long as they are executables even without the .exe extension).
Please note that busybox can execute `file` even without extension, so even an executable called `file` can be executed directly.

**Comment by vj23a** [comment]
This is a specification adopted in msys2, so I would appreciate it if you would give it some consideration.

**Comment by rmyorston** [comment]
>When you run text -x file, I want you to check for the existence of the file name "file" + ".exe" (file.exe).

Sorry, that is indeed what you requested. I missed it due to auto-completion in my brain.

The question of support for MSYS2's approach to such things was considered (and rejected) in issue #405.

**Comment by vj23a** [comment]
I had missed it being mentioned in the past.
Thank you for your response.

**Comment by ale5000-git** [comment]
@vj23a

The code can be easily made compatible with both.
If you do this:
```
file_path='/myfolder/myfile'
if file_path="$(command -v "${file_path}")"; then
  echo "File exist and it is here: ${file_path}"
else
  echo 'Not exist'
fi

```
So now `${file_path}` include the extension and `test -x "${file_path}"` now works.
