### ISSUE TITLE
basename and back-slashed path names

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#48]
I'm not sure what's appropriate here, but basename doesn't work with back-slashed paths.  Either basename could support the backslash truncation to the basename, or adding readlink and having it understand backslashes to convert to forward slashes to be used by basename.

ie:
basename \`readlink -f ${WinPath}\`

**Comment by rmyorston** [comment]
I've improved support for backslashes in the library routine that basename uses.

There's a new binary on my website.

**Comment by dgtlrift** [comment]
Tested with latest git pull.  Confirmed this works as expected with the last update.
