### ISSUE TITLE
Can not identify directory?

### ISSUE THREAD

**Issue by aswjh** [rmyorston/busybox-w32#49]
on XP(same problem on linux):
![bb](https://cloud.githubusercontent.com/assets/6280240/11491893/07dbc8ec-97de-11e5-9d35-5128fdcbbeff.PNG)

**Comment by rmyorston** [comment]
I don't understand the problem.  You appear to be trying to execute a directory.  As expected it fails.

**Comment by aswjh** [comment]
The error is a bit confusing. No other problem.

**Comment by rmyorston** [comment]
I don't think trying to execute a directory is worth a special case.  The error messages are different on Linux and Windows but both make some sense.  Linux says 'Permission denied' while Windows says 'Exec format error'.

The exit status is 127, which may be considered contrary to POSIX.  POSIX says:

>If a command is not found, the exit status shall be 127. If the command name is found, but it is not an executable utility, the exit status shall be 126.

I see that dash, on which BusyBox ash is based, also returns an exit status of 127 in this case.  I wouldn't consider this worth fixing unless someone is really concerned about it.
