### ISSUE TITLE
calling an alias from function in ash

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#50]
I'm seeing that aliases don't (seem) to work when calling from a function in ash.

```
# There is a newline in that string after $PWD.
alias Apushd='POPD_STACK_DIRS="$PWD
${POPD_STACK_DIRS}"; echo "${POPD_STACK_DIRS}" | xargs ; cd'

pushd() {
	export POPD_STACK_DIRS="$PWD
${POPD_STACK_DIRS}"
	echo "${POPD_STACK_DIRS}" | xargs
	cd "${1}"
}

# This is all one line.
alias popd='LINE=`echo "\${POPD_STACK_DIRS}" | sed -ne '1p'`;[ "$LINE" != "" ] && cd $LINE;POPD_STACK_DIRS=`echo "\${POPD_STACK_DIRS}" | sed -e '1d'`;echo "${POPD_STACK_DIRS}" | xargs'
```

what I have noticed is that I can call the function from another ash function - ie:
```
log_pushd() {
	log_trace "PUSHD \"${1}\""
	pushd "$1"
}

log_popd() {
	_lRet=$(popd "$1")
	log_trace "POPD \"${_lRet}\""
}
```

but switching to use the alias form gives me the error:
```
C:\P\blah\pp-build.sh: C:/P/blah/post-build.sh: line 47: pushd: not found
```

Is this an issue with Ash, or by design with ash?

**Comment by rmyorston** [comment]
Dash doesn't have this issue; upstream BusyBox does.  I'll look into it.

**Comment by rmyorston** [comment]
Sorry, I was too hasty and botched my tests.  Can you provide a simpler test case?

**Comment by dgtlrift** [comment]
This looks like it's by design... CygWin, Linux, et al all seem to do the same.
```
#!/bin/env bash

alias aTest='echo '

fTest() {
        echo "${@}"
}


fTestF() {
        fTest fTestF
}


fTestA() {
        aTest fTesta
}


fTestF
fTestA
```

**Comment by rmyorston** [comment]
Your sample script fails when run in bash, but not in dash, BusyBox ash or bash in POSIX mode.

The bash reference manual says:

>The rules concerning the definition and use of aliases are somewhat confusing.
>
>For almost every purpose, shell functions are preferred over aliases.

I'm having a hard time making sense of how aliases are supposed to behave in bash and POSIX, so I tend to agree.

**Comment by dgtlrift** [comment]
I believe this can be closed as it works as designed.
