### ISSUE TITLE
reduce Windows .exe size by a few kilobytes

### ISSUE THREAD

**Issue by vszakats** [rmyorston/busybox-w32#51]
Try adding `-fno-ident` to CFLAGS.

By default annoying C compiler ID string is built in each object 
file and they will be linked into the final executable without 
deduplication. This option will drop them all. (some may still 
appear from compiler's objects)

**Comment by rmyorston** [comment]
Good idea, thank you.

I've taken the opportunity to make a new binary.  This makes it 3% smaller.

**Comment by vszakats** [comment]
Great, thank you very much!
