### ISSUE TITLE
adding modeless editor

### ISSUE THREAD

**Issue by jlrn7** [rmyorston/busybox-w32#53]
Hello! I'm trying to add `ue` as a modeless editor besides `vi` and I followed the instructions given in [the main busybox page](https://busybox.net/FAQ.html#adding) to include it, but somehow it didn't work. How can I share it to troubleshoot it? Thanks in advance,

**Comment by jlrn7** [comment]
Turns out that you need to edit `Config.src`, `Kbuild.src`, `applets.src.h` and `usage.src.h` instead of the generated ones, as I did in the first time.— The editor still doesn't work, but now it's compiling...

**Comment by rmyorston** [comment]
I'm pleased to hear you were able to make progress.  If I can be of any help you can contact me by email:  rmy@pobox.com
