### ISSUE TITLE
[question] What's the relation to pclouds/busybox-w32 ?

### ISSUE THREAD

**Issue by avih** [rmyorston/busybox-w32#54]
This repo is a fork of pclouds/busybox-w32 but ahead of it by 90 commits (as of now), yet both seems active. Also, the readme at pclouds/busybox-w32 points to this (rmyorston/busybox-w32) repo..

So what's going on?

**Comment by rmyorston** [comment]
The only activity in pclouds' repo in the last four years is a fast-forward merge with mine a few weeks ago (which, of course, pulled in my README).

pclouds has said he's no longer active in busybox-w32 and has [suggested] (https://github.com/pclouds/busybox-w32/issues/21) using my fork instead.

**Comment by avih** [comment]
Thanks.
