### ISSUE TITLE
"echo -n 54321 | tail -c 3" does not work as expected

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#56]
From BusyBox 1.22.1 on Ubuntu, the command `echo -n 54321 | tail -c 3` produces `321`  as expected, but from BusyBox-w32 v1.25.0.git I get `543` with the same command. I would expected `321`

**Comment by dgtlrift** [comment]
The issue seems to be related to pipes.
See the following:

```
C:/P/Tools $ echo -n 987654321 > test.txt
C:/P/Tools $ tail -c 3 test.txt
321
C:/P/Tools $ cat test.txt | tail -c 3
987
C:/P/Tools $

```

**Comment by rmyorston** [comment]
Definitely related to pipes.  ```tail``` tries to use ```lseek``` as an optimisation.  ```lseek``` doesn't work with pipes but on Windows it doesn't return an error so ```tail``` thinks the seek has succeeded.

I've added a wrapper for ```lseek``` that returns an error if its argument isn't a file on disk.  Try the latest binary.

**Comment by dgtlrift** [comment]
Confirmed - fixed in tip.
