### ISSUE TITLE
locale app support in win32

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#57]
Using the windows command `dism /online /get-intl` can be clumsy and including support for `locale` even as a read-only command would be helpful.

Even with the command, it gives me the error under `busybox`:
`You cannot service a running 64-bit operating system with a 32-bit version of DISM.`

It would be even better if it could support temporarily setting the locale for inherited tasks executed within it's context as certain windows programs (ie `tf.exe`) show different date formats depending on locale and causes parsing problems.

**Comment by dgtlrift** [comment]
So I've written these two functions...
```
getLocale() {
	local LOCALE=$('C:\windows\sysnative\dism' /online /get-intl | grep -i locale | awk -F: '{ print $2 }')
	echo ${LOCALE}
}

setLocale() {
	local locale="$1"
	local tmp="$(echo ${TEMP}/locale.${RANDOM}.xml| sed -e 's/\//\\/g')"
	
	echo -n '' > "${tmp}"
	echo    '<gs:GlobalizationServices xmlns:gs="urn:longhornGlobalizationUnattend">' >> "${tmp}"
    echo    '<!--User List-->'					>> "${tmp}"
    echo    '<gs:UserList>'						>> "${tmp}"
    echo    '	<gs:User UserID="Current"/>'	>> "${tmp}"
    echo    '</gs:UserList>'					>> "${tmp}"
    echo    '<!-- User Locale-->'				>> "${tmp}"
    echo    '<gs:UserLocale>'					>> "${tmp}"
    echo -n '	<gs:Locale Name="'				>> "${tmp}"
	echo -n    "${locale}"						>> "${tmp}"
	echo       '" SetAsCurrent="true"/>'		>> "${tmp}"
    echo    '</gs:UserLocale>'					>> "${tmp}"
	echo    '</gs:GlobalizationServices>'		>> "${tmp}"
		
	echo "tmp='${tmp}'"
	cat "${tmp}"
#	local result=$(control intl.cpl,, /f:\"${tmp}\")
	control intl.cpl,, "/f:\\\"${tmp}\\\""
	echo "result=${result}"	
	echo "local=${locale}"
}
```
First one (getLocale) works great... the second (setLocale) not so well... I can run the command from the DOS prompt, but not from within BusyBox bash.... any ideas to why?

**Comment by rmyorston** [comment]
Sorry, no ideas. I can't even get the ```control``` command to work from the DOS prompt in my test system.  But I don't really know what you're trying to do here:  this is way beyond my Windows knowledge.

**Comment by dgtlrift** [comment]
I'm guessing you are trying this from Windows XP - instead of `control intl.cpl,, /f:"filename.xml"`, try `RUNDLL32.EXE SHELL32.DLL,Control_RunDLL intl.cpl,, /f:"C:\filename.xml"` for the same result in CMD prompt.

Essentially, the first function gets the current Locale settings from Windows, and the second is setting a locale... the "easiest" way to do this programatically is with the International control panel with an xml file.

A few things regarding the /f option in `RUNDLL32.EXE SHELL32.DLL,Control_RunDLL intl.cpl,, /f:"C:\filename.xml"` - the quotes are critical, and apparently, the filename must be a full path, so no relative paths...

**Comment by rmyorston** [comment]
Not XP; I'm using Windows 8.1 Enterprise Evaluation.

I used your setLocale script to generate the XML file, and a brief search on the internet told me about the issue with quotes, but the ```control``` command doesn't seem to have any effect.

**Comment by dgtlrift** [comment]
Looks like the command has no issue in `DOS/CMD` but fails under `busybox`.
`RUNDLL32.EXE SHELL32.DLL,Control_RunDLL intl.cpl,, /f:"C:\filename.xml"`
Is there (other then `set -x`) an option to trace execution within `busybox`?

**Comment by dgtlrift** [comment]
My guess is there there is some subtle difference in the way the quotes are handled when being passed from `busybox` vs the `DOS/CMD` prompt.

**Comment by rmyorston** [comment]
Yes, quotes are a pain.  But still, it should be possible to pass them through to a Windows executable.  I wrote a trivial program to echo its arguments which does this when run from busybox shell:
```
$ echox "/f:\"blobby\""
echox
/f:"blobby"
$
```
That should be good enough.

When things fail mysteriously it sometimes helps to use the ```-X``` shell option (which has to be the first, and it's a capital ```X```).  This prevents the shell from changing backslashes in environment variables into forward slashes.  Some Windows code simply doesn't work when presented with forward slashes in paths in environment variables.

**Comment by dgtlrift** [comment]
ugh... in a world of workarounds when it comes to anything microsoft, I created a batchfile `intl.cmd` that looks like:```

@echo off

setlocal
set BAT_DIR=%~dp0
set INTL_XML_FILE=%~1

:: echo BAT_DIR="%BAT_DIR%"
:: echo INTL_XML_FILE="%INTL_XML_FILE%"

RUNDLL32.EXE SHELL32.DLL,Control_RunDLL intl.cpl,, /f:"%INTL_XML_FILE%"
```
This allows me to call the batch file from the busybox script and get it to work... If I had to put money on it, I'm guessing it's either the quotes being swallowed, or possibly more likely, the `/f` is improperly parsed by `RUNDLL32.exe` with argv[0] being set up with `C:/windows/system32/RUNDLL32.EXE` ... it bothers me that there's no root understanding as to the failure as there is no diagnostic info other then the event log under `%SystemRoot%\System32\Winevt\Logs\Microsoft-Windows-International%4Operational.evtx` specifying failure or success, but that is all really beyond the scope of busybox.

At least this is all documented here for someone else to understand the issue.
