### ISSUE TITLE
Missing support for -j parameter of unzip

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#59]
Please add support to this parameter in the unzip utility:

-j junk paths. The archive's directory structure is not recreated; all files are deposited in the extraction directory (by default, the current one).

**Comment by rmyorston** [comment]
I prefer to keep differences between busybox-w32 and upstream to a minimum, so this isn't a feature I'd add if it isn't supported upstream.

I see you've raised an enhancement request upstream. If this results in the -j option being supported in BusyBox it will also be available in busybox-w32.

**Comment by ale5000-git** [comment]
@rmyorston: It is now supported.
Ref: https://bugs.busybox.net/show_bug.cgi?id=9126

**Comment by rmyorston** [comment]
I've merged the latest upstream BusyBox. New binaries with support for ```unzip -j``` are available.  They have version FRP-1325-g1f01a34ec.

**Comment by ale5000-git** [comment]
Thanks :)
