### ISSUE TITLE
busybox utf-8 support

### ISSUE THREAD

**Issue by mega7star** [rmyorston/busybox-w32#61]
Hi!
Does busybox support utf-8?
I have this
![file](https://cloud.githubusercontent.com/assets/1462355/17458643/68a99642-5c21-11e6-91d7-72c3a7a36352.PNG)

**Comment by rmyorston** [comment]
No, busybox-w32 doesn't support UTF-8.

Character encodings and code pages are a huge mess. Windows has many layers of legacy support. Upstream BusyBox, of course, supports the Unix way of doing things. (It also has some wide character support, though it isn't enabled in busybox-w32 and doesn't seem to be widely used.)

It might be possible to improve support for character encodings in busybox-w32 but it won't be easy and it isn't a priority.

**Comment by mega7star** [comment]
Ok, thanks for the prompt reply.
