### ISSUE TITLE
Allow Disabling winansi Emulation

### ISSUE THREAD

**Issue by mentalisttraceur** [rmyorston/busybox-w32#64]
On terminal emulators which properly support a wide range of ANSI escape sequences ( for example, ConEmu ), busybox-w32's winansi.c functionality is unnecessary, and often provides a worse experience ( ConEmu supports the escape sequences for 24-bit color, etc). They also don't "stack", since the ANSI escape sequences are stripped by busybox-w32 before the terminal emulator sees them.

It would be great if an option could be provided to suppress busybox-w32's own ANSI emulation for those of us who use console emulators with a richer feature set.

**Comment by mentalisttraceur** [comment]
Here is just one example of the difference:

![conemu_v_busybox-w32_ansi](https://cloud.githubusercontent.com/assets/6531708/20159246/576490de-a6d7-11e6-8b95-bafacd7b6073.png)

The above was ran inside a ConEmu window, in the `cmd` interpreter, the first is using Windows `type` command (equivalent of `cat`), the second is using the busybox-w32 `cat`. I can attach the file being cat-ed out as well, if desired (it ships with ConEmu).

**Comment by mentalisttraceur** [comment]
Since it looks like busybox-w32 handles this conversion on a per-applet basis (makes since, since the programs are meant to be able to run outside of the busybox shell), I propose using an environment variable to control this.

**Comment by rmyorston** [comment]
OK, setting the (currently undocumented) environment variable ```BB_SKIP_ANSI_EMULATION``` causes escape sequences to be passed to the terminal verbatim. The value of the environment doesn't matter, it can be set to anything.

There's a new binary on my website.

**Comment by mentalisttraceur** [comment]
Thanks, seems to work well from my limited testing yesterday.

**Comment by rmyorston** [comment]
Documented in README.md
