### ISSUE TITLE
Unable to spawn shell

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#66]
I have tried:
`busybox sh -c "grep sdk build.prop"`
`busybox ash -c "grep sdk build.prop"`
and I alwasy get "unable to spawn shell".

I'm on Windows 10.
Is it a bug or is there something wrong in my command?

PS: Using grep directly works but I need to call it from within a shell.

**Comment by rmyorston** [comment]
Works for me on Windows 10.

Which version of Windows and busybox.exe are you using?  Where is busybox.exe installed?  32 or 64 bit?

**Comment by ale5000-git** [comment]
Windows 10 64-bit
BusyBox v1.26.0-FRP-811-g71ecc80

I have checked and it was in the wrong folder, I have moved it to SysWOW64 and it started working.
But now it fail at `test_2=$(cut -d "=" -f 2 <<< $test_1)` with `syntax error: unexpected redirection`

**Comment by rmyorston** [comment]
The `<<<` redirection is a bashism.  It isn't supported.

**Comment by rmyorston** [comment]
How about `test_2=$(echo $test_1 | cut -d "=" -f 2)`?

**Comment by ale5000-git** [comment]
Thanks, it is much simpler like that, sorry I'm not very experienced with this.
