### ISSUE TITLE
command completion

### ISSUE THREAD

**Issue by JochenHayek** [rmyorston/busybox-w32#68]
On https://frippery.org/busybox/ I found this statement:

> Recent changes include:
> tab completion of commands in the shell includes built-in applets and excludes non-executables on PATH

Looks like .pl files are considered as executables, whereas .sh files are not.

Is this something you are aware of?
Is this something I can configure?
Is there "a way around".

Kind regards,
~J

**Comment by JochenHayek** [comment]
>

**Comment by rmyorston** [comment]
In this context the file extension doesn't matter. A text file is considered to be executable if the first characters are ```#!```.

**Comment by JochenHayek** [comment]
great! thanks!
