### ISSUE TITLE
Enable CONFIG_FEATURE_FLOAT_SLEEP ?

### ISSUE THREAD

**Issue by tkelman** [rmyorston/busybox-w32#69]
Would this work correctly? Cost a noticeable amount in size? Being able to do `sleep 0.1` would be useful, instead of getting `invalid number '0.1'`.

**Comment by rmyorston** [comment]
For some value of 'correctly', yes.  I've implemented the required ```nanosleep``` function using Windows ```Sleep``` which takes an argument in milliseconds (though that doesn't mean you'll get millisecond accuracy).  It adds 512 bytes to the binary, so not a big deal.

DO NOT use this to control your nuclear reactor or robotic heart surgeon.

**Comment by tkelman** [comment]
Thanks!

> DO NOT use this to control your nuclear reactor or robotic heart surgeon.

Roger. That's what the whole "no warranty" clause is for.
