### ISSUE TITLE
mkdir -p 'C:\path\exists\but\this\path\doesnt'

### ISSUE THREAD

**Issue by dgtlrift** [rmyorston/busybox-w32#71]
Using:
mkdir -p 'C:\path\exists\but\this\path\doesnt'
fails with
mkdir: can't create directory 'C:\path\exists\but\this\path\doesnt': No such file or directory

**Comment by rmyorston** [comment]
The function that creates directories only handled forward slashes in paths.  Fixed in the code, I'll make a new binary some other time.

**Comment by rmyorston** [comment]
Binaries with version FRP-878 or later have the fix for this issue.
