### ISSUE TITLE
awk match string function does not allow capture group

### ISSUE THREAD

**Issue by an-dr-eas-k** [rmyorston/busybox-w32#73]
I use the match function from awk with pattern groups but the resulting array is empty when a match occurs.

`
echo "abcdef" | awk '{if(match($0, /b(.*)e/, a)) {print a[1]}}'
`

* inside `busybox sh` environment, this prints an empty line.
* inside cygwin environment, it prints `cd`.

I expect, awk from busybox fills the array `a`.

**Comment by rmyorston** [comment]
The ```match``` function with three arguments appears to be a GNU extension; it isn't mentioned in the POSIX awk documentation.  Upstream BusyBox doesn't support the three-argument ```match``` so the Windows port doesn't either.

**Comment by an-dr-eas-k** [comment]
That resolves the issue. (And not my problem... :unamused: ) 

Anyways: Cheers!
