### ISSUE TITLE
busybox patch without parameters

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#74]
Running `busybox patch` without parameters just sit-in forever without doing anything and never exit.

I'm using the latest busybox_safe.exe

**Comment by rmyorston** [comment]
Isn't that what ```patch``` is supposed to do?  It's waiting for the patch on standard input (which needs to be terminated with ctrl-Z on WIndows).

```busybox cat``` does the same!

**Comment by ale5000-git** [comment]
Sorry I didn't know, I have thought it would show help.

**Comment by rmyorston** [comment]
It's possible to get help on any BusyBox applet with either ```busybox --help applet_name``` or ```busybox applet_name --help```.
