### ISSUE TITLE
wildcards broken

### ISSUE THREAD

**Issue by eadmaster** [rmyorston/busybox-w32#9]
e.g.:

```
> busybox.exe grep nircmd.exe *.bat
grep: *.bat: Invalid argument
```

the older v1.19.1 build by pclouds worked fine

**Comment by eadmaster** [comment]
what about detecting at runtime the current shell and if it is Windows' cmd.exe force wildcard expansion with (glob)[http://www.gnu.org/software/libc/manual/html_node/Calling-Glob.html#Calling-Glob] ?

glob.h is now available in mingw.

**Comment by rmyorston** [comment]
I'm not too keen on this idea:

- busybox-w32 is now built with mingw-w64: it doesn't have `glob.h`
- mingw's version of `glob` is POSIX(-ish) not Windows
- It would require additional code to handle globbing by hand

**Comment by eadmaster** [comment]
Ok, Windows has the [FindFirstFile function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)...

**Comment by rmyorston** [comment]
Sure, it would be possible to write another implementation of globbing.  I don't think it's worth the effort, though.

**Comment by eadmaster** [comment]
as a workaround i've tried to wrap the command inside a shell, but it does not work:

     busybox.exe sh -c "ls C:\*"

do you know any other workaround?

**Comment by rmyorston** [comment]
Your example won't work because the backslash escapes the asterisk.  Using a slash instead of the backslash doesn't work for an entirely different reason: the wildcard is expanded in the current directory instead of the root of the C: drive.  This is some weird Windows thing: I'll see if I can do something about it.  This command:
```
buysybox.exe sh -c "ls *"
```
does work.

Would it help if I provided a binary with Windows globbing enabled?

**Comment by eadmaster** [comment]
yes, an updated binary with Windows globbing enabled would help, thank you...

**Comment by eadmaster** [comment]
yes, an updated binary with Windows globbing enabled would help, thank you...

**Comment by rmyorston** [comment]
My website now has a prebuilt binary with Windows wildcards enabled:

http://frippery.org/files/busybox/busybox_glob.exe

There's a link to it from the page on globbing.  It might not be updated as frequently as the main build.
