### ISSUE TITLE
"which" problem

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#94]
I have zip.exe in c:\my_dir

I set:
`PATH="c:\my_dir;${PATH}"`

Then when I use:
`which 'zip' || echo 'Fail'`
It fail.

Have I done something wrong?

**Comment by rmyorston** [comment]
No, you're not doing anything wrong.

Upstream has recently made lots more applets ```NOFORK```, including ```which```.  This is more efficient but there's a documented bug in the shell which means that ```NOFORK``` applets don't see changed variables in their environment.

Disabling special treatment of ```NOFORK``` applets in the shell (by unsetting ```CONFIG_FEATURE_SH_NOFORK```) makes the problem go away but loses the advantages of ```NOFORK```.  I'm not sure how to proceed, I'll think about it...

**Comment by ale5000-git** [comment]
I know when I change variables, so the most performant way, I think, is to reload them only when needed.
I propose to add a command to reload them in the current shell like "reloadvars", so after that all NOFORK applets will works fine as is.

**Comment by rmyorston** [comment]
Upstream has fixed the shell so ```which``` now works as expected.  I've merged with upstream so busybox-w32 versions from ```FRP-1709-g65e9c0ad9``` have the fix.

**Comment by ale5000-git** [comment]
It works perfectly, thansk :)
