### ISSUE TITLE
date formatting bug?

### ISSUE THREAD

**Issue by ejzhang** [rmyorston/busybox-w32#95]
Default date formatting output with prefix 0, e.g. busybox.exe date "+%Y-%m-%d" output "2017-12-08", if i want to remove the prefix 0 with the placeholder (-) of date formatting parameters, e.g. busybox.exe date "+%Y-%m-%-d", but the output is empty instead of "2017-12-8".
I test ok with official busybox (https://busybox.net/downloads/binaries/) in CentOS.

**Comment by rmyorston** [comment]
The ```date``` applet uses the system-provided function ```strftime``` to implement formatted output.  What we're seeing here is a difference between the behaviour of ```strftime``` in glibc and the Microsoft C runtime.  glibc uses '-' to prevent padding of numeric values while Microsoft uses '#'.  Both of these are extensions to the ANSI C specification.  It's unfortunate they've used different characters.

As a temporary workaround you can use the format ```"+%Y-%m-%#d"``` to get the output ```"2017-12-8"```.

However, it would probably be better to change busybox-w32 to accept the glibc-style format. I think a major use of busybox-w32 is to allow scripts from Linux/Unix to be run on Microsoft Windows so supporting a compatible date format is a good feature to have.

Does that seem like a good idea?

**Comment by rmyorston** [comment]
The latest build supports the use of '-' as a format flag to disable zero-padding.  The Windows-native '#' also works but isn't portable.

**Comment by ejzhang** [comment]
Thank for your reply very much!
