### ISSUE TITLE
Please add pipe_progress

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#97]
Hi,
it would be nice to have [pv](http://www.ivarch.com/programs/pv.shtml) (for example for monitoring dd).

Example command:
`dd if=/dev/urandom | pv | dd of=/dev/null`

**Comment by rmyorston** [comment]
Pleased to see you're making good use of the new /dev/urandom support in dd. ;-)

Hmm, pv...

As usual, the first question is, "Is it upstream?". To which the answer is, "No".

Upstream does have pipe_progress, which is sufficiently simple that it can be enabled in busybox-w32 with no work whatsoever.  Its output isn't as exciting as pv, though.

**Comment by ale5000-git** [comment]
It was impatient to test /dev/urandom :)

I guess it is fine also pipe_progress.

**Comment by rmyorston** [comment]
I've added pipe_progress to the default configuration.  I haven't made new binaries.

pipe_progress is much more restrictive than pv. It only tells you that *some* data has gone through the pipe in the past second, not how much.

**Comment by yetanothergeek** [comment]
I don't know if it is possible on Windows, but on Linux you can pipe data through the "dd" applet and occasionally send a SIGUSR1 signal to dd to output the progress in bytes.

**Comment by rmyorston** [comment]
Indeed, upstream BusyBox has optional support for SIGUSR1 in ```dd```. It's disabled in busybox-w32, though, because support for signals in Windows is minimal: it only defines six signals and SIGUSR1 isn't one of them.
