### ISSUE TITLE
Please add /dev/urandom support in od

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/busybox-w32#98]
Example:
`od -A n -t d -N 1 /dev/urandom`

**Comment by rmyorston** [comment]
The special devices /dev/zero and /dev/urandom are only supported by the low-level ```open(2)``` and ```read(2)``` function calls. ```od``` uses the higher-level ```fopen(3)``` and ```fread(3)``` calls.

The situation at the moment is inconsistent:
- applets that use ```open/read``` (e.g. ```cat```) support the special devices;
- applets that use ```fopen/fread``` (e.g. ```od```) don't;
- use of the special devices in shell redirection is explicitly forbidden.

While it might be *nice* to support the special devices everywhere I'm not convinced that the additional complexity is worthwhile. Indeed, I'm considering disabling it everywhere except where it's known to work, i.e. in ```dd``` and ```shred```.

Anything else that needs data from /dev/zero or /dev/urandom can get it from ```dd```.

**Comment by rmyorston** [comment]
The /dev/zero and /dev/urandom special devices can now only be used as input files to ```dd```.

Attempting to use them in any other context will fail.

**Comment by rmyorston** [comment]
`/dev/urandom` and `/dev/zero` are now available to use as arguments to all applets and as sources for shell redirections. They're also visible to `ls` and `stat` if given as an explicit argument.

Prerelease binaries with this new feature are available in the [usual place](https://frippery.org/files/busybox/prerelease) (PRE-6067 or later).

**Comment by avih** [comment]
> `/dev/urandom` and `/dev/zero` are now available to use as arguments to all applets and as sources for shell redirections. They're also visible to `ls` and `stat` if given as an explicit argument.

`dd --help` still prints:
> if=/dev/zero and if=/dev/urandom are supported

It can probably be removed now.

**Comment by rmyorston** [comment]
Good idea. I'd updated README.md but missed the `dd` help text.

If anyone cares, there are new prereleases (PRE-6081) in the [usual place](https://frippery.org/files/busybox/prerelease).
